// Code generated by gen-enums. DO NOT EDIT.

package enums

type AccessSubjectType string

const (
	AccessSubjectTypeUser   AccessSubjectType = "USER"
	AccessSubjectTypeClient AccessSubjectType = "CLIENT"
)
