// Code generated by gen-enums. DO NOT EDIT.

package enums

type AccessGrantType string

const (
	AccessGrantTypeRole       AccessGrantType = "ROLE"
	AccessGrantTypePermission AccessGrantType = "PERMISSION"
)

type AccessGrantEffect string

const (
	AccessGrantEffectAllow AccessGrantEffect = "ALLOW"
	AccessGrantEffectDeny  AccessGrantEffect = "DENY"
)
