// Code generated by gen-enums. DO NOT EDIT.

package enums

type AccessScopeType string

const (
	AccessScopeTypeTenant AccessScopeType = "TENANT"
	AccessScopeTypeApp    AccessScopeType = "APP"
	AccessScopeTypeGlobal AccessScopeType = "GLOBAL"
)
