// Code generated by gen-enums. DO NOT EDIT.

package enums

type AuditDataClassification string

const (
	AuditDataClassificationPublic       AuditDataClassification = "public"
	AuditDataClassificationInternal     AuditDataClassification = "internal"
	AuditDataClassificationConfidential AuditDataClassification = "confidential"
	AuditDataClassificationRestricted   AuditDataClassification = "restricted"
)
