// Code generated by gen-enums. DO NOT EDIT.

package enums

type AuditRiskLevel string

const (
	AuditRiskLevelLow      AuditRiskLevel = "low"
	AuditRiskLevelMedium   AuditRiskLevel = "medium"
	AuditRiskLevelHigh     AuditRiskLevel = "high"
	AuditRiskLevelCritical AuditRiskLevel = "critical"
)
