// Code generated by gen-enums. DO NOT EDIT.

package enums

type AuditActorType string

const (
	AuditActorTypeUser    AuditActorType = "user"
	AuditActorTypeService AuditActorType = "service"
	AuditActorTypeSystem  AuditActorType = "system"
	AuditActorTypeAdmin   AuditActorType = "admin"
)
