// Code generated by gen-enums. DO NOT EDIT.

package enums

type AuditRetentionAction string

const (
	AuditRetentionActionArchive AuditRetentionAction = "archive"
	AuditRetentionActionDelete  AuditRetentionAction = "delete"
	AuditRetentionActionExport  AuditRetentionAction = "export"
)
