// Code generated by gen-enums. DO NOT EDIT.

package enums

type AuthResetDelivery string

const (
	AuthResetDeliveryEmail AuthResetDelivery = "email"
	AuthResetDeliverySms   AuthResetDelivery = "sms"
)

type AuthResetStatus string

const (
	AuthResetStatusIssued  AuthResetStatus = "issued"
	AuthResetStatusUsed    AuthResetStatus = "used"
	AuthResetStatusExpired AuthResetStatus = "expired"
	AuthResetStatusRevoked AuthResetStatus = "revoked"
)
