// Code generated by gen-enums. DO NOT EDIT.

package enums

type AuthIdentityProvider string

const (
	AuthIdentityProviderPassword AuthIdentityProvider = "password"
)

type AuthForgerRole string

const (
	AuthForgerRoleForger AuthForgerRole = "forger"
)

type AuthAuthorityRole string

const (
	AuthAuthorityRoleAuditor       AuthAuthorityRole = "auditor"
	AuthAuthorityRoleAdministrator AuthAuthorityRole = "administrator"
	AuthAuthorityRoleOwner         AuthAuthorityRole = "owner"
)

type AuthAccountStatus string

const (
	AuthAccountStatusActive    AuthAccountStatus = "active"
	AuthAccountStatusSuspended AuthAccountStatus = "suspended"
	AuthAccountStatusDeleted   AuthAccountStatus = "deleted"
)

type AuthSignupPlatform string

const (
	AuthSignupPlatformNfxidentity AuthSignupPlatform = "nfxidentity"
	AuthSignupPlatformNfxnews     AuthSignupPlatform = "nfxnews"
	AuthSignupPlatformNfxstorages AuthSignupPlatform = "nfxstorages"
	AuthSignupPlatformNfxedge     AuthSignupPlatform = "nfxedge"
)

type AuthProfileLanguage string

const (
	AuthProfileLanguageEn AuthProfileLanguage = "en"
	AuthProfileLanguageZh AuthProfileLanguage = "zh"
	AuthProfileLanguageFr AuthProfileLanguage = "fr"
)

type AuthProfileScope string

const (
	AuthProfileScopeCommunity AuthProfileScope = "community"
	AuthProfileScopeAuthority AuthProfileScope = "authority"
)
