// Code generated by gen-enums. DO NOT EDIT.

package enums

type AuthSessionRevokeReason string

const (
	AuthSessionRevokeReasonUserLogout         AuthSessionRevokeReason = "user_logout"
	AuthSessionRevokeReasonAdminRevoke        AuthSessionRevokeReason = "admin_revoke"
	AuthSessionRevokeReasonPasswordChanged    AuthSessionRevokeReason = "password_changed"
	AuthSessionRevokeReasonDeviceChanged      AuthSessionRevokeReason = "device_changed"
	AuthSessionRevokeReasonAccountLocked      AuthSessionRevokeReason = "account_locked"
	AuthSessionRevokeReasonSuspiciousActivity AuthSessionRevokeReason = "suspicious_activity"
	AuthSessionRevokeReasonSessionExpired     AuthSessionRevokeReason = "session_expired"
	AuthSessionRevokeReasonOther              AuthSessionRevokeReason = "other"
)
