// Code generated by gen-enums. DO NOT EDIT.

package enums

type AuthAuthorityRole string

const (
	AuthAuthorityRoleAuditor       AuthAuthorityRole = "auditor"
	AuthAuthorityRoleAdministrator AuthAuthorityRole = "administrator"
	AuthAuthorityRoleOwner         AuthAuthorityRole = "owner"
)
