// Code generated by gen-enums. DO NOT EDIT.

package enums

type AuthSignupPlatform string

const (
	AuthSignupPlatformNfxidentity AuthSignupPlatform = "nfxidentity"
	AuthSignupPlatformNfxnews     AuthSignupPlatform = "nfxnews"
	AuthSignupPlatformNfxstorages AuthSignupPlatform = "nfxstorages"
	AuthSignupPlatformNfxvault    AuthSignupPlatform = "nfxvault"
)
