// Code generated by gen-enums. DO NOT EDIT.

package enums

type AuthAccountStatus string

const (
	AuthAccountStatusActive    AuthAccountStatus = "active"
	AuthAccountStatusSuspended AuthAccountStatus = "suspended"
	AuthAccountStatusDeleted   AuthAccountStatus = "deleted"
)
