// Code generated by gen-enums. DO NOT EDIT.

package enums

type AuthLockReason string

const (
	AuthLockReasonTooManyAttempts    AuthLockReason = "too_many_attempts"
	AuthLockReasonAdminLock          AuthLockReason = "admin_lock"
	AuthLockReasonRiskDetected       AuthLockReason = "risk_detected"
	AuthLockReasonSuspiciousActivity AuthLockReason = "suspicious_activity"
	AuthLockReasonCompliance         AuthLockReason = "compliance"
	AuthLockReasonOther              AuthLockReason = "other"
)
