// Code generated by gen-enums. DO NOT EDIT.

package enums

type AuthFailureCode string

const (
	AuthFailureCodeBadPassword       AuthFailureCode = "bad_password"
	AuthFailureCodeUserNotFound      AuthFailureCode = "user_not_found"
	AuthFailureCodeLocked            AuthFailureCode = "locked"
	AuthFailureCodeMfaRequired       AuthFailureCode = "mfa_required"
	AuthFailureCodeMfaFailed         AuthFailureCode = "mfa_failed"
	AuthFailureCodeAccountDisabled   AuthFailureCode = "account_disabled"
	AuthFailureCodeCredentialExpired AuthFailureCode = "credential_expired"
	AuthFailureCodeRateLimited       AuthFailureCode = "rate_limited"
	AuthFailureCodeIpBlocked         AuthFailureCode = "ip_blocked"
	AuthFailureCodeDeviceNotTrusted  AuthFailureCode = "device_not_trusted"
	AuthFailureCodeOther             AuthFailureCode = "other"
)
