// Code generated by gen-enums. DO NOT EDIT.

package enums

type AuthMfaType string

const (
	AuthMfaTypeTotp       AuthMfaType = "totp"
	AuthMfaTypeSms        AuthMfaType = "sms"
	AuthMfaTypeEmail      AuthMfaType = "email"
	AuthMfaTypeWebauthn   AuthMfaType = "webauthn"
	AuthMfaTypeBackupCode AuthMfaType = "backup_code"
)
