// Code generated by gen-enums. DO NOT EDIT.

package enums

type AuthCredentialType string

const (
	AuthCredentialTypePassword  AuthCredentialType = "password"
	AuthCredentialTypePasskey   AuthCredentialType = "passkey"
	AuthCredentialTypeOauthLink AuthCredentialType = "oauth_link"
	AuthCredentialTypeSaml      AuthCredentialType = "saml"
	AuthCredentialTypeLdap      AuthCredentialType = "ldap"
)

type AuthCredentialStatus string

const (
	AuthCredentialStatusActive   AuthCredentialStatus = "active"
	AuthCredentialStatusDisabled AuthCredentialStatus = "disabled"
	AuthCredentialStatusExpired  AuthCredentialStatus = "expired"
)
