// Code generated by gen-enums. DO NOT EDIT.

package enums

type AuthIdentityProvider string

const (
	AuthIdentityProviderPassword AuthIdentityProvider = "password"
	AuthIdentityProviderGithub   AuthIdentityProvider = "github"
)
