// Code generated by gen-enums. DO NOT EDIT.

package enums

type AuthProfileLanguage string

const (
	AuthProfileLanguageEn AuthProfileLanguage = "en"
	AuthProfileLanguageZh AuthProfileLanguage = "zh"
	AuthProfileLanguageFr AuthProfileLanguage = "fr"
)

type AuthProfileScope string

const (
	AuthProfileScopeForger    AuthProfileScope = "forger"
	AuthProfileScopeAuthority AuthProfileScope = "authority"
)
