// Code generated by gen-enums. DO NOT EDIT.

package enums

type AuthRevokeReason string

const (
	AuthRevokeReasonUserLogout         AuthRevokeReason = "user_logout"
	AuthRevokeReasonAdminRevoke        AuthRevokeReason = "admin_revoke"
	AuthRevokeReasonPasswordChanged    AuthRevokeReason = "password_changed"
	AuthRevokeReasonRotation           AuthRevokeReason = "rotation"
	AuthRevokeReasonAccountLocked      AuthRevokeReason = "account_locked"
	AuthRevokeReasonDeviceChanged      AuthRevokeReason = "device_changed"
	AuthRevokeReasonSuspiciousActivity AuthRevokeReason = "suspicious_activity"
	AuthRevokeReasonOther              AuthRevokeReason = "other"
)
