// Code generated by gen-enums. DO NOT EDIT.

package enums

type ClientsAllowlistStatus string

const (
	ClientsAllowlistStatusActive   ClientsAllowlistStatus = "active"
	ClientsAllowlistStatusDisabled ClientsAllowlistStatus = "disabled"
	ClientsAllowlistStatusRevoked  ClientsAllowlistStatus = "revoked"
)
