// Code generated by gen-enums. DO NOT EDIT.

package enums

type ClientsRateLimitType string

const (
	ClientsRateLimitTypeRequestsPerSecond ClientsRateLimitType = "requests_per_second"
	ClientsRateLimitTypeRequestsPerMinute ClientsRateLimitType = "requests_per_minute"
	ClientsRateLimitTypeRequestsPerHour   ClientsRateLimitType = "requests_per_hour"
	ClientsRateLimitTypeRequestsPerDay    ClientsRateLimitType = "requests_per_day"
)
