// Code generated by gen-enums. DO NOT EDIT.

package enums

type ClientsCredentialStatus string

const (
	ClientsCredentialStatusActive   ClientsCredentialStatus = "active"
	ClientsCredentialStatusExpired  ClientsCredentialStatus = "expired"
	ClientsCredentialStatusRevoked  ClientsCredentialStatus = "revoked"
	ClientsCredentialStatusRotating ClientsCredentialStatus = "rotating"
)
