// Code generated by gen-enums. DO NOT EDIT.

package enums

type ClientsAppType string

const (
	ClientsAppTypeServer     ClientsAppType = "server"
	ClientsAppTypeService    ClientsAppType = "service"
	ClientsAppTypeInternal   ClientsAppType = "internal"
	ClientsAppTypePartner    ClientsAppType = "partner"
	ClientsAppTypeThirdParty ClientsAppType = "third_party"
)

type ClientsAppStatus string

const (
	ClientsAppStatusActive    ClientsAppStatus = "active"
	ClientsAppStatusDisabled  ClientsAppStatus = "disabled"
	ClientsAppStatusSuspended ClientsAppStatus = "suspended"
	ClientsAppStatusPending   ClientsAppStatus = "pending"
)
