// Code generated by gen-enums. DO NOT EDIT.

package enums

type ClientsEnvironment string

const (
	ClientsEnvironmentProduction  ClientsEnvironment = "production"
	ClientsEnvironmentStaging     ClientsEnvironment = "staging"
	ClientsEnvironmentDevelopment ClientsEnvironment = "development"
	ClientsEnvironmentTest        ClientsEnvironment = "test"
)
