// Code generated by gen-enums. DO NOT EDIT.

package enums

type ClientsApiKeyStatus string

const (
	ClientsApiKeyStatusActive  ClientsApiKeyStatus = "active"
	ClientsApiKeyStatusRevoked ClientsApiKeyStatus = "revoked"
	ClientsApiKeyStatusExpired ClientsApiKeyStatus = "expired"
)
