// Code generated by gen-enums. DO NOT EDIT.

package enums

type DirectoryUserStatus string

const (
	DirectoryUserStatusPending  DirectoryUserStatus = "pending"
	DirectoryUserStatusActive   DirectoryUserStatus = "active"
	DirectoryUserStatusDeactive DirectoryUserStatus = "deactive"
)
