// Code generated by gen-enums. DO NOT EDIT.

package enums

type PermissionCategory string

const (
	PermissionCategorySystem PermissionCategory = "system"
	PermissionCategoryUser   PermissionCategory = "user"
)
