// Code generated by gen-enums. DO NOT EDIT.

package enums

type TenantsMemberStatus string

const (
	TenantsMemberStatusInvited   TenantsMemberStatus = "INVITED"
	TenantsMemberStatusActive    TenantsMemberStatus = "ACTIVE"
	TenantsMemberStatusSuspended TenantsMemberStatus = "SUSPENDED"
	TenantsMemberStatusRemoved   TenantsMemberStatus = "REMOVED"
)

type TenantsMemberSource string

const (
	TenantsMemberSourceManual TenantsMemberSource = "MANUAL"
	TenantsMemberSourceInvite TenantsMemberSource = "INVITE"
	TenantsMemberSourceScim   TenantsMemberSource = "SCIM"
	TenantsMemberSourceSso    TenantsMemberSource = "SSO"
	TenantsMemberSourceHrSync TenantsMemberSource = "HR_SYNC"
	TenantsMemberSourceImport TenantsMemberSource = "IMPORT"
)
