// Code generated by gen-enums. DO NOT EDIT.

package enums

type TenantsGroupType string

const (
	TenantsGroupTypeDepartment TenantsGroupType = "department"
	TenantsGroupTypeTeam       TenantsGroupType = "team"
	TenantsGroupTypeGroup      TenantsGroupType = "group"
	TenantsGroupTypeOther      TenantsGroupType = "other"
)
