// Code generated by gen-enums. DO NOT EDIT.

package enums

type TenantsTenantStatus string

const (
	TenantsTenantStatusActive    TenantsTenantStatus = "ACTIVE"
	TenantsTenantStatusSuspended TenantsTenantStatus = "SUSPENDED"
	TenantsTenantStatusClosed    TenantsTenantStatus = "CLOSED"
	TenantsTenantStatusPending   TenantsTenantStatus = "PENDING"
)

type TenantsTenantAppStatus string

const (
	TenantsTenantAppStatusActive    TenantsTenantAppStatus = "ACTIVE"
	TenantsTenantAppStatusDisabled  TenantsTenantAppStatus = "DISABLED"
	TenantsTenantAppStatusSuspended TenantsTenantAppStatus = "SUSPENDED"
)
