// Code generated by gen-enums. DO NOT EDIT.

package enums

type TenantsTenantStatus string

const (
	TenantsTenantStatusActive    TenantsTenantStatus = "ACTIVE"
	TenantsTenantStatusSuspended TenantsTenantStatus = "SUSPENDED"
	TenantsTenantStatusClosed    TenantsTenantStatus = "CLOSED"
	TenantsTenantStatusPending   TenantsTenantStatus = "PENDING"
)

type TenantsTenantApplicationStatus string

const (
	TenantsTenantApplicationStatusActive    TenantsTenantApplicationStatus = "ACTIVE"
	TenantsTenantApplicationStatusDisabled  TenantsTenantApplicationStatus = "DISABLED"
	TenantsTenantApplicationStatusSuspended TenantsTenantApplicationStatus = "SUSPENDED"
)
