// Code generated by gen-enums. DO NOT EDIT.

package enums

type TenantsVerificationMethod string

const (
	TenantsVerificationMethodDns  TenantsVerificationMethod = "DNS"
	TenantsVerificationMethodTxt  TenantsVerificationMethod = "TXT"
	TenantsVerificationMethodHtml TenantsVerificationMethod = "HTML"
	TenantsVerificationMethodFile TenantsVerificationMethod = "FILE"
)

type TenantsVerificationStatus string

const (
	TenantsVerificationStatusPending  TenantsVerificationStatus = "PENDING"
	TenantsVerificationStatusVerified TenantsVerificationStatus = "VERIFIED"
	TenantsVerificationStatusFailed   TenantsVerificationStatus = "FAILED"
	TenantsVerificationStatusExpired  TenantsVerificationStatus = "EXPIRED"
)
