// Code generated by gen-enums. DO NOT EDIT.

package enums

type TenantsInvitationStatus string

const (
	TenantsInvitationStatusPending  TenantsInvitationStatus = "PENDING"
	TenantsInvitationStatusAccepted TenantsInvitationStatus = "ACCEPTED"
	TenantsInvitationStatusExpired  TenantsInvitationStatus = "EXPIRED"
	TenantsInvitationStatusRevoked  TenantsInvitationStatus = "REVOKED"
)
