// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type Permission struct {
	ID          uuid.UUID      `gorm:"type:uuid;primaryKey"`
	Tag         string         `gorm:"type:varchar(100);index:idx_permissions_tag;uniqueIndex:permissions_tag_key"`
	Name        string         `gorm:"type:varchar(255)"`
	Description *string        `gorm:"type:text"`
	Category    *string        `gorm:"type:varchar(50);index:idx_permissions_category"`
	IsSystem    bool           `gorm:"type:boolean"`
	CreatedAt   time.Time      `gorm:"autoCreateTime"`
	UpdatedAt   time.Time      `gorm:"autoUpdateTime"`
	DeletedAt   gorm.DeletedAt `gorm:"index"`
}

func (Permission) TableName() string { return "permission.permissions" }

func (m *Permission) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var PermissionCols = struct {
	ID, Tag, Name, Description, Category, IsSystem, CreatedAt,
	UpdatedAt, DeletedAt string
}{
	ID:          "id",
	Tag:         "tag",
	Name:        "name",
	Description: "description",
	Category:    "category",
	IsSystem:    "is_system",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
	DeletedAt:   "deleted_at",
}

const (
	PermissionPk       = "permissions_pkey"
	PermissionUkTagKey = "permissions_tag_key"
)
