// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type AuthorizationCode struct {
	ID        uuid.UUID      `gorm:"type:uuid;primaryKey"`
	Code      string         `gorm:"type:varchar(255);uniqueIndex:authorization_codes_code_key;index:idx_authorization_codes_code"`
	MaxUses   int            `gorm:"type:integer"`
	UsedCount int            `gorm:"type:integer"`
	CreatedBy *uuid.UUID     `gorm:"type:uuid;index:idx_authorization_codes_created_by"`
	ExpiresAt *time.Time     `gorm:"type:timestamp;index:idx_authorization_codes_expires_at"`
	IsActive  bool           `gorm:"type:boolean;index:idx_authorization_codes_is_active"`
	CreatedAt time.Time      `gorm:"autoCreateTime"`
	UpdatedAt time.Time      `gorm:"autoUpdateTime"`
	DeletedAt gorm.DeletedAt `gorm:"index"`
}

func (AuthorizationCode) TableName() string { return "permission.authorization_codes" }

func (m *AuthorizationCode) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var AuthorizationCodeCols = struct {
	ID, Code, MaxUses, UsedCount, CreatedBy, ExpiresAt, IsActive,
	CreatedAt, UpdatedAt, DeletedAt string
}{
	ID:        "id",
	Code:      "code",
	MaxUses:   "max_uses",
	UsedCount: "used_count",
	CreatedBy: "created_by",
	ExpiresAt: "expires_at",
	IsActive:  "is_active",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
}

const (
	AuthorizationCodePk        = "authorization_codes_pkey"
	AuthorizationCodeUkCodeKey = "authorization_codes_code_key"
)
