// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type UserPermission struct {
	ID           uuid.UUID      `gorm:"type:uuid;primaryKey"`
	UserID       uuid.UUID      `gorm:"type:uuid;index:idx_user_permissions_user_id;uniqueIndex:user_permissions_user_id_permission_id_key,priority:1"`
	PermissionID uuid.UUID      `gorm:"type:uuid;index:idx_user_permissions_permission_id;uniqueIndex:user_permissions_user_id_permission_id_key,priority:2"`
	CreatedAt    time.Time      `gorm:"autoCreateTime"`
	DeletedAt    gorm.DeletedAt `gorm:"index"`
}

func (UserPermission) TableName() string { return "permission.user_permissions" }

func (m *UserPermission) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var UserPermissionCols = struct {
	ID, UserID, PermissionID, CreatedAt, DeletedAt string
}{
	ID:           "id",
	UserID:       "user_id",
	PermissionID: "permission_id",
	CreatedAt:    "created_at",
	DeletedAt:    "deleted_at",
}

const (
	UserPermissionPk                      = "user_permissions_pkey"
	UserPermissionUkUserIdPermissionIdKey = "user_permissions_user_id_permission_id_key"
	UserPermissionFkPermissionIdFkey      = "user_permissions_permission_id_fkey"
)
