// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type ImageTag struct {
	ID         uuid.UUID `gorm:"type:uuid;primaryKey"`
	ImageID    uuid.UUID `gorm:"type:uuid;index:idx_image_tags_image_id;uniqueIndex:image_tags_image_id_tag_key,priority:1"`
	Tag        string    `gorm:"type:text;index:idx_image_tags_tag;index:idx_image_tags_tag_confidence,priority:1;uniqueIndex:image_tags_image_id_tag_key,priority:2"`
	Confidence *float64  `gorm:"type:double precision;index:idx_image_tags_confidence;index:idx_image_tags_tag_confidence,priority:2"`
	CreatedAt  time.Time `gorm:"autoCreateTime"`
}

func (ImageTag) TableName() string { return "image.image_tags" }

func (m *ImageTag) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var ImageTagCols = struct {
	ID, ImageID, Tag, Confidence, CreatedAt string
}{
	ID:         "id",
	ImageID:    "image_id",
	Tag:        "tag",
	Confidence: "confidence",
	CreatedAt:  "created_at",
}

const (
	ImageTagPk              = "image_tags_pkey"
	ImageTagUkImageIdTagKey = "image_tags_image_id_tag_key"
	ImageTagFkImageIdFkey   = "image_tags_image_id_fkey"
)
