// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type ImageType struct {
	ID          uuid.UUID `gorm:"type:uuid;primaryKey"`
	Key         string    `gorm:"type:text;index:idx_image_types_key;uniqueIndex:image_types_key_key"`
	Description *string   `gorm:"type:text"`
	MaxWidth    *int      `gorm:"type:integer"`
	MaxHeight   *int      `gorm:"type:integer"`
	AspectRatio *string   `gorm:"type:text"`
	IsSystem    *bool     `gorm:"type:boolean;index:idx_image_types_is_system"`
	CreatedAt   time.Time `gorm:"autoCreateTime"`
	UpdatedAt   time.Time `gorm:"autoUpdateTime"`
}

func (ImageType) TableName() string { return "image.image_types" }

func (m *ImageType) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var ImageTypeCols = struct {
	ID, Key, Description, MaxWidth, MaxHeight, AspectRatio, IsSystem,
	CreatedAt, UpdatedAt string
}{
	ID:          "id",
	Key:         "key",
	Description: "description",
	MaxWidth:    "max_width",
	MaxHeight:   "max_height",
	AspectRatio: "aspect_ratio",
	IsSystem:    "is_system",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}

const (
	ImageTypePk       = "image_types_pkey"
	ImageTypeUkKeyKey = "image_types_key_key"
)
