// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

type Image struct {
	ID               uuid.UUID       `gorm:"type:uuid;primaryKey"`
	TypeID           *uuid.UUID      `gorm:"type:uuid;index:idx_images_type_id;index:idx_images_type_public,priority:1"`
	UserID           *uuid.UUID      `gorm:"type:uuid;index:idx_images_tenant_user,priority:2;index:idx_images_user_id;index:idx_images_user_public,priority:1"`
	TenantID         *uuid.UUID      `gorm:"type:uuid;index:idx_images_tenant_application,priority:1;index:idx_images_tenant_id;index:idx_images_tenant_user,priority:1"`
	ApplicationID    *uuid.UUID      `gorm:"type:uuid;index:idx_images_application_id;index:idx_images_tenant_application,priority:2"`
	SourceDomain     *string         `gorm:"type:text;index:idx_images_source_domain"`
	Filename         string          `gorm:"type:text;index:idx_images_filename"`
	OriginalFilename string          `gorm:"type:text"`
	MimeType         string          `gorm:"type:text;index:idx_images_mime_type"`
	Size             int64           `gorm:"type:bigint"`
	Width            *int            `gorm:"type:integer"`
	Height           *int            `gorm:"type:integer"`
	StoragePath      string          `gorm:"type:text"`
	URL              *string         `gorm:"type:text"`
	IsPublic         bool            `gorm:"type:boolean;index:idx_images_is_public;index:idx_images_type_public,priority:2;index:idx_images_user_public,priority:2"`
	Metadata         *datatypes.JSON `gorm:"type:jsonb"`
	CreatedAt        time.Time       `gorm:"autoCreateTime"`
	UpdatedAt        time.Time       `gorm:"autoUpdateTime"`
	DeletedAt        gorm.DeletedAt  `gorm:"index"`
}

func (Image) TableName() string { return "image.images" }

func (m *Image) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var ImageCols = struct {
	ID, TypeID, UserID, TenantID, ApplicationID, SourceDomain, Filename,
	OriginalFilename, MimeType, Size, Width, Height, StoragePath, URL,
	IsPublic, Metadata, CreatedAt, UpdatedAt, DeletedAt string
}{
	ID:               "id",
	TypeID:           "type_id",
	UserID:           "user_id",
	TenantID:         "tenant_id",
	ApplicationID:    "application_id",
	SourceDomain:     "source_domain",
	Filename:         "filename",
	OriginalFilename: "original_filename",
	MimeType:         "mime_type",
	Size:             "size",
	Width:            "width",
	Height:           "height",
	StoragePath:      "storage_path",
	URL:              "url",
	IsPublic:         "is_public",
	Metadata:         "metadata",
	CreatedAt:        "created_at",
	UpdatedAt:        "updated_at",
	DeletedAt:        "deleted_at",
}

const (
	ImagePk           = "images_pkey"
	ImageFkTypeIdFkey = "images_type_id_fkey"
)
