// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type ImageVariant struct {
	ID          uuid.UUID `gorm:"type:uuid;primaryKey"`
	ImageID     uuid.UUID `gorm:"type:uuid;index:idx_image_variants_image_id;uniqueIndex:image_variants_image_id_variant_key_key,priority:1"`
	VariantKey  string    `gorm:"type:text;index:idx_image_variants_variant_key;uniqueIndex:image_variants_image_id_variant_key_key,priority:2"`
	Width       *int      `gorm:"type:integer"`
	Height      *int      `gorm:"type:integer"`
	Size        *int64    `gorm:"type:bigint"`
	MimeType    *string   `gorm:"type:text"`
	StoragePath string    `gorm:"type:text"`
	URL         *string   `gorm:"type:text;index:idx_image_variants_url"`
	CreatedAt   time.Time `gorm:"autoCreateTime"`
	UpdatedAt   time.Time `gorm:"autoUpdateTime"`
}

func (ImageVariant) TableName() string { return "image.image_variants" }

func (m *ImageVariant) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var ImageVariantCols = struct {
	ID, ImageID, VariantKey, Width, Height, Size, MimeType,
	StoragePath, URL, CreatedAt, UpdatedAt string
}{
	ID:          "id",
	ImageID:     "image_id",
	VariantKey:  "variant_key",
	Width:       "width",
	Height:      "height",
	Size:        "size",
	MimeType:    "mime_type",
	StoragePath: "storage_path",
	URL:         "url",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}

const (
	ImageVariantPk                     = "image_variants_pkey"
	ImageVariantUkImageIdVariantKeyKey = "image_variants_image_id_variant_key_key"
	ImageVariantFkImageIdFkey          = "image_variants_image_id_fkey"
)
