# https://taskfile.dev

version: "3"

dotenv:
  - ".env"

vars:
  PROTO_SRC_DIR: protos
  PROTO_OUT_DIR: protos/gen
  GO_VERSION: "1.24.3"
  POSTGRES_HOST: "192.168.1.64"
  POSTGRES_PORT: "10105"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "Lucas127."
  POSTGRES_DB_DEV: "nfxid_dev"
  POSTGRES_DB_PROD: "nfxid"
  POSTGRES_DB_SHADOW: "nfxid_diff"
  POSTGRES_CONTAINER_NAME: "NFX-Stack-PostgreSQL"
  ATLAS_ENV: "{{default \"dev\" .ATLAS_ENV}}"
  ATLAS_CONFIG_PATH: "file://databases/atlas.hcl"
  ATLAS_MIGRATIONS_DIR_DEV: "file://databases/migrations/development"
  ATLAS_MIGRATIONS_DIR_PROD: "file://databases/migrations/production"
  ATLAS_MIGRATIONS_DIR: "{{if eq .ATLAS_ENV \"prod\"}}{{.ATLAS_MIGRATIONS_DIR_PROD}}{{else}}{{.ATLAS_MIGRATIONS_DIR_DEV}}{{end}}"
  # Resources docker-compose.yml path (relative to Identity-Backend directory)
  RESOURCES_DOCKER_COMPOSE: "../Resources/docker-compose.yml"

tasks:
  install:
    desc: "Install required Go dev tools"
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install github.com/air-verse/air@latest
      - go install golang.org/x/tools/cmd/goimports@latest
      - go install github.com/segmentio/golines@latest
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - go install github.com/bufbuild/buf/cmd/buf@v1.49.0
      - go install golang.org/x/tools/cmd/goimports@latest
    silent: false

  proto:update:
    desc: "Download buf dependencies"
    dir: "{{.PROTO_SRC_DIR}}"
    cmds:
      - buf dep update

  proto:gen:
    desc: "Generate gRPC & Protobuf code using buf"
    deps: [proto:update]
    dir: "{{.PROTO_SRC_DIR}}"
    cmds:
      - buf generate
    sources:
      - "{{.PROTO_SRC_DIR}}/**/*.proto"
    generates:
      - "{{.PROTO_OUT_DIR}}/**/*.pb.go"

  lint:
    desc: "Run golangci-lint"
    cmds:
      - golangci-lint run --timeout=5m

  fmt:
    desc: "Format Go code"
    cmds:
      - golines -m 120 -w .
    silent: true

  ci:
    desc: "Run all CI tasks (format, lint)"
    cmds:
      - task: fmt
      - task: lint

  atlas:gen-models:
    desc: "Generate Go models from the database schema"
    cmds:
      - |
        POSTGRES_USER="{{.POSTGRES_USER}}" \
        POSTGRES_PASSWORD="{{.POSTGRES_PASSWORD}}" \
        POSTGRES_HOST="{{.POSTGRES_HOST}}" \
        POSTGRES_PORT="{{.POSTGRES_PORT}}" \
        POSTGRES_DB_DEV="{{.POSTGRES_DB_DEV}}" \
        POSTGRES_DB_PROD="{{.POSTGRES_DB_PROD}}" \
        POSTGRES_DB_SHADOW="{{.POSTGRES_DB_SHADOW}}" \
        POSTGRES_CONTAINER_NAME="{{.POSTGRES_CONTAINER_NAME}}" \
        RESOURCES_DOCKER_COMPOSE="{{.RESOURCES_DOCKER_COMPOSE}}" \
        ATLAS_ENV="{{.ATLAS_ENV}}" \
        bash databases/scripts/gen_models.sh
    silent: false

  atlas:gen-views:
    desc: "Generate Go views from the database schema"
    cmds:
      - |
        POSTGRES_USER="{{.POSTGRES_USER}}" \
        POSTGRES_PASSWORD="{{.POSTGRES_PASSWORD}}" \
        POSTGRES_HOST="{{.POSTGRES_HOST}}" \
        POSTGRES_PORT="{{.POSTGRES_PORT}}" \
        POSTGRES_DB_DEV="{{.POSTGRES_DB_DEV}}" \
        POSTGRES_DB_PROD="{{.POSTGRES_DB_PROD}}" \
        POSTGRES_DB_SHADOW="{{.POSTGRES_DB_SHADOW}}" \
        POSTGRES_CONTAINER_NAME="{{.POSTGRES_CONTAINER_NAME}}" \
        RESOURCES_DOCKER_COMPOSE="{{.RESOURCES_DOCKER_COMPOSE}}" \
        ATLAS_ENV="{{.ATLAS_ENV}}" \
        bash databases/scripts/gen_views.sh
    silent: false

  atlas:gen-enums:
    desc: "Generate Go enums from the database schema"
    cmds:
      - |
        POSTGRES_USER="{{.POSTGRES_USER}}" \
        POSTGRES_PASSWORD="{{.POSTGRES_PASSWORD}}" \
        POSTGRES_HOST="{{.POSTGRES_HOST}}" \
        POSTGRES_PORT="{{.POSTGRES_PORT}}" \
        POSTGRES_DB_DEV="{{.POSTGRES_DB_DEV}}" \
        POSTGRES_DB_PROD="{{.POSTGRES_DB_PROD}}" \
        POSTGRES_DB_SHADOW="{{.POSTGRES_DB_SHADOW}}" \
        POSTGRES_CONTAINER_NAME="{{.POSTGRES_CONTAINER_NAME}}" \
        ATLAS_ENV="{{.ATLAS_ENV}}" \
        bash databases/scripts/gen_enums.sh
    silent: false

  atlas:gen:
    desc: "Generate Go models, enums and views from the database schema"
    cmds:
      - task: atlas:gen-enums
      - task: atlas:gen-models
      - task: atlas:gen-views
    silent: false

  atlas:pipeline:run:ps:
    desc: "Run Atlas pipeline using PowerShell (interactive environment selection)"
    dir: .
    env:
      POSTGRES_USER: "{{.POSTGRES_USER}}"
      POSTGRES_PASSWORD: "{{.POSTGRES_PASSWORD}}"
      POSTGRES_HOST: "{{.POSTGRES_HOST}}"
      POSTGRES_PORT: "{{.POSTGRES_PORT}}"
      POSTGRES_DB_DEV: "{{.POSTGRES_DB_DEV}}"
      POSTGRES_DB_PROD: "{{.POSTGRES_DB_PROD}}"
      POSTGRES_DB_SHADOW: "{{.POSTGRES_DB_SHADOW}}"
      POSTGRES_CONTAINER_NAME: "{{.POSTGRES_CONTAINER_NAME}}"
      RESOURCES_DOCKER_COMPOSE: "{{.RESOURCES_DOCKER_COMPOSE}}"
      ATLAS_CONFIG_PATH: "{{.ATLAS_CONFIG_PATH}}"
    cmds:
      - powershell -ExecutionPolicy Bypass -File run_atlas_pipeline.ps1

  atlas:pipeline:run:sh:
    desc: "Run Atlas pipeline using bash (interactive environment selection)"
    env:
      POSTGRES_USER: "{{.POSTGRES_USER}}"
      POSTGRES_PASSWORD: "{{.POSTGRES_PASSWORD}}"
      POSTGRES_HOST: "{{.POSTGRES_HOST}}"
      POSTGRES_PORT: "{{.POSTGRES_PORT}}"
      POSTGRES_DB_DEV: "{{.POSTGRES_DB_DEV}}"
      POSTGRES_DB_PROD: "{{.POSTGRES_DB_PROD}}"
      POSTGRES_DB_SHADOW: "{{.POSTGRES_DB_SHADOW}}"
      POSTGRES_CONTAINER_NAME: "{{.POSTGRES_CONTAINER_NAME}}"
      RESOURCES_DOCKER_COMPOSE: "{{.RESOURCES_DOCKER_COMPOSE}}"
      ATLAS_CONFIG_PATH: "{{.ATLAS_CONFIG_PATH}}"
    cmds:
      - bash run_atlas_pipeline.sh

  atlas:push:
    desc: "Push migrations to Atlas Cloud"
    dir: atlas
    cmds:
      - |
        source /volume1/use-menv.sh && \
        atlas migrate push \
          --env {{.ATLAS_ENV}} \
          --dev-url "postgres://{{.POSTGRES_USER}}:{{.POSTGRES_PASSWORD}}@{{.POSTGRES_HOST}}:{{.POSTGRES_PORT}}/{{.POSTGRES_DB_SHADOW}}?sslmode=disable" \
          nfx-identity
    silent: false

  clean:
    desc: "Clean build artifacts"
    cmds:
      - rm -rf bin/

  console:
    desc: "Run console dev server"
    dir: console
    cmds:
      - npm run dev

  console:i:
    desc: "Install console dependencies"
    dir: console
    cmds:
      - npm install
  
  go:ub:
    desc: "Up go dev server and build"
    cmds:
      - sudo docker compose -f docker-compose.dev.yml up --build

  go:up:
    desc: "Up go dev server"
    cmds:
      - sudo docker compose -f docker-compose.dev.yml up
