// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type Badge struct {
	ID          uuid.UUID      `gorm:"type:uuid;primaryKey"`
	Name        string         `gorm:"type:varchar(50);uniqueIndex:badges_name_key;index:idx_badges_name"`
	Description *string        `gorm:"type:text"`
	IconURL     *string        `gorm:"type:varchar(255)"`
	Color       *string        `gorm:"type:varchar(20)"`
	Category    *string        `gorm:"type:varchar(50);index:idx_badges_category"`
	IsSystem    bool           `gorm:"type:boolean"`
	CreatedAt   time.Time      `gorm:"autoCreateTime"`
	UpdatedAt   time.Time      `gorm:"autoUpdateTime"`
	DeletedAt   gorm.DeletedAt `gorm:"index"`
}

func (Badge) TableName() string { return "auth.badges" }

func (m *Badge) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var BadgeCols = struct {
	ID, Name, Description, IconURL, Color, Category, IsSystem,
	CreatedAt, UpdatedAt, DeletedAt string
}{
	ID:          "id",
	Name:        "name",
	Description: "description",
	IconURL:     "icon_url",
	Color:       "color",
	Category:    "category",
	IsSystem:    "is_system",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
	DeletedAt:   "deleted_at",
}

const (
	BadgePk        = "badges_pkey"
	BadgeUkNameKey = "badges_name_key"
)
