// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type ProfileBadge struct {
	ID          uuid.UUID `gorm:"type:uuid;primaryKey"`
	ProfileID   uuid.UUID `gorm:"type:uuid;index:idx_profile_badges_profile_id;uniqueIndex:profile_badges_profile_id_badge_id_key,priority:1"`
	BadgeID     uuid.UUID `gorm:"type:uuid;index:idx_profile_badges_badge_id;uniqueIndex:profile_badges_profile_id_badge_id_key,priority:2"`
	Description *string   `gorm:"type:text"`
	Level       *int      `gorm:"type:integer"`
	EarnedAt    time.Time `gorm:"type:timestamp;index:idx_profile_badges_earned_at"`
	CreatedAt   time.Time `gorm:"autoCreateTime"`
	UpdatedAt   time.Time `gorm:"autoUpdateTime"`
}

func (ProfileBadge) TableName() string { return "auth.profile_badges" }

func (m *ProfileBadge) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var ProfileBadgeCols = struct {
	ID, ProfileID, BadgeID, Description, Level, EarnedAt, CreatedAt,
	UpdatedAt string
}{
	ID:          "id",
	ProfileID:   "profile_id",
	BadgeID:     "badge_id",
	Description: "description",
	Level:       "level",
	EarnedAt:    "earned_at",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}

const (
	ProfileBadgePk                    = "profile_badges_pkey"
	ProfileBadgeUkProfileIdBadgeIdKey = "profile_badges_profile_id_badge_id_key"
	ProfileBadgeFkBadgeIdFkey         = "profile_badges_badge_id_fkey"
	ProfileBadgeFkProfileIdFkey       = "profile_badges_profile_id_fkey"
)
