// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

type Profile struct {
	ID              uuid.UUID       `gorm:"type:uuid;primaryKey"`
	UserID          uuid.UUID       `gorm:"type:uuid;index:idx_profiles_user_id;uniqueIndex:profiles_user_id_key"`
	FirstName       *string         `gorm:"type:varchar(100);index:idx_profiles_first_and_last_name,priority:1"`
	LastName        *string         `gorm:"type:varchar(100);index:idx_profiles_first_and_last_name,priority:2"`
	Nickname        *string         `gorm:"type:varchar(50);index:idx_profiles_nickname;uniqueIndex:profiles_nickname_key"`
	DisplayName     *string         `gorm:"type:varchar(100);index:idx_profiles_display_name"`
	AvatarID        *uuid.UUID      `gorm:"type:uuid;index:idx_profiles_avatar_id"`
	BackgroundID    *uuid.UUID      `gorm:"type:uuid;index:idx_profiles_background_id"`
	BackgroundIds   *string         `gorm:"type:uuid[]"`
	Bio             *string         `gorm:"type:text"`
	Phone           *string         `gorm:"type:varchar(20);index:idx_profiles_phone"`
	Birthday        *time.Time      `gorm:"type:date;index:idx_profiles_birthday"`
	Age             *int            `gorm:"type:integer"`
	Gender          *string         `gorm:"type:varchar(20);index:idx_profiles_gender"`
	Location        *string         `gorm:"type:varchar(255);index:idx_profiles_location"`
	Website         *string         `gorm:"type:varchar(255);index:idx_profiles_website"`
	Github          *string         `gorm:"type:varchar(255);index:idx_profiles_github"`
	SocialLinks     *datatypes.JSON `gorm:"type:jsonb"`
	Preferences     *datatypes.JSON `gorm:"type:jsonb"`
	Skills          *datatypes.JSON `gorm:"type:jsonb"`
	PrivacySettings *datatypes.JSON `gorm:"type:jsonb"`
	CreatedAt       time.Time       `gorm:"autoCreateTime"`
	UpdatedAt       time.Time       `gorm:"autoUpdateTime"`
	DeletedAt       gorm.DeletedAt  `gorm:"index"`
}

func (Profile) TableName() string { return "auth.profiles" }

func (m *Profile) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var ProfileCols = struct {
	ID, UserID, FirstName, LastName, Nickname, DisplayName, AvatarID,
	BackgroundID, BackgroundIds, Bio, Phone, Birthday, Age, Gender,
	Location, Website, Github, SocialLinks, Preferences, Skills, PrivacySettings,
	CreatedAt, UpdatedAt, DeletedAt string
}{
	ID:              "id",
	UserID:          "user_id",
	FirstName:       "first_name",
	LastName:        "last_name",
	Nickname:        "nickname",
	DisplayName:     "display_name",
	AvatarID:        "avatar_id",
	BackgroundID:    "background_id",
	BackgroundIds:   "background_ids",
	Bio:             "bio",
	Phone:           "phone",
	Birthday:        "birthday",
	Age:             "age",
	Gender:          "gender",
	Location:        "location",
	Website:         "website",
	Github:          "github",
	SocialLinks:     "social_links",
	Preferences:     "preferences",
	Skills:          "skills",
	PrivacySettings: "privacy_settings",
	CreatedAt:       "created_at",
	UpdatedAt:       "updated_at",
	DeletedAt:       "deleted_at",
}

const (
	ProfilePk            = "profiles_pkey"
	ProfileUkNicknameKey = "profiles_nickname_key"
	ProfileUkUserIdKey   = "profiles_user_id_key"
	ProfileFkUserIdFkey  = "profiles_user_id_fkey"
)
