// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

type Role struct {
	ID          uuid.UUID       `gorm:"type:uuid;primaryKey"`
	Name        string          `gorm:"type:varchar(50);index:idx_roles_name;uniqueIndex:roles_name_key"`
	Description *string         `gorm:"type:text"`
	Permissions *datatypes.JSON `gorm:"type:jsonb"`
	IsSystem    bool            `gorm:"type:boolean"`
	CreatedAt   time.Time       `gorm:"autoCreateTime"`
	UpdatedAt   time.Time       `gorm:"autoUpdateTime"`
	DeletedAt   gorm.DeletedAt  `gorm:"index"`
}

func (Role) TableName() string { return "auth.roles" }

func (m *Role) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var RoleCols = struct {
	ID, Name, Description, Permissions, IsSystem, CreatedAt, UpdatedAt,
	DeletedAt string
}{
	ID:          "id",
	Name:        "name",
	Description: "description",
	Permissions: "permissions",
	IsSystem:    "is_system",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
	DeletedAt:   "deleted_at",
}

const (
	RolePk        = "roles_pkey"
	RoleUkNameKey = "roles_name_key"
)
