import { EventEmitter, defineEvents, type EventNamesOf } from "nfx-ui/events";
import { singleton } from "nfx-ui/utils";

export const accessEvents = defineEvents({
  INVALIDATE_ROLE: "ACCESS:INVALIDATE_ROLE",
  INVALIDATE_ROLES: "ACCESS:INVALIDATE_ROLES",
  INVALIDATE_PERMISSION: "ACCESS:INVALIDATE_PERMISSION",
  INVALIDATE_PERMISSIONS: "ACCESS:INVALIDATE_PERMISSIONS",
  INVALIDATE_SCOPE: "ACCESS:INVALIDATE_SCOPE",
  INVALIDATE_SCOPES: "ACCESS:INVALIDATE_SCOPES",
  INVALIDATE_GRANT: "ACCESS:INVALIDATE_GRANT",
  INVALIDATE_GRANTS: "ACCESS:INVALIDATE_GRANTS",
  INVALIDATE_ROLE_PERMISSION: "ACCESS:INVALIDATE_ROLE_PERMISSION",
  INVALIDATE_ROLE_PERMISSIONS: "ACCESS:INVALIDATE_ROLE_PERMISSIONS",
  INVALIDATE_SCOPE_PERMISSION: "ACCESS:INVALIDATE_SCOPE_PERMISSION",
  INVALIDATE_SCOPE_PERMISSIONS: "ACCESS:INVALIDATE_SCOPE_PERMISSIONS",
  INVALIDATE_ACTION: "ACCESS:INVALIDATE_ACTION",
  INVALIDATE_ACTIONS: "ACCESS:INVALIDATE_ACTIONS",
  INVALIDATE_ACTION_REQUIREMENT: "ACCESS:INVALIDATE_ACTION_REQUIREMENT",
  INVALIDATE_ACTION_REQUIREMENTS: "ACCESS:INVALIDATE_ACTION_REQUIREMENTS",
});

type AccessEvent = EventNamesOf<typeof accessEvents>;

class AccessEventEmitter extends EventEmitter<AccessEvent> {
  constructor() {
    super(accessEvents);
  }
}

export const accessEventEmitter = new (singleton(AccessEventEmitter))();
