import { EventEmitter, defineEvents, type EventNamesOf } from "nfx-ui/events";
import { singleton } from "nfx-ui/utils";

export const auditEvents = defineEvents({
  INVALIDATE_EVENT: "AUDIT:INVALIDATE_EVENT",
  INVALIDATE_EVENTS: "AUDIT:INVALIDATE_EVENTS",
  INVALIDATE_ACTOR_SNAPSHOT: "AUDIT:INVALIDATE_ACTOR_SNAPSHOT",
  INVALIDATE_ACTOR_SNAPSHOTS: "AUDIT:INVALIDATE_ACTOR_SNAPSHOTS",
  INVALIDATE_EVENT_RETENTION_POLICY: "AUDIT:INVALIDATE_EVENT_RETENTION_POLICY",
  INVALIDATE_EVENT_RETENTION_POLICIES: "AUDIT:INVALIDATE_EVENT_RETENTION_POLICIES",
  INVALIDATE_EVENT_SEARCH_INDEX: "AUDIT:INVALIDATE_EVENT_SEARCH_INDEX",
  INVALIDATE_EVENT_SEARCH_INDICES: "AUDIT:INVALIDATE_EVENT_SEARCH_INDICES",
  INVALIDATE_HASH_CHAIN_CHECKPOINT: "AUDIT:INVALIDATE_HASH_CHAIN_CHECKPOINT",
  INVALIDATE_HASH_CHAIN_CHECKPOINTS: "AUDIT:INVALIDATE_HASH_CHAIN_CHECKPOINTS",
});

type AuditEvent = EventNamesOf<typeof auditEvents>;

class AuditEventEmitter extends EventEmitter<AuditEvent> {
  constructor() {
    super(auditEvents);
  }
}

export const auditEventEmitter = new (singleton(AuditEventEmitter))();
