import { EventEmitter, defineEvents, type EventNamesOf } from "nfx-ui/events";
import { singleton } from "nfx-ui/utils";

export const authEvents = defineEvents({
  INVALIDATE_SESSION: "AUTH:INVALIDATE_SESSION",
  INVALIDATE_SESSIONS: "AUTH:INVALIDATE_SESSIONS",
  INVALIDATE_USER_CREDENTIAL: "AUTH:INVALIDATE_USER_CREDENTIAL",
  INVALIDATE_USER_CREDENTIALS: "AUTH:INVALIDATE_USER_CREDENTIALS",
  INVALIDATE_MFA_FACTOR: "AUTH:INVALIDATE_MFA_FACTOR",
  INVALIDATE_MFA_FACTORS: "AUTH:INVALIDATE_MFA_FACTORS",
  INVALIDATE_REFRESH_TOKEN: "AUTH:INVALIDATE_REFRESH_TOKEN",
  INVALIDATE_REFRESH_TOKENS: "AUTH:INVALIDATE_REFRESH_TOKENS",
  INVALIDATE_PASSWORD_RESET: "AUTH:INVALIDATE_PASSWORD_RESET",
  INVALIDATE_PASSWORD_RESETS: "AUTH:INVALIDATE_PASSWORD_RESETS",
  INVALIDATE_PASSWORD_HISTORY: "AUTH:INVALIDATE_PASSWORD_HISTORY",
  INVALIDATE_PASSWORD_HISTORIES: "AUTH:INVALIDATE_PASSWORD_HISTORIES",
  INVALIDATE_LOGIN_ATTEMPT: "AUTH:INVALIDATE_LOGIN_ATTEMPT",
  INVALIDATE_LOGIN_ATTEMPTS: "AUTH:INVALIDATE_LOGIN_ATTEMPTS",
  INVALIDATE_ACCOUNT_LOCKOUT: "AUTH:INVALIDATE_ACCOUNT_LOCKOUT",
  INVALIDATE_ACCOUNT_LOCKOUTS: "AUTH:INVALIDATE_ACCOUNT_LOCKOUTS",
  INVALIDATE_TRUSTED_DEVICE: "AUTH:INVALIDATE_TRUSTED_DEVICE",
  INVALIDATE_TRUSTED_DEVICES: "AUTH:INVALIDATE_TRUSTED_DEVICES",
  LOGIN_SUCCESS: "AUTH:LOGIN_SUCCESS",
  LOGOUT: "AUTH:LOGOUT",
});

type AuthEvent = EventNamesOf<typeof authEvents>;

class AuthEventEmitter extends EventEmitter<AuthEvent> {
  constructor() {
    super(authEvents);
  }
}

export const authEventEmitter = new (singleton(AuthEventEmitter))();
