import { EventEmitter, defineEvents, type EventNamesOf } from "nfx-ui/events";
import { singleton } from "nfx-ui/utils";

export const clientsEvents = defineEvents({
  INVALIDATE_APP: "CLIENTS:INVALIDATE_APP",
  INVALIDATE_APPS: "CLIENTS:INVALIDATE_APPS",
  INVALIDATE_API_KEY: "CLIENTS:INVALIDATE_API_KEY",
  INVALIDATE_API_KEYS: "CLIENTS:INVALIDATE_API_KEYS",
  INVALIDATE_CLIENT_CREDENTIAL: "CLIENTS:INVALIDATE_CLIENT_CREDENTIAL",
  INVALIDATE_CLIENT_CREDENTIALS: "CLIENTS:INVALIDATE_CLIENT_CREDENTIALS",
  INVALIDATE_CLIENT_SCOPE: "CLIENTS:INVALIDATE_CLIENT_SCOPE",
  INVALIDATE_CLIENT_SCOPES: "CLIENTS:INVALIDATE_CLIENT_SCOPES",
  INVALIDATE_IP_ALLOWLIST: "CLIENTS:INVALIDATE_IP_ALLOWLIST",
  INVALIDATE_IP_ALLOWLISTS: "CLIENTS:INVALIDATE_IP_ALLOWLISTS",
  INVALIDATE_RATE_LIMIT: "CLIENTS:INVALIDATE_RATE_LIMIT",
  INVALIDATE_RATE_LIMITS: "CLIENTS:INVALIDATE_RATE_LIMITS",
});

type ClientsEvent = EventNamesOf<typeof clientsEvents>;

class ClientsEventEmitter extends EventEmitter<ClientsEvent> {
  constructor() {
    super(clientsEvents);
  }
}

export const clientsEventEmitter = new (singleton(ClientsEventEmitter))();
