import { EventEmitter, defineEvents, type EventNamesOf } from "nfx-ui/events";
import { singleton } from "nfx-ui/utils";

export const directoryEvents = defineEvents({
  INVALIDATE_USER: "DIRECTORY:INVALIDATE_USER",
  INVALIDATE_USERS: "DIRECTORY:INVALIDATE_USERS",
  INVALIDATE_BADGE: "DIRECTORY:INVALIDATE_BADGE",
  INVALIDATE_BADGES: "DIRECTORY:INVALIDATE_BADGES",
  INVALIDATE_USER_BADGE: "DIRECTORY:INVALIDATE_USER_BADGE",
  INVALIDATE_USER_BADGES: "DIRECTORY:INVALIDATE_USER_BADGES",
  INVALIDATE_USER_EDUCATION: "DIRECTORY:INVALIDATE_USER_EDUCATION",
  INVALIDATE_USER_EDUCATIONS: "DIRECTORY:INVALIDATE_USER_EDUCATIONS",
  INVALIDATE_USER_EMAIL: "DIRECTORY:INVALIDATE_USER_EMAIL",
  INVALIDATE_USER_EMAILS: "DIRECTORY:INVALIDATE_USER_EMAILS",
  INVALIDATE_USER_OCCUPATION: "DIRECTORY:INVALIDATE_USER_OCCUPATION",
  INVALIDATE_USER_OCCUPATIONS: "DIRECTORY:INVALIDATE_USER_OCCUPATIONS",
  INVALIDATE_USER_PHONE: "DIRECTORY:INVALIDATE_USER_PHONE",
  INVALIDATE_USER_PHONES: "DIRECTORY:INVALIDATE_USER_PHONES",
  INVALIDATE_USER_PREFERENCE: "DIRECTORY:INVALIDATE_USER_PREFERENCE",
  INVALIDATE_USER_PREFERENCES: "DIRECTORY:INVALIDATE_USER_PREFERENCES",
  INVALIDATE_USER_PROFILE: "DIRECTORY:INVALIDATE_USER_PROFILE",
  INVALIDATE_USER_PROFILES: "DIRECTORY:INVALIDATE_USER_PROFILES",
  INVALIDATE_USER_AVATAR: "DIRECTORY:INVALIDATE_USER_AVATAR",
  INVALIDATE_USER_AVATARS: "DIRECTORY:INVALIDATE_USER_AVATARS",
  INVALIDATE_USER_IMAGE: "DIRECTORY:INVALIDATE_USER_IMAGE",
  INVALIDATE_USER_IMAGES: "DIRECTORY:INVALIDATE_USER_IMAGES",
});

type DirectoryEvent = EventNamesOf<typeof directoryEvents>;

class DirectoryEventEmitter extends EventEmitter<DirectoryEvent> {
  constructor() {
    super(directoryEvents);
  }
}

export const directoryEventEmitter = new (singleton(DirectoryEventEmitter))();
