import { EventEmitter, defineEvents, type EventNamesOf } from "nfx-ui/events";
import { singleton } from "nfx-ui/utils";

export const tenantsEvents = defineEvents({
  INVALIDATE_TENANT: "TENANTS:INVALIDATE_TENANT",
  INVALIDATE_TENANTS: "TENANTS:INVALIDATE_TENANTS",
  INVALIDATE_GROUP: "TENANTS:INVALIDATE_GROUP",
  INVALIDATE_GROUPS: "TENANTS:INVALIDATE_GROUPS",
  INVALIDATE_MEMBER: "TENANTS:INVALIDATE_MEMBER",
  INVALIDATE_MEMBERS: "TENANTS:INVALIDATE_MEMBERS",
  INVALIDATE_INVITATION: "TENANTS:INVALIDATE_INVITATION",
  INVALIDATE_INVITATIONS: "TENANTS:INVALIDATE_INVITATIONS",
  INVALIDATE_TENANT_APP: "TENANTS:INVALIDATE_TENANT_APP",
  INVALIDATE_TENANT_APPS: "TENANTS:INVALIDATE_TENANT_APPS",
  INVALIDATE_TENANT_SETTING: "TENANTS:INVALIDATE_TENANT_SETTING",
  INVALIDATE_TENANT_SETTINGS: "TENANTS:INVALIDATE_TENANT_SETTINGS",
  INVALIDATE_DOMAIN_VERIFICATION: "TENANTS:INVALIDATE_DOMAIN_VERIFICATION",
  INVALIDATE_DOMAIN_VERIFICATIONS: "TENANTS:INVALIDATE_DOMAIN_VERIFICATIONS",
  INVALIDATE_MEMBER_ROLE: "TENANTS:INVALIDATE_MEMBER_ROLE",
  INVALIDATE_MEMBER_ROLES: "TENANTS:INVALIDATE_MEMBER_ROLES",
  INVALIDATE_MEMBER_GROUP: "TENANTS:INVALIDATE_MEMBER_GROUP",
  INVALIDATE_MEMBER_GROUPS: "TENANTS:INVALIDATE_MEMBER_GROUPS",
  INVALIDATE_MEMBER_APP_ROLE: "TENANTS:INVALIDATE_MEMBER_APP_ROLE",
  INVALIDATE_MEMBER_APP_ROLES: "TENANTS:INVALIDATE_MEMBER_APP_ROLES",
});

type TenantsEvent = EventNamesOf<typeof tenantsEvents>;

class TenantsEventEmitter extends EventEmitter<TenantsEvent> {
  constructor() {
    super(tenantsEvents);
  }
}

export const tenantsEventEmitter = new (singleton(TenantsEventEmitter))();
