// Code generated by gen-views. DO NOT EDIT.
package views

import (
	"time"
	"uuid"

	"gorm.io/datatypes"
)

type Systemstateactiveview struct {
	ID                    *uuid.UUID      `gorm:"column:id;->"`
	Initialized           *bool           `gorm:"column:initialized;->"`
	InitializedAt         *time.Time      `gorm:"column:initialized_at;->"`
	InitializationVersion *string         `gorm:"column:initialization_version;->"`
	LastResetAt           *time.Time      `gorm:"column:last_reset_at;->"`
	LastResetBy           *uuid.UUID      `gorm:"column:last_reset_by;->"`
	ResetCount            *int            `gorm:"column:reset_count;->"`
	Metadata              *datatypes.JSON `gorm:"column:metadata;->"`
	CreatedAt             *time.Time      `gorm:"column:created_at;->"`
	UpdatedAt             *time.Time      `gorm:"column:updated_at;->"`
}

func (Systemstateactiveview) TableName() string { return "system.SystemStateActiveView" }

var SystemstateactiveviewCols = struct {
	ID, Initialized, InitializedAt, InitializationVersion, LastResetAt, LastResetBy, ResetCount,
	Metadata, CreatedAt, UpdatedAt string
}{
	ID:                    "id",
	Initialized:           "initialized",
	InitializedAt:         "initialized_at",
	InitializationVersion: "initialization_version",
	LastResetAt:           "last_reset_at",
	LastResetBy:           "last_reset_by",
	ResetCount:            "reset_count",
	Metadata:              "metadata",
	CreatedAt:             "created_at",
	UpdatedAt:             "updated_at",
}
