import type { QueryKey } from "@tanstack/react-query";
import { DOMAIN_ACCESS, DOMAIN_ACCESS_ROLE, DOMAIN_ACCESS_PERMISSION, DOMAIN_ACCESS_SCOPE, DOMAIN_ACCESS_GRANT, DOMAIN_ACCESS_ROLE_PERMISSION, DOMAIN_ACCESS_SCOPE_PERMISSION, DOMAIN_ACCESS_ACTION, DOMAIN_ACCESS_ACTION_REQUIREMENT } from "./domain.key";
import { CACHE_ITEM, CACHE_LIST } from "./cache.key";

/**
 * Access 相关的 Query Key 常量
 * 用于统一管理所有 access 相关的 query keys，避免在 pages 中手写
 */

// ========== Role 相关 ==========
export const ACCESS_ROLE_LIST = [DOMAIN_ACCESS, CACHE_LIST, DOMAIN_ACCESS_ROLE];
export const ACCESS_ROLE = (item: string): QueryKey => [DOMAIN_ACCESS, CACHE_ITEM, DOMAIN_ACCESS_ROLE, item];

// ========== Permission 相关 ==========
export const ACCESS_PERMISSION_LIST = [DOMAIN_ACCESS, CACHE_LIST, DOMAIN_ACCESS_PERMISSION];
export const ACCESS_PERMISSION = (item: string): QueryKey => [DOMAIN_ACCESS, CACHE_ITEM, DOMAIN_ACCESS_PERMISSION, item];

// ========== Scope 相关 ==========
export const ACCESS_SCOPE_LIST = [DOMAIN_ACCESS, CACHE_LIST, DOMAIN_ACCESS_SCOPE];
export const ACCESS_SCOPE = (item: string): QueryKey => [DOMAIN_ACCESS, CACHE_ITEM, DOMAIN_ACCESS_SCOPE, item];

// ========== Grant 相关 ==========
export const ACCESS_GRANT_LIST = [DOMAIN_ACCESS, CACHE_LIST, DOMAIN_ACCESS_GRANT];
export const ACCESS_GRANT = (item: string): QueryKey => [DOMAIN_ACCESS, CACHE_ITEM, DOMAIN_ACCESS_GRANT, item];
/** 按 subject 查询 grant 列表的 query key */
export const ACCESS_GRANTS_BY_SUBJECT = (
  subjectType: string,
  subjectId: string,
  tenantId?: string,
): QueryKey =>
  tenantId != null
    ? [DOMAIN_ACCESS, CACHE_LIST, DOMAIN_ACCESS_GRANT, "by-subject", subjectType, subjectId, tenantId]
    : [DOMAIN_ACCESS, CACHE_LIST, DOMAIN_ACCESS_GRANT, "by-subject", subjectType, subjectId];

// ========== RolePermission 相关 ==========
export const ACCESS_ROLE_PERMISSION_LIST = [DOMAIN_ACCESS, CACHE_LIST, DOMAIN_ACCESS_ROLE_PERMISSION];
export const ACCESS_ROLE_PERMISSION = (item: string): QueryKey => [DOMAIN_ACCESS, CACHE_ITEM, DOMAIN_ACCESS_ROLE_PERMISSION, item];
/** 按 roleId 查询角色权限列表的 query key */
export const ACCESS_ROLE_PERMISSIONS_BY_ROLE = (roleId: string): QueryKey =>
  [DOMAIN_ACCESS, CACHE_LIST, DOMAIN_ACCESS_ROLE_PERMISSION, "by-role", roleId];

// ========== Action 相关 ==========
export const ACCESS_ACTION_LIST = [DOMAIN_ACCESS, CACHE_LIST, DOMAIN_ACCESS_ACTION];
export const ACCESS_ACTION = (item: string): QueryKey => [DOMAIN_ACCESS, CACHE_ITEM, DOMAIN_ACCESS_ACTION, item];

// ========== ActionRequirement 相关 ==========
export const ACCESS_ACTION_REQUIREMENT_LIST = [DOMAIN_ACCESS, CACHE_LIST, DOMAIN_ACCESS_ACTION_REQUIREMENT];
export const ACCESS_ACTION_REQUIREMENT = (item: string): QueryKey => [DOMAIN_ACCESS, CACHE_ITEM, DOMAIN_ACCESS_ACTION_REQUIREMENT, item];
export const ACCESS_ACTION_REQUIREMENTS_BY_PERMISSION = (permissionId: string): QueryKey =>
  [DOMAIN_ACCESS, CACHE_LIST, DOMAIN_ACCESS_ACTION_REQUIREMENT, "by-permission", permissionId];

// ========== ScopePermission 相关 ==========
export const ACCESS_SCOPE_PERMISSION_LIST = [DOMAIN_ACCESS, CACHE_LIST, DOMAIN_ACCESS_SCOPE_PERMISSION];
export const ACCESS_SCOPE_PERMISSION = (item: string): QueryKey => [DOMAIN_ACCESS, CACHE_ITEM, DOMAIN_ACCESS_SCOPE_PERMISSION, item];

/**
 * 用于 useCacheInvalidationEvents.ts 的 query key 前缀
 * 这些是用于 invalidateQueries 的匹配前缀
 */
export const ACCESS_QUERY_KEY_PREFIXES = {
  ROLES: [DOMAIN_ACCESS, CACHE_LIST, DOMAIN_ACCESS_ROLE],
  ROLE: [DOMAIN_ACCESS, CACHE_ITEM, DOMAIN_ACCESS_ROLE],
  PERMISSIONS: [DOMAIN_ACCESS, CACHE_LIST, DOMAIN_ACCESS_PERMISSION],
  PERMISSION: [DOMAIN_ACCESS, CACHE_ITEM, DOMAIN_ACCESS_PERMISSION],
  SCOPES: [DOMAIN_ACCESS, CACHE_LIST, DOMAIN_ACCESS_SCOPE],
  SCOPE: [DOMAIN_ACCESS, CACHE_ITEM, DOMAIN_ACCESS_SCOPE],
  GRANTS: [DOMAIN_ACCESS, CACHE_LIST, DOMAIN_ACCESS_GRANT],
  GRANT: [DOMAIN_ACCESS, CACHE_ITEM, DOMAIN_ACCESS_GRANT],
  ROLE_PERMISSIONS: [DOMAIN_ACCESS, CACHE_LIST, DOMAIN_ACCESS_ROLE_PERMISSION],
  ROLE_PERMISSION: [DOMAIN_ACCESS, CACHE_ITEM, DOMAIN_ACCESS_ROLE_PERMISSION],
  SCOPE_PERMISSIONS: [DOMAIN_ACCESS, CACHE_LIST, DOMAIN_ACCESS_SCOPE_PERMISSION],
  SCOPE_PERMISSION: [DOMAIN_ACCESS, CACHE_ITEM, DOMAIN_ACCESS_SCOPE_PERMISSION],
  ACTIONS: [DOMAIN_ACCESS, CACHE_LIST, DOMAIN_ACCESS_ACTION],
  ACTION: [DOMAIN_ACCESS, CACHE_ITEM, DOMAIN_ACCESS_ACTION],
  ACTION_REQUIREMENTS: [DOMAIN_ACCESS, CACHE_LIST, DOMAIN_ACCESS_ACTION_REQUIREMENT],
  ACTION_REQUIREMENT: [DOMAIN_ACCESS, CACHE_ITEM, DOMAIN_ACCESS_ACTION_REQUIREMENT],
};
