import type { QueryKey } from "@tanstack/react-query";
import { DOMAIN_AUDIT, DOMAIN_AUDIT_EVENT, DOMAIN_AUDIT_ACTOR_SNAPSHOT, DOMAIN_AUDIT_EVENT_RETENTION_POLICY, DOMAIN_AUDIT_EVENT_SEARCH_INDEX, DOMAIN_AUDIT_HASH_CHAIN_CHECKPOINT } from "./domain.key";
import { CACHE_ITEM, CACHE_LIST } from "./cache.key";

/**
 * Audit 相关的 Query Key 常量
 */

// ========== Event 相关 ==========
export const AUDIT_EVENT_LIST = [DOMAIN_AUDIT, CACHE_LIST, DOMAIN_AUDIT_EVENT];
export const AUDIT_EVENT = (item: string): QueryKey => [DOMAIN_AUDIT, CACHE_ITEM, DOMAIN_AUDIT_EVENT, item];

// ========== ActorSnapshot 相关 ==========
export const AUDIT_ACTOR_SNAPSHOT_LIST = [DOMAIN_AUDIT, CACHE_LIST, DOMAIN_AUDIT_ACTOR_SNAPSHOT];
export const AUDIT_ACTOR_SNAPSHOT = (item: string): QueryKey => [DOMAIN_AUDIT, CACHE_ITEM, DOMAIN_AUDIT_ACTOR_SNAPSHOT, item];

// ========== EventRetentionPolicy 相关 ==========
export const AUDIT_EVENT_RETENTION_POLICY_LIST = [DOMAIN_AUDIT, CACHE_LIST, DOMAIN_AUDIT_EVENT_RETENTION_POLICY];
export const AUDIT_EVENT_RETENTION_POLICY = (item: string): QueryKey => [DOMAIN_AUDIT, CACHE_ITEM, DOMAIN_AUDIT_EVENT_RETENTION_POLICY, item];

// ========== EventSearchIndex 相关 ==========
export const AUDIT_EVENT_SEARCH_INDEX_LIST = [DOMAIN_AUDIT, CACHE_LIST, DOMAIN_AUDIT_EVENT_SEARCH_INDEX];
export const AUDIT_EVENT_SEARCH_INDEX = (item: string): QueryKey => [DOMAIN_AUDIT, CACHE_ITEM, DOMAIN_AUDIT_EVENT_SEARCH_INDEX, item];

// ========== HashChainCheckpoint 相关 ==========
export const AUDIT_HASH_CHAIN_CHECKPOINT_LIST = [DOMAIN_AUDIT, CACHE_LIST, DOMAIN_AUDIT_HASH_CHAIN_CHECKPOINT];
export const AUDIT_HASH_CHAIN_CHECKPOINT = (item: string): QueryKey => [DOMAIN_AUDIT, CACHE_ITEM, DOMAIN_AUDIT_HASH_CHAIN_CHECKPOINT, item];

/**
 * 用于 useCacheInvalidationEvents.ts 的 query key 前缀
 */
export const AUDIT_QUERY_KEY_PREFIXES = {
  EVENTS: [DOMAIN_AUDIT, CACHE_LIST, DOMAIN_AUDIT_EVENT],
  EVENT: [DOMAIN_AUDIT, CACHE_ITEM, DOMAIN_AUDIT_EVENT],
  ACTOR_SNAPSHOTS: [DOMAIN_AUDIT, CACHE_LIST, DOMAIN_AUDIT_ACTOR_SNAPSHOT],
  ACTOR_SNAPSHOT: [DOMAIN_AUDIT, CACHE_ITEM, DOMAIN_AUDIT_ACTOR_SNAPSHOT],
  EVENT_RETENTION_POLICIES: [DOMAIN_AUDIT, CACHE_LIST, DOMAIN_AUDIT_EVENT_RETENTION_POLICY],
  EVENT_RETENTION_POLICY: [DOMAIN_AUDIT, CACHE_ITEM, DOMAIN_AUDIT_EVENT_RETENTION_POLICY],
  EVENT_SEARCH_INDICES: [DOMAIN_AUDIT, CACHE_LIST, DOMAIN_AUDIT_EVENT_SEARCH_INDEX],
  EVENT_SEARCH_INDEX: [DOMAIN_AUDIT, CACHE_ITEM, DOMAIN_AUDIT_EVENT_SEARCH_INDEX],
  HASH_CHAIN_CHECKPOINTS: [DOMAIN_AUDIT, CACHE_LIST, DOMAIN_AUDIT_HASH_CHAIN_CHECKPOINT],
  HASH_CHAIN_CHECKPOINT: [DOMAIN_AUDIT, CACHE_ITEM, DOMAIN_AUDIT_HASH_CHAIN_CHECKPOINT],
};
