import { createItemKey, createListKey } from "nfx-ui/constants";
import { DOMAIN_AUDIT, DOMAIN_AUDIT_EVENT, DOMAIN_AUDIT_ACTOR_SNAPSHOT, DOMAIN_AUDIT_EVENT_RETENTION_POLICY, DOMAIN_AUDIT_EVENT_SEARCH_INDEX, DOMAIN_AUDIT_HASH_CHAIN_CHECKPOINT } from "./domain.key";

export const AUDIT_EVENT_LIST = createListKey(DOMAIN_AUDIT, DOMAIN_AUDIT_EVENT);
export const AUDIT_EVENT = createItemKey(DOMAIN_AUDIT, DOMAIN_AUDIT_EVENT);

export const AUDIT_ACTOR_SNAPSHOT_LIST = createListKey(DOMAIN_AUDIT, DOMAIN_AUDIT_ACTOR_SNAPSHOT);
export const AUDIT_ACTOR_SNAPSHOT = createItemKey(DOMAIN_AUDIT, DOMAIN_AUDIT_ACTOR_SNAPSHOT);

export const AUDIT_EVENT_RETENTION_POLICY_LIST = createListKey(DOMAIN_AUDIT, DOMAIN_AUDIT_EVENT_RETENTION_POLICY);
export const AUDIT_EVENT_RETENTION_POLICY = createItemKey(DOMAIN_AUDIT, DOMAIN_AUDIT_EVENT_RETENTION_POLICY);

export const AUDIT_EVENT_SEARCH_INDEX_LIST = createListKey(DOMAIN_AUDIT, DOMAIN_AUDIT_EVENT_SEARCH_INDEX);
export const AUDIT_EVENT_SEARCH_INDEX = createItemKey(DOMAIN_AUDIT, DOMAIN_AUDIT_EVENT_SEARCH_INDEX);

export const AUDIT_HASH_CHAIN_CHECKPOINT_LIST = createListKey(DOMAIN_AUDIT, DOMAIN_AUDIT_HASH_CHAIN_CHECKPOINT);
export const AUDIT_HASH_CHAIN_CHECKPOINT = createItemKey(DOMAIN_AUDIT, DOMAIN_AUDIT_HASH_CHAIN_CHECKPOINT);

