import type { QueryKey } from "@tanstack/react-query";
import { DOMAIN_AUTH, DOMAIN_AUTH_SESSION, DOMAIN_AUTH_USER_CREDENTIAL, DOMAIN_AUTH_MFA_FACTOR, DOMAIN_AUTH_REFRESH_TOKEN, DOMAIN_AUTH_PASSWORD_RESET, DOMAIN_AUTH_PASSWORD_HISTORY, DOMAIN_AUTH_LOGIN_ATTEMPT, DOMAIN_AUTH_ACCOUNT_LOCKOUT, DOMAIN_AUTH_TRUSTED_DEVICE } from "./domain.key";
import { CACHE_ITEM, CACHE_LIST } from "./cache.key";

/**
 * Auth 相关的 Query Key 常量
 * 用于统一管理所有 auth 相关的 query keys，避免在 pages 中手写
 */

// ========== Session 相关 ==========
export const AUTH_SESSION_LIST = [DOMAIN_AUTH, CACHE_LIST, DOMAIN_AUTH_SESSION];
export const AUTH_SESSION = (item: string): QueryKey => [DOMAIN_AUTH, CACHE_ITEM, DOMAIN_AUTH_SESSION, item];

// ========== UserCredential 相关 ==========
export const AUTH_USER_CREDENTIAL_LIST = [DOMAIN_AUTH, CACHE_LIST, DOMAIN_AUTH_USER_CREDENTIAL];
export const AUTH_USER_CREDENTIAL = (item: string): QueryKey => [DOMAIN_AUTH, CACHE_ITEM, DOMAIN_AUTH_USER_CREDENTIAL, item];

// ========== MFAFactor 相关 ==========
export const AUTH_MFA_FACTOR_LIST = [DOMAIN_AUTH, CACHE_LIST, DOMAIN_AUTH_MFA_FACTOR];
export const AUTH_MFA_FACTOR = (item: string): QueryKey => [DOMAIN_AUTH, CACHE_ITEM, DOMAIN_AUTH_MFA_FACTOR, item];

// ========== RefreshToken 相关 ==========
export const AUTH_REFRESH_TOKEN_LIST = [DOMAIN_AUTH, CACHE_LIST, DOMAIN_AUTH_REFRESH_TOKEN];
export const AUTH_REFRESH_TOKEN = (item: string): QueryKey => [DOMAIN_AUTH, CACHE_ITEM, DOMAIN_AUTH_REFRESH_TOKEN, item];

// ========== PasswordReset 相关 ==========
export const AUTH_PASSWORD_RESET_LIST = [DOMAIN_AUTH, CACHE_LIST, DOMAIN_AUTH_PASSWORD_RESET];
export const AUTH_PASSWORD_RESET = (item: string): QueryKey => [DOMAIN_AUTH, CACHE_ITEM, DOMAIN_AUTH_PASSWORD_RESET, item];

// ========== PasswordHistory 相关 ==========
export const AUTH_PASSWORD_HISTORY_LIST = [DOMAIN_AUTH, CACHE_LIST, DOMAIN_AUTH_PASSWORD_HISTORY];
export const AUTH_PASSWORD_HISTORY = (item: string): QueryKey => [DOMAIN_AUTH, CACHE_ITEM, DOMAIN_AUTH_PASSWORD_HISTORY, item];

// ========== LoginAttempt 相关 ==========
export const AUTH_LOGIN_ATTEMPT_LIST = [DOMAIN_AUTH, CACHE_LIST, DOMAIN_AUTH_LOGIN_ATTEMPT];
export const AUTH_LOGIN_ATTEMPT = (item: string): QueryKey => [DOMAIN_AUTH, CACHE_ITEM, DOMAIN_AUTH_LOGIN_ATTEMPT, item];

// ========== AccountLockout 相关 ==========
export const AUTH_ACCOUNT_LOCKOUT_LIST = [DOMAIN_AUTH, CACHE_LIST, DOMAIN_AUTH_ACCOUNT_LOCKOUT];
export const AUTH_ACCOUNT_LOCKOUT = (item: string): QueryKey => [DOMAIN_AUTH, CACHE_ITEM, DOMAIN_AUTH_ACCOUNT_LOCKOUT, item];

// ========== TrustedDevice 相关 ==========
export const AUTH_TRUSTED_DEVICE_LIST = [DOMAIN_AUTH, CACHE_LIST, DOMAIN_AUTH_TRUSTED_DEVICE];
export const AUTH_TRUSTED_DEVICE = (item: string): QueryKey => [DOMAIN_AUTH, CACHE_ITEM, DOMAIN_AUTH_TRUSTED_DEVICE, item];

/**
 * 用于 useCacheInvalidationEvents.ts 的 query key 前缀
 */
export const AUTH_QUERY_KEY_PREFIXES = {
  SESSIONS: [DOMAIN_AUTH, CACHE_LIST, DOMAIN_AUTH_SESSION],
  SESSION: [DOMAIN_AUTH, CACHE_ITEM, DOMAIN_AUTH_SESSION],
  USER_CREDENTIALS: [DOMAIN_AUTH, CACHE_LIST, DOMAIN_AUTH_USER_CREDENTIAL],
  USER_CREDENTIAL: [DOMAIN_AUTH, CACHE_ITEM, DOMAIN_AUTH_USER_CREDENTIAL],
  MFA_FACTORS: [DOMAIN_AUTH, CACHE_LIST, DOMAIN_AUTH_MFA_FACTOR],
  MFA_FACTOR: [DOMAIN_AUTH, CACHE_ITEM, DOMAIN_AUTH_MFA_FACTOR],
  REFRESH_TOKENS: [DOMAIN_AUTH, CACHE_LIST, DOMAIN_AUTH_REFRESH_TOKEN],
  REFRESH_TOKEN: [DOMAIN_AUTH, CACHE_ITEM, DOMAIN_AUTH_REFRESH_TOKEN],
  PASSWORD_RESETS: [DOMAIN_AUTH, CACHE_LIST, DOMAIN_AUTH_PASSWORD_RESET],
  PASSWORD_RESET: [DOMAIN_AUTH, CACHE_ITEM, DOMAIN_AUTH_PASSWORD_RESET],
  PASSWORD_HISTORIES: [DOMAIN_AUTH, CACHE_LIST, DOMAIN_AUTH_PASSWORD_HISTORY],
  PASSWORD_HISTORY: [DOMAIN_AUTH, CACHE_ITEM, DOMAIN_AUTH_PASSWORD_HISTORY],
  LOGIN_ATTEMPTS: [DOMAIN_AUTH, CACHE_LIST, DOMAIN_AUTH_LOGIN_ATTEMPT],
  LOGIN_ATTEMPT: [DOMAIN_AUTH, CACHE_ITEM, DOMAIN_AUTH_LOGIN_ATTEMPT],
  ACCOUNT_LOCKOUTS: [DOMAIN_AUTH, CACHE_LIST, DOMAIN_AUTH_ACCOUNT_LOCKOUT],
  ACCOUNT_LOCKOUT: [DOMAIN_AUTH, CACHE_ITEM, DOMAIN_AUTH_ACCOUNT_LOCKOUT],
  TRUSTED_DEVICES: [DOMAIN_AUTH, CACHE_LIST, DOMAIN_AUTH_TRUSTED_DEVICE],
  TRUSTED_DEVICE: [DOMAIN_AUTH, CACHE_ITEM, DOMAIN_AUTH_TRUSTED_DEVICE],
};
