import { createItemKey, createListKey } from "nfx-ui/constants";
import { DOMAIN_CLIENTS, DOMAIN_CLIENTS_APP, DOMAIN_CLIENTS_API_KEY, DOMAIN_CLIENTS_CLIENT_CREDENTIAL, DOMAIN_CLIENTS_CLIENT_SCOPE, DOMAIN_CLIENTS_IP_ALLOWLIST, DOMAIN_CLIENTS_RATE_LIMIT } from "./domain.key";

export const CLIENTS_APP_LIST = createListKey(DOMAIN_CLIENTS, DOMAIN_CLIENTS_APP);
export const CLIENTS_APP = createItemKey(DOMAIN_CLIENTS, DOMAIN_CLIENTS_APP);
export const CLIENTS_API_KEY_LIST = createListKey(DOMAIN_CLIENTS, DOMAIN_CLIENTS_API_KEY);
export const CLIENTS_API_KEY = createItemKey(DOMAIN_CLIENTS, DOMAIN_CLIENTS_API_KEY);
export const CLIENTS_CLIENT_CREDENTIAL_LIST = createListKey(DOMAIN_CLIENTS, DOMAIN_CLIENTS_CLIENT_CREDENTIAL);
export const CLIENTS_CLIENT_CREDENTIAL = createItemKey(DOMAIN_CLIENTS, DOMAIN_CLIENTS_CLIENT_CREDENTIAL);
export const CLIENTS_CLIENT_SCOPE_LIST = createListKey(DOMAIN_CLIENTS, DOMAIN_CLIENTS_CLIENT_SCOPE);
export const CLIENTS_CLIENT_SCOPE = createItemKey(DOMAIN_CLIENTS, DOMAIN_CLIENTS_CLIENT_SCOPE);
export const CLIENTS_IP_ALLOWLIST_LIST = createListKey(DOMAIN_CLIENTS, DOMAIN_CLIENTS_IP_ALLOWLIST);
export const CLIENTS_IP_ALLOWLIST = createItemKey(DOMAIN_CLIENTS, DOMAIN_CLIENTS_IP_ALLOWLIST);
export const CLIENTS_RATE_LIMIT_LIST = createListKey(DOMAIN_CLIENTS, DOMAIN_CLIENTS_RATE_LIMIT);
export const CLIENTS_RATE_LIMIT = createItemKey(DOMAIN_CLIENTS, DOMAIN_CLIENTS_RATE_LIMIT);

