import type { QueryKey } from "@tanstack/react-query";
import { DOMAIN_CLIENTS, DOMAIN_CLIENTS_APP, DOMAIN_CLIENTS_API_KEY, DOMAIN_CLIENTS_CLIENT_CREDENTIAL, DOMAIN_CLIENTS_CLIENT_SCOPE, DOMAIN_CLIENTS_IP_ALLOWLIST, DOMAIN_CLIENTS_RATE_LIMIT } from "./domain.key";
import { CACHE_ITEM, CACHE_LIST } from "./cache.key";

/**
 * Clients 相关的 Query Key 常量
 */

// ========== App 相关 ==========
export const CLIENTS_APP_LIST = [DOMAIN_CLIENTS, CACHE_LIST, DOMAIN_CLIENTS_APP];
export const CLIENTS_APP = (item: string): QueryKey => [DOMAIN_CLIENTS, CACHE_ITEM, DOMAIN_CLIENTS_APP, item];

// ========== APIKey 相关 ==========
export const CLIENTS_API_KEY_LIST = [DOMAIN_CLIENTS, CACHE_LIST, DOMAIN_CLIENTS_API_KEY];
export const CLIENTS_API_KEY = (item: string): QueryKey => [DOMAIN_CLIENTS, CACHE_ITEM, DOMAIN_CLIENTS_API_KEY, item];

// ========== ClientCredential 相关 ==========
export const CLIENTS_CLIENT_CREDENTIAL_LIST = [DOMAIN_CLIENTS, CACHE_LIST, DOMAIN_CLIENTS_CLIENT_CREDENTIAL];
export const CLIENTS_CLIENT_CREDENTIAL = (item: string): QueryKey => [DOMAIN_CLIENTS, CACHE_ITEM, DOMAIN_CLIENTS_CLIENT_CREDENTIAL, item];

// ========== ClientScope 相关 ==========
export const CLIENTS_CLIENT_SCOPE_LIST = [DOMAIN_CLIENTS, CACHE_LIST, DOMAIN_CLIENTS_CLIENT_SCOPE];
export const CLIENTS_CLIENT_SCOPE = (item: string): QueryKey => [DOMAIN_CLIENTS, CACHE_ITEM, DOMAIN_CLIENTS_CLIENT_SCOPE, item];

// ========== IPAllowlist 相关 ==========
export const CLIENTS_IP_ALLOWLIST_LIST = [DOMAIN_CLIENTS, CACHE_LIST, DOMAIN_CLIENTS_IP_ALLOWLIST];
export const CLIENTS_IP_ALLOWLIST = (item: string): QueryKey => [DOMAIN_CLIENTS, CACHE_ITEM, DOMAIN_CLIENTS_IP_ALLOWLIST, item];

// ========== RateLimit 相关 ==========
export const CLIENTS_RATE_LIMIT_LIST = [DOMAIN_CLIENTS, CACHE_LIST, DOMAIN_CLIENTS_RATE_LIMIT];
export const CLIENTS_RATE_LIMIT = (item: string): QueryKey => [DOMAIN_CLIENTS, CACHE_ITEM, DOMAIN_CLIENTS_RATE_LIMIT, item];

/**
 * 用于 useCacheInvalidationEvents.ts 的 query key 前缀
 */
export const CLIENTS_QUERY_KEY_PREFIXES = {
  APPS: [DOMAIN_CLIENTS, CACHE_LIST, DOMAIN_CLIENTS_APP],
  APP: [DOMAIN_CLIENTS, CACHE_ITEM, DOMAIN_CLIENTS_APP],
  API_KEYS: [DOMAIN_CLIENTS, CACHE_LIST, DOMAIN_CLIENTS_API_KEY],
  API_KEY: [DOMAIN_CLIENTS, CACHE_ITEM, DOMAIN_CLIENTS_API_KEY],
  CLIENT_CREDENTIALS: [DOMAIN_CLIENTS, CACHE_LIST, DOMAIN_CLIENTS_CLIENT_CREDENTIAL],
  CLIENT_CREDENTIAL: [DOMAIN_CLIENTS, CACHE_ITEM, DOMAIN_CLIENTS_CLIENT_CREDENTIAL],
  CLIENT_SCOPES: [DOMAIN_CLIENTS, CACHE_LIST, DOMAIN_CLIENTS_CLIENT_SCOPE],
  CLIENT_SCOPE: [DOMAIN_CLIENTS, CACHE_ITEM, DOMAIN_CLIENTS_CLIENT_SCOPE],
  IP_ALLOWLISTS: [DOMAIN_CLIENTS, CACHE_LIST, DOMAIN_CLIENTS_IP_ALLOWLIST],
  IP_ALLOWLIST: [DOMAIN_CLIENTS, CACHE_ITEM, DOMAIN_CLIENTS_IP_ALLOWLIST],
  RATE_LIMITS: [DOMAIN_CLIENTS, CACHE_LIST, DOMAIN_CLIENTS_RATE_LIMIT],
  RATE_LIMIT: [DOMAIN_CLIENTS, CACHE_ITEM, DOMAIN_CLIENTS_RATE_LIMIT],
};
