import type { QueryKey } from "@tanstack/react-query";
import { DOMAIN_DIRECTORY, DOMAIN_DIRECTORY_USER, DOMAIN_DIRECTORY_BADGE, DOMAIN_DIRECTORY_USER_BADGE, DOMAIN_DIRECTORY_USER_EDUCATION, DOMAIN_DIRECTORY_USER_EMAIL, DOMAIN_DIRECTORY_USER_OCCUPATION, DOMAIN_DIRECTORY_USER_PHONE, DOMAIN_DIRECTORY_USER_PREFERENCE, DOMAIN_DIRECTORY_USER_PROFILE } from "./domain.key";
import { CACHE_ITEM, CACHE_LIST } from "./cache.key";

/**
 * Directory 相关的 Query Key 常量
 */

// ========== User 相关 ==========
export const DIRECTORY_USER_LIST = [DOMAIN_DIRECTORY, CACHE_LIST, DOMAIN_DIRECTORY_USER];
export const DIRECTORY_USER = (item: string): QueryKey => [DOMAIN_DIRECTORY, CACHE_ITEM, DOMAIN_DIRECTORY_USER, item];

// ========== Badge 相关 ==========
export const DIRECTORY_BADGE_LIST = [DOMAIN_DIRECTORY, CACHE_LIST, DOMAIN_DIRECTORY_BADGE];
export const DIRECTORY_BADGE = (item: string): QueryKey => [DOMAIN_DIRECTORY, CACHE_ITEM, DOMAIN_DIRECTORY_BADGE, item];

// ========== UserBadge 相关 ==========
export const DIRECTORY_USER_BADGE_LIST = [DOMAIN_DIRECTORY, CACHE_LIST, DOMAIN_DIRECTORY_USER_BADGE];
export const DIRECTORY_USER_BADGE = (item: string): QueryKey => [DOMAIN_DIRECTORY, CACHE_ITEM, DOMAIN_DIRECTORY_USER_BADGE, item];

// ========== UserEducation 相关 ==========
export const DIRECTORY_USER_EDUCATION_LIST = [DOMAIN_DIRECTORY, CACHE_LIST, DOMAIN_DIRECTORY_USER_EDUCATION];
export const DIRECTORY_USER_EDUCATION = (item: string): QueryKey => [DOMAIN_DIRECTORY, CACHE_ITEM, DOMAIN_DIRECTORY_USER_EDUCATION, item];

// ========== UserEmail 相关 ==========
export const DIRECTORY_USER_EMAIL_LIST = [DOMAIN_DIRECTORY, CACHE_LIST, DOMAIN_DIRECTORY_USER_EMAIL];
export const DIRECTORY_USER_EMAIL = (item: string): QueryKey => [DOMAIN_DIRECTORY, CACHE_ITEM, DOMAIN_DIRECTORY_USER_EMAIL, item];

// ========== UserOccupation 相关 ==========
export const DIRECTORY_USER_OCCUPATION_LIST = [DOMAIN_DIRECTORY, CACHE_LIST, DOMAIN_DIRECTORY_USER_OCCUPATION];
export const DIRECTORY_USER_OCCUPATION = (item: string): QueryKey => [DOMAIN_DIRECTORY, CACHE_ITEM, DOMAIN_DIRECTORY_USER_OCCUPATION, item];

// ========== UserPhone 相关 ==========
export const DIRECTORY_USER_PHONE_LIST = [DOMAIN_DIRECTORY, CACHE_LIST, DOMAIN_DIRECTORY_USER_PHONE];
export const DIRECTORY_USER_PHONE = (item: string): QueryKey => [DOMAIN_DIRECTORY, CACHE_ITEM, DOMAIN_DIRECTORY_USER_PHONE, item];

// ========== UserPreference 相关 ==========
export const DIRECTORY_USER_PREFERENCE_LIST = [DOMAIN_DIRECTORY, CACHE_LIST, DOMAIN_DIRECTORY_USER_PREFERENCE];
export const DIRECTORY_USER_PREFERENCE = (item: string): QueryKey => [DOMAIN_DIRECTORY, CACHE_ITEM, DOMAIN_DIRECTORY_USER_PREFERENCE, item];

// ========== UserProfile 相关 ==========
export const DIRECTORY_USER_PROFILE_LIST = [DOMAIN_DIRECTORY, CACHE_LIST, DOMAIN_DIRECTORY_USER_PROFILE];
export const DIRECTORY_USER_PROFILE = (item: string): QueryKey => [DOMAIN_DIRECTORY, CACHE_ITEM, DOMAIN_DIRECTORY_USER_PROFILE, item];

/**
 * 用于 useCacheInvalidationEvents.ts 的 query key 前缀
 */
export const DIRECTORY_QUERY_KEY_PREFIXES = {
  USERS: [DOMAIN_DIRECTORY, CACHE_LIST, DOMAIN_DIRECTORY_USER],
  USER: [DOMAIN_DIRECTORY, CACHE_ITEM, DOMAIN_DIRECTORY_USER],
  BADGES: [DOMAIN_DIRECTORY, CACHE_LIST, DOMAIN_DIRECTORY_BADGE],
  BADGE: [DOMAIN_DIRECTORY, CACHE_ITEM, DOMAIN_DIRECTORY_BADGE],
  USER_BADGES: [DOMAIN_DIRECTORY, CACHE_LIST, DOMAIN_DIRECTORY_USER_BADGE],
  USER_BADGE: [DOMAIN_DIRECTORY, CACHE_ITEM, DOMAIN_DIRECTORY_USER_BADGE],
  USER_EDUCATIONS: [DOMAIN_DIRECTORY, CACHE_LIST, DOMAIN_DIRECTORY_USER_EDUCATION],
  USER_EDUCATION: [DOMAIN_DIRECTORY, CACHE_ITEM, DOMAIN_DIRECTORY_USER_EDUCATION],
  USER_EMAILS: [DOMAIN_DIRECTORY, CACHE_LIST, DOMAIN_DIRECTORY_USER_EMAIL],
  USER_EMAIL: [DOMAIN_DIRECTORY, CACHE_ITEM, DOMAIN_DIRECTORY_USER_EMAIL],
  USER_OCCUPATIONS: [DOMAIN_DIRECTORY, CACHE_LIST, DOMAIN_DIRECTORY_USER_OCCUPATION],
  USER_OCCUPATION: [DOMAIN_DIRECTORY, CACHE_ITEM, DOMAIN_DIRECTORY_USER_OCCUPATION],
  USER_PHONES: [DOMAIN_DIRECTORY, CACHE_LIST, DOMAIN_DIRECTORY_USER_PHONE],
  USER_PHONE: [DOMAIN_DIRECTORY, CACHE_ITEM, DOMAIN_DIRECTORY_USER_PHONE],
  USER_PREFERENCES: [DOMAIN_DIRECTORY, CACHE_LIST, DOMAIN_DIRECTORY_USER_PREFERENCE],
  USER_PREFERENCE: [DOMAIN_DIRECTORY, CACHE_ITEM, DOMAIN_DIRECTORY_USER_PREFERENCE],
  USER_PROFILES: [DOMAIN_DIRECTORY, CACHE_LIST, DOMAIN_DIRECTORY_USER_PROFILE],
  USER_PROFILE: [DOMAIN_DIRECTORY, CACHE_ITEM, DOMAIN_DIRECTORY_USER_PROFILE],
};
