import { createItemKey, createListKey } from "nfx-ui/constants";
import { DOMAIN_DIRECTORY, DOMAIN_DIRECTORY_USER, DOMAIN_DIRECTORY_BADGE, DOMAIN_DIRECTORY_USER_BADGE, DOMAIN_DIRECTORY_USER_EDUCATION, DOMAIN_DIRECTORY_USER_EMAIL, DOMAIN_DIRECTORY_USER_OCCUPATION, DOMAIN_DIRECTORY_USER_PHONE, DOMAIN_DIRECTORY_USER_PREFERENCE, DOMAIN_DIRECTORY_USER_PROFILE, DOMAIN_DIRECTORY_USER_AVATAR, DOMAIN_DIRECTORY_USER_IMAGE } from "./domain.key";

export const DIRECTORY_USER_LIST = createListKey(DOMAIN_DIRECTORY, DOMAIN_DIRECTORY_USER);
export const DIRECTORY_USER = createItemKey(DOMAIN_DIRECTORY, DOMAIN_DIRECTORY_USER);

// ========== Badge 相关 ==========
export const DIRECTORY_BADGE_LIST = createListKey(DOMAIN_DIRECTORY, DOMAIN_DIRECTORY_BADGE);
export const DIRECTORY_BADGE = createItemKey(DOMAIN_DIRECTORY, DOMAIN_DIRECTORY_BADGE);

// ========== UserBadge 相关 ==========
export const DIRECTORY_USER_BADGE_LIST = createListKey(DOMAIN_DIRECTORY, DOMAIN_DIRECTORY_USER_BADGE);
export const DIRECTORY_USER_BADGE = createItemKey(DOMAIN_DIRECTORY, DOMAIN_DIRECTORY_USER_BADGE);

// ========== UserEducation 相关 ==========
export const DIRECTORY_USER_EDUCATION_LIST = createListKey(DOMAIN_DIRECTORY, DOMAIN_DIRECTORY_USER_EDUCATION);
export const DIRECTORY_USER_EDUCATION = createItemKey(DOMAIN_DIRECTORY, DOMAIN_DIRECTORY_USER_EDUCATION);

// ========== UserEmail 相关 ==========
export const DIRECTORY_USER_EMAIL_LIST = createListKey(DOMAIN_DIRECTORY, DOMAIN_DIRECTORY_USER_EMAIL);
export const DIRECTORY_USER_EMAIL = createItemKey(DOMAIN_DIRECTORY, DOMAIN_DIRECTORY_USER_EMAIL);

// ========== UserOccupation 相关 ==========
export const DIRECTORY_USER_OCCUPATION_LIST = createListKey(DOMAIN_DIRECTORY, DOMAIN_DIRECTORY_USER_OCCUPATION);
export const DIRECTORY_USER_OCCUPATION = createItemKey(DOMAIN_DIRECTORY, DOMAIN_DIRECTORY_USER_OCCUPATION);

// ========== UserPhone 相关 ==========
export const DIRECTORY_USER_PHONE_LIST = createListKey(DOMAIN_DIRECTORY, DOMAIN_DIRECTORY_USER_PHONE);
export const DIRECTORY_USER_PHONE = createItemKey(DOMAIN_DIRECTORY, DOMAIN_DIRECTORY_USER_PHONE);

// ========== UserPreference 相关 ==========
export const DIRECTORY_USER_PREFERENCE_LIST = createListKey(DOMAIN_DIRECTORY, DOMAIN_DIRECTORY_USER_PREFERENCE);
export const DIRECTORY_USER_PREFERENCE = createItemKey(DOMAIN_DIRECTORY, DOMAIN_DIRECTORY_USER_PREFERENCE);

// ========== UserProfile 相关 ==========
export const DIRECTORY_USER_PROFILE_LIST = createListKey(DOMAIN_DIRECTORY, DOMAIN_DIRECTORY_USER_PROFILE);
export const DIRECTORY_USER_PROFILE = createItemKey(DOMAIN_DIRECTORY, DOMAIN_DIRECTORY_USER_PROFILE);

// ========== UserAvatar 相关 ==========
export const DIRECTORY_USER_AVATAR_LIST = createListKey(DOMAIN_DIRECTORY, DOMAIN_DIRECTORY_USER_AVATAR);
export const DIRECTORY_USER_AVATAR = createItemKey(DOMAIN_DIRECTORY, DOMAIN_DIRECTORY_USER_AVATAR);

// ========== UserImage 相关 ==========
export const DIRECTORY_USER_IMAGE_LIST = createListKey(DOMAIN_DIRECTORY, DOMAIN_DIRECTORY_USER_IMAGE);
export const DIRECTORY_USER_IMAGE = createItemKey(DOMAIN_DIRECTORY, DOMAIN_DIRECTORY_USER_IMAGE);

/**
 * 用于 useCacheInvalidationEvents.ts 的 query key 前缀
 */
