import { createItemKey, createListKey } from "nfx-ui/constants";
import { DOMAIN_IMAGE, DOMAIN_IMAGE_IMAGE, DOMAIN_IMAGE_IMAGE_TYPE, DOMAIN_IMAGE_IMAGE_VARIANT, DOMAIN_IMAGE_IMAGE_TAG } from "./domain.key";

export const IMAGE_IMAGE_LIST = createListKey(DOMAIN_IMAGE, DOMAIN_IMAGE_IMAGE);
export const IMAGE_IMAGE = createItemKey(DOMAIN_IMAGE, DOMAIN_IMAGE_IMAGE);

export const IMAGE_IMAGE_TYPE_LIST = createListKey(DOMAIN_IMAGE, DOMAIN_IMAGE_IMAGE_TYPE);
export const IMAGE_IMAGE_TYPE = createItemKey(DOMAIN_IMAGE, DOMAIN_IMAGE_IMAGE_TYPE);

export const IMAGE_IMAGE_VARIANT_LIST = createListKey(DOMAIN_IMAGE, DOMAIN_IMAGE_IMAGE_VARIANT);
export const IMAGE_IMAGE_VARIANT = createItemKey(DOMAIN_IMAGE, DOMAIN_IMAGE_IMAGE_VARIANT);

export const IMAGE_IMAGE_TAG_LIST = createListKey(DOMAIN_IMAGE, DOMAIN_IMAGE_IMAGE_TAG);
export const IMAGE_IMAGE_TAG = createItemKey(DOMAIN_IMAGE, DOMAIN_IMAGE_IMAGE_TAG);

