import type { QueryKey } from "@tanstack/react-query";
import { DOMAIN_IMAGE, DOMAIN_IMAGE_IMAGE, DOMAIN_IMAGE_IMAGE_TYPE, DOMAIN_IMAGE_IMAGE_VARIANT, DOMAIN_IMAGE_IMAGE_TAG } from "./domain.key";
import { CACHE_ITEM, CACHE_LIST } from "./cache.key";

/**
 * Image 相关的 Query Key 常量
 */

// ========== Image 相关 ==========
export const IMAGE_IMAGE_LIST = [DOMAIN_IMAGE, CACHE_LIST, DOMAIN_IMAGE_IMAGE];
export const IMAGE_IMAGE = (item: string): QueryKey => [DOMAIN_IMAGE, CACHE_ITEM, DOMAIN_IMAGE_IMAGE, item];

// ========== ImageType 相关 ==========
export const IMAGE_IMAGE_TYPE_LIST = [DOMAIN_IMAGE, CACHE_LIST, DOMAIN_IMAGE_IMAGE_TYPE];
export const IMAGE_IMAGE_TYPE = (item: string): QueryKey => [DOMAIN_IMAGE, CACHE_ITEM, DOMAIN_IMAGE_IMAGE_TYPE, item];

// ========== ImageVariant 相关 ==========
export const IMAGE_IMAGE_VARIANT_LIST = [DOMAIN_IMAGE, CACHE_LIST, DOMAIN_IMAGE_IMAGE_VARIANT];
export const IMAGE_IMAGE_VARIANT = (item: string): QueryKey => [DOMAIN_IMAGE, CACHE_ITEM, DOMAIN_IMAGE_IMAGE_VARIANT, item];

// ========== ImageTag 相关 ==========
export const IMAGE_IMAGE_TAG_LIST = [DOMAIN_IMAGE, CACHE_LIST, DOMAIN_IMAGE_IMAGE_TAG];
export const IMAGE_IMAGE_TAG = (item: string): QueryKey => [DOMAIN_IMAGE, CACHE_ITEM, DOMAIN_IMAGE_IMAGE_TAG, item];

/**
 * 用于 useCacheInvalidationEvents.ts 的 query key 前缀
 */
export const IMAGE_QUERY_KEY_PREFIXES = {
  IMAGES: [DOMAIN_IMAGE, CACHE_LIST, DOMAIN_IMAGE_IMAGE],
  IMAGE: [DOMAIN_IMAGE, CACHE_ITEM, DOMAIN_IMAGE_IMAGE],
  IMAGE_TYPES: [DOMAIN_IMAGE, CACHE_LIST, DOMAIN_IMAGE_IMAGE_TYPE],
  IMAGE_TYPE: [DOMAIN_IMAGE, CACHE_ITEM, DOMAIN_IMAGE_IMAGE_TYPE],
  IMAGE_VARIANTS: [DOMAIN_IMAGE, CACHE_LIST, DOMAIN_IMAGE_IMAGE_VARIANT],
  IMAGE_VARIANT: [DOMAIN_IMAGE, CACHE_ITEM, DOMAIN_IMAGE_IMAGE_VARIANT],
  IMAGE_TAGS: [DOMAIN_IMAGE, CACHE_LIST, DOMAIN_IMAGE_IMAGE_TAG],
  IMAGE_TAG: [DOMAIN_IMAGE, CACHE_ITEM, DOMAIN_IMAGE_IMAGE_TAG],
};
