import { createItemKey, createListKey } from "nfx-ui/constants";
import { DOMAIN_TENANTS, DOMAIN_TENANTS_TENANT, DOMAIN_TENANTS_GROUP, DOMAIN_TENANTS_MEMBER, DOMAIN_TENANTS_INVITATION, DOMAIN_TENANTS_TENANT_APP, DOMAIN_TENANTS_TENANT_SETTING, DOMAIN_TENANTS_DOMAIN_VERIFICATION, DOMAIN_TENANTS_MEMBER_ROLE, DOMAIN_TENANTS_MEMBER_GROUP, DOMAIN_TENANTS_MEMBER_APP_ROLE } from "./domain.key";

// ========== Tenant ==========
export const TENANTS_TENANT_LIST = createListKey(DOMAIN_TENANTS, DOMAIN_TENANTS_TENANT);
export const TENANTS_TENANT = createItemKey(DOMAIN_TENANTS, DOMAIN_TENANTS_TENANT);

// ========== Group ==========
export const TENANTS_GROUP_LIST = createListKey(DOMAIN_TENANTS, DOMAIN_TENANTS_GROUP);
export const TENANTS_GROUP = createItemKey(DOMAIN_TENANTS, DOMAIN_TENANTS_GROUP);

// ========== Member ==========
export const TENANTS_MEMBER_LIST = createListKey(DOMAIN_TENANTS, DOMAIN_TENANTS_MEMBER);
export const TENANTS_MEMBER = createItemKey(DOMAIN_TENANTS, DOMAIN_TENANTS_MEMBER);

// ========== Invitation ==========
export const TENANTS_INVITATION_LIST = createListKey(DOMAIN_TENANTS, DOMAIN_TENANTS_INVITATION);
export const TENANTS_INVITATION = createItemKey(DOMAIN_TENANTS, DOMAIN_TENANTS_INVITATION);

// ========== TenantApp ==========
export const TENANTS_TENANT_APP_LIST = createListKey(DOMAIN_TENANTS, DOMAIN_TENANTS_TENANT_APP);
export const TENANTS_TENANT_APP = createItemKey(DOMAIN_TENANTS, DOMAIN_TENANTS_TENANT_APP);

// ========== TenantSetting ==========
export const TENANTS_TENANT_SETTING_LIST = createListKey(DOMAIN_TENANTS, DOMAIN_TENANTS_TENANT_SETTING);
export const TENANTS_TENANT_SETTING = createItemKey(DOMAIN_TENANTS, DOMAIN_TENANTS_TENANT_SETTING);

// ========== DomainVerification ==========
export const TENANTS_DOMAIN_VERIFICATION_LIST = createListKey(DOMAIN_TENANTS, DOMAIN_TENANTS_DOMAIN_VERIFICATION);
export const TENANTS_DOMAIN_VERIFICATION = createItemKey(DOMAIN_TENANTS, DOMAIN_TENANTS_DOMAIN_VERIFICATION);

// ========== MemberRole ==========
export const TENANTS_MEMBER_ROLE_LIST = createListKey(DOMAIN_TENANTS, DOMAIN_TENANTS_MEMBER_ROLE);
export const TENANTS_MEMBER_ROLE = createItemKey(DOMAIN_TENANTS, DOMAIN_TENANTS_MEMBER_ROLE);

// ========== MemberGroup ==========
export const TENANTS_MEMBER_GROUP_LIST = createListKey(DOMAIN_TENANTS, DOMAIN_TENANTS_MEMBER_GROUP);
export const TENANTS_MEMBER_GROUP = createItemKey(DOMAIN_TENANTS, DOMAIN_TENANTS_MEMBER_GROUP);

// ========== MemberAppRole ==========
export const TENANTS_MEMBER_APP_ROLE_LIST = createListKey(DOMAIN_TENANTS, DOMAIN_TENANTS_MEMBER_APP_ROLE);
export const TENANTS_MEMBER_APP_ROLE = createItemKey(DOMAIN_TENANTS, DOMAIN_TENANTS_MEMBER_APP_ROLE);

