import type { QueryKey } from "@tanstack/react-query";
import { DOMAIN_TENANTS, DOMAIN_TENANTS_TENANT, DOMAIN_TENANTS_GROUP, DOMAIN_TENANTS_MEMBER, DOMAIN_TENANTS_INVITATION, DOMAIN_TENANTS_TENANT_APP, DOMAIN_TENANTS_TENANT_SETTING, DOMAIN_TENANTS_DOMAIN_VERIFICATION, DOMAIN_TENANTS_MEMBER_ROLE, DOMAIN_TENANTS_MEMBER_GROUP, DOMAIN_TENANTS_MEMBER_APP_ROLE } from "./domain.key";
import { CACHE_ITEM, CACHE_LIST } from "./cache.key";

/**
 * Tenants 相关的 Query Key 常量
 */

// ========== Tenant 相关 ==========
export const TENANTS_TENANT_LIST = [DOMAIN_TENANTS, CACHE_LIST, DOMAIN_TENANTS_TENANT];
export const TENANTS_TENANT = (item: string): QueryKey => [DOMAIN_TENANTS, CACHE_ITEM, DOMAIN_TENANTS_TENANT, item];

// ========== Group 相关 ==========
export const TENANTS_GROUP_LIST = [DOMAIN_TENANTS, CACHE_LIST, DOMAIN_TENANTS_GROUP];
export const TENANTS_GROUP = (item: string): QueryKey => [DOMAIN_TENANTS, CACHE_ITEM, DOMAIN_TENANTS_GROUP, item];

// ========== Member 相关 ==========
export const TENANTS_MEMBER_LIST = [DOMAIN_TENANTS, CACHE_LIST, DOMAIN_TENANTS_MEMBER];
export const TENANTS_MEMBER = (item: string): QueryKey => [DOMAIN_TENANTS, CACHE_ITEM, DOMAIN_TENANTS_MEMBER, item];

// ========== Invitation 相关 ==========
export const TENANTS_INVITATION_LIST = [DOMAIN_TENANTS, CACHE_LIST, DOMAIN_TENANTS_INVITATION];
export const TENANTS_INVITATION = (item: string): QueryKey => [DOMAIN_TENANTS, CACHE_ITEM, DOMAIN_TENANTS_INVITATION, item];

// ========== TenantApp 相关 ==========
export const TENANTS_TENANT_APP_LIST = [DOMAIN_TENANTS, CACHE_LIST, DOMAIN_TENANTS_TENANT_APP];
export const TENANTS_TENANT_APP = (item: string): QueryKey => [DOMAIN_TENANTS, CACHE_ITEM, DOMAIN_TENANTS_TENANT_APP, item];

// ========== TenantSetting 相关 ==========
export const TENANTS_TENANT_SETTING_LIST = [DOMAIN_TENANTS, CACHE_LIST, DOMAIN_TENANTS_TENANT_SETTING];
export const TENANTS_TENANT_SETTING = (item: string): QueryKey => [DOMAIN_TENANTS, CACHE_ITEM, DOMAIN_TENANTS_TENANT_SETTING, item];

// ========== DomainVerification 相关 ==========
export const TENANTS_DOMAIN_VERIFICATION_LIST = [DOMAIN_TENANTS, CACHE_LIST, DOMAIN_TENANTS_DOMAIN_VERIFICATION];
export const TENANTS_DOMAIN_VERIFICATION = (item: string): QueryKey => [DOMAIN_TENANTS, CACHE_ITEM, DOMAIN_TENANTS_DOMAIN_VERIFICATION, item];

// ========== MemberRole 相关 ==========
export const TENANTS_MEMBER_ROLE_LIST = [DOMAIN_TENANTS, CACHE_LIST, DOMAIN_TENANTS_MEMBER_ROLE];
export const TENANTS_MEMBER_ROLE = (item: string): QueryKey => [DOMAIN_TENANTS, CACHE_ITEM, DOMAIN_TENANTS_MEMBER_ROLE, item];

// ========== MemberGroup 相关 ==========
export const TENANTS_MEMBER_GROUP_LIST = [DOMAIN_TENANTS, CACHE_LIST, DOMAIN_TENANTS_MEMBER_GROUP];
export const TENANTS_MEMBER_GROUP = (item: string): QueryKey => [DOMAIN_TENANTS, CACHE_ITEM, DOMAIN_TENANTS_MEMBER_GROUP, item];

// ========== MemberAppRole 相关 ==========
export const TENANTS_MEMBER_APP_ROLE_LIST = [DOMAIN_TENANTS, CACHE_LIST, DOMAIN_TENANTS_MEMBER_APP_ROLE];
export const TENANTS_MEMBER_APP_ROLE = (item: string): QueryKey => [DOMAIN_TENANTS, CACHE_ITEM, DOMAIN_TENANTS_MEMBER_APP_ROLE, item];

/**
 * 用于 useCacheInvalidationEvents.ts 的 query key 前缀
 */
export const TENANTS_QUERY_KEY_PREFIXES = {
  TENANTS: [DOMAIN_TENANTS, CACHE_LIST, DOMAIN_TENANTS_TENANT],
  TENANT: [DOMAIN_TENANTS, CACHE_ITEM, DOMAIN_TENANTS_TENANT],
  GROUPS: [DOMAIN_TENANTS, CACHE_LIST, DOMAIN_TENANTS_GROUP],
  GROUP: [DOMAIN_TENANTS, CACHE_ITEM, DOMAIN_TENANTS_GROUP],
  MEMBERS: [DOMAIN_TENANTS, CACHE_LIST, DOMAIN_TENANTS_MEMBER],
  MEMBER: [DOMAIN_TENANTS, CACHE_ITEM, DOMAIN_TENANTS_MEMBER],
  INVITATIONS: [DOMAIN_TENANTS, CACHE_LIST, DOMAIN_TENANTS_INVITATION],
  INVITATION: [DOMAIN_TENANTS, CACHE_ITEM, DOMAIN_TENANTS_INVITATION],
  TENANT_APPS: [DOMAIN_TENANTS, CACHE_LIST, DOMAIN_TENANTS_TENANT_APP],
  TENANT_APP: [DOMAIN_TENANTS, CACHE_ITEM, DOMAIN_TENANTS_TENANT_APP],
  TENANT_SETTINGS: [DOMAIN_TENANTS, CACHE_LIST, DOMAIN_TENANTS_TENANT_SETTING],
  TENANT_SETTING: [DOMAIN_TENANTS, CACHE_ITEM, DOMAIN_TENANTS_TENANT_SETTING],
  DOMAIN_VERIFICATIONS: [DOMAIN_TENANTS, CACHE_LIST, DOMAIN_TENANTS_DOMAIN_VERIFICATION],
  DOMAIN_VERIFICATION: [DOMAIN_TENANTS, CACHE_ITEM, DOMAIN_TENANTS_DOMAIN_VERIFICATION],
  MEMBER_ROLES: [DOMAIN_TENANTS, CACHE_LIST, DOMAIN_TENANTS_MEMBER_ROLE],
  MEMBER_ROLE: [DOMAIN_TENANTS, CACHE_ITEM, DOMAIN_TENANTS_MEMBER_ROLE],
  MEMBER_GROUPS: [DOMAIN_TENANTS, CACHE_LIST, DOMAIN_TENANTS_MEMBER_GROUP],
  MEMBER_GROUP: [DOMAIN_TENANTS, CACHE_ITEM, DOMAIN_TENANTS_MEMBER_GROUP],
  MEMBER_APP_ROLES: [DOMAIN_TENANTS, CACHE_LIST, DOMAIN_TENANTS_MEMBER_APP_ROLE],
  MEMBER_APP_ROLE: [DOMAIN_TENANTS, CACHE_ITEM, DOMAIN_TENANTS_MEMBER_APP_ROLE],
};
