// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type UserBadge struct {
	ID          uuid.UUID `gorm:"type:uuid;primaryKey"`
	UserID      uuid.UUID `gorm:"type:uuid;index:idx_user_badges_user_id;uniqueIndex:user_badges_user_id_badge_id_key,priority:1"`
	BadgeID     uuid.UUID `gorm:"type:uuid;index:idx_user_badges_badge_id;uniqueIndex:user_badges_user_id_badge_id_key,priority:2"`
	Description *string   `gorm:"type:text"`
	Level       *int      `gorm:"type:integer"`
	EarnedAt    time.Time `gorm:"type:timestamp;index:idx_user_badges_earned_at"`
	CreatedAt   time.Time `gorm:"autoCreateTime"`
	UpdatedAt   time.Time `gorm:"autoUpdateTime"`
}

func (UserBadge) TableName() string { return "directory.user_badges" }

func (m *UserBadge) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var UserBadgeCols = struct {
	ID, UserID, BadgeID, Description, Level, EarnedAt, CreatedAt,
	UpdatedAt string
}{
	ID:          "id",
	UserID:      "user_id",
	BadgeID:     "badge_id",
	Description: "description",
	Level:       "level",
	EarnedAt:    "earned_at",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}

const (
	UserBadgePk                 = "user_badges_pkey"
	UserBadgeUkUserIdBadgeIdKey = "user_badges_user_id_badge_id_key"
	UserBadgeFkBadgeIdFkey      = "user_badges_badge_id_fkey"
	UserBadgeFkUserIdFkey       = "user_badges_user_id_fkey"
)
