// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type UserPhone struct {
	ID                    uuid.UUID      `gorm:"type:uuid;primaryKey"`
	UserID                uuid.UUID      `gorm:"type:uuid;index:idx_user_phones_is_primary,priority:1;index:idx_user_phones_user_id"`
	Phone                 string         `gorm:"type:varchar(20);index:idx_user_phones_phone;uniqueIndex:user_phones_phone_key"`
	CountryCode           *string        `gorm:"type:varchar(10)"`
	IsPrimary             bool           `gorm:"type:boolean;index:idx_user_phones_is_primary,priority:2"`
	IsVerified            bool           `gorm:"type:boolean;index:idx_user_phones_is_verified"`
	VerifiedAt            *time.Time     `gorm:"type:timestamp"`
	VerificationCode      *string        `gorm:"type:varchar(10)"`
	VerificationExpiresAt *time.Time     `gorm:"type:timestamp"`
	CreatedAt             time.Time      `gorm:"autoCreateTime"`
	UpdatedAt             time.Time      `gorm:"autoUpdateTime"`
	DeletedAt             gorm.DeletedAt `gorm:"index"`
}

func (UserPhone) TableName() string { return "directory.user_phones" }

func (m *UserPhone) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var UserPhoneCols = struct {
	ID, UserID, Phone, CountryCode, IsPrimary, IsVerified, VerifiedAt,
	VerificationCode, VerificationExpiresAt, CreatedAt, UpdatedAt, DeletedAt string
}{
	ID:                    "id",
	UserID:                "user_id",
	Phone:                 "phone",
	CountryCode:           "country_code",
	IsPrimary:             "is_primary",
	IsVerified:            "is_verified",
	VerifiedAt:            "verified_at",
	VerificationCode:      "verification_code",
	VerificationExpiresAt: "verification_expires_at",
	CreatedAt:             "created_at",
	UpdatedAt:             "updated_at",
	DeletedAt:             "deleted_at",
}

const (
	UserPhonePk           = "user_phones_pkey"
	UserPhoneUkPhoneKey   = "user_phones_phone_key"
	UserPhoneFkUserIdFkey = "user_phones_user_id_fkey"
)
