// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxid/enums"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type User struct {
	ID          uuid.UUID                 `gorm:"type:uuid;primaryKey"`
	TenantID    uuid.UUID                 `gorm:"type:uuid"`
	Username    string                    `gorm:"type:varchar(50);index:idx_users_username;uniqueIndex:users_username_key"`
	Status      enums.DirectoryUserStatus `gorm:"type:user_status;index:idx_users_status"`
	IsVerified  bool                      `gorm:"type:boolean"`
	LastLoginAt *time.Time                `gorm:"type:timestamp;index:idx_users_last_login_at"`
	CreatedAt   time.Time                 `gorm:"autoCreateTime"`
	UpdatedAt   time.Time                 `gorm:"autoUpdateTime"`
	DeletedAt   gorm.DeletedAt            `gorm:"index"`
}

func (User) TableName() string { return "directory.users" }

func (m *User) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var UserCols = struct {
	ID, TenantID, Username, Status, IsVerified, LastLoginAt, CreatedAt,
	UpdatedAt, DeletedAt string
}{
	ID:          "id",
	TenantID:    "tenant_id",
	Username:    "username",
	Status:      "status",
	IsVerified:  "is_verified",
	LastLoginAt: "last_login_at",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
	DeletedAt:   "deleted_at",
}

const (
	UserPk            = "users_pkey"
	UserUkUsernameKey = "users_username_key"
)
