// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type UserImage struct {
	ID           uuid.UUID      `gorm:"type:uuid;primaryKey"`
	UserID       uuid.UUID      `gorm:"type:uuid;index:idx_user_images_display_order,priority:1;index:idx_user_images_user_id;uniqueIndex:idx_user_images_user_image_unique,priority:1;index:idx_user_images_user_order,priority:1"`
	ImageID      uuid.UUID      `gorm:"type:uuid;index:idx_user_images_image_id;uniqueIndex:idx_user_images_user_image_unique,priority:2"`
	DisplayOrder int            `gorm:"type:integer;index:idx_user_images_display_order,priority:2;index:idx_user_images_user_order,priority:2"`
	CreatedAt    time.Time      `gorm:"autoCreateTime"`
	UpdatedAt    time.Time      `gorm:"autoUpdateTime"`
	DeletedAt    gorm.DeletedAt `gorm:"index"`
}

func (UserImage) TableName() string { return "directory.user_images" }

func (m *UserImage) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var UserImageCols = struct {
	ID, UserID, ImageID, DisplayOrder, CreatedAt, UpdatedAt, DeletedAt string
}{
	ID:           "id",
	UserID:       "user_id",
	ImageID:      "image_id",
	DisplayOrder: "display_order",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
	DeletedAt:    "deleted_at",
}

const (
	UserImagePk                = "user_images_pkey"
	UserImageUkUserImageUnique = "idx_user_images_user_image_unique"
	UserImageFkUserIdFkey      = "user_images_user_id_fkey"
)
