// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
)

type UserAvatar struct {
	UserID    uuid.UUID `gorm:"type:uuid;primaryKey"`
	ImageID   uuid.UUID `gorm:"type:uuid;index:idx_user_avatars_image_id"`
	CreatedAt time.Time `gorm:"autoCreateTime"`
	UpdatedAt time.Time `gorm:"autoUpdateTime"`
}

func (UserAvatar) TableName() string { return "directory.user_avatars" }

var UserAvatarCols = struct {
	UserID, ImageID, CreatedAt, UpdatedAt string
}{
	UserID:    "user_id",
	ImageID:   "image_id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

const (
	UserAvatarPk           = "user_avatars_pkey"
	UserAvatarFkUserIdFkey = "user_avatars_user_id_fkey"
)
