// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

type UserPreference struct {
	ID            uuid.UUID       `gorm:"type:uuid;primaryKey"`
	UserID        uuid.UUID       `gorm:"type:uuid;index:idx_user_preferences_user_id;uniqueIndex:user_preferences_user_id_key"`
	Theme         *string         `gorm:"type:varchar(50)"`
	Language      *string         `gorm:"type:varchar(10)"`
	Timezone      *string         `gorm:"type:varchar(50)"`
	Notifications *datatypes.JSON `gorm:"type:jsonb"`
	Privacy       *datatypes.JSON `gorm:"type:jsonb"`
	Display       *datatypes.JSON `gorm:"type:jsonb"`
	Other         *datatypes.JSON `gorm:"type:jsonb"`
	CreatedAt     time.Time       `gorm:"autoCreateTime"`
	UpdatedAt     time.Time       `gorm:"autoUpdateTime"`
	DeletedAt     gorm.DeletedAt  `gorm:"index"`
}

func (UserPreference) TableName() string { return "directory.user_preferences" }

func (m *UserPreference) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var UserPreferenceCols = struct {
	ID, UserID, Theme, Language, Timezone, Notifications, Privacy,
	Display, Other, CreatedAt, UpdatedAt, DeletedAt string
}{
	ID:            "id",
	UserID:        "user_id",
	Theme:         "theme",
	Language:      "language",
	Timezone:      "timezone",
	Notifications: "notifications",
	Privacy:       "privacy",
	Display:       "display",
	Other:         "other",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
	DeletedAt:     "deleted_at",
}

const (
	UserPreferencePk           = "user_preferences_pkey"
	UserPreferenceUkUserIdKey  = "user_preferences_user_id_key"
	UserPreferenceFkUserIdFkey = "user_preferences_user_id_fkey"
)
