// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type UserEmail struct {
	ID                uuid.UUID      `gorm:"type:uuid;primaryKey"`
	UserID            uuid.UUID      `gorm:"type:uuid;index:idx_user_emails_is_primary,priority:1;index:idx_user_emails_user_id"`
	Email             string         `gorm:"type:varchar(255);index:idx_user_emails_email;uniqueIndex:user_emails_email_key"`
	IsPrimary         bool           `gorm:"type:boolean;index:idx_user_emails_is_primary,priority:2"`
	IsVerified        bool           `gorm:"type:boolean;index:idx_user_emails_is_verified"`
	VerifiedAt        *time.Time     `gorm:"type:timestamp"`
	VerificationToken *string        `gorm:"type:varchar(255)"`
	CreatedAt         time.Time      `gorm:"autoCreateTime"`
	UpdatedAt         time.Time      `gorm:"autoUpdateTime"`
	DeletedAt         gorm.DeletedAt `gorm:"index"`
}

func (UserEmail) TableName() string { return "directory.user_emails" }

func (m *UserEmail) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var UserEmailCols = struct {
	ID, UserID, Email, IsPrimary, IsVerified, VerifiedAt, VerificationToken,
	CreatedAt, UpdatedAt, DeletedAt string
}{
	ID:                "id",
	UserID:            "user_id",
	Email:             "email",
	IsPrimary:         "is_primary",
	IsVerified:        "is_verified",
	VerifiedAt:        "verified_at",
	VerificationToken: "verification_token",
	CreatedAt:         "created_at",
	UpdatedAt:         "updated_at",
	DeletedAt:         "deleted_at",
}

const (
	UserEmailPk           = "user_emails_pkey"
	UserEmailUkEmailKey   = "user_emails_email_key"
	UserEmailFkUserIdFkey = "user_emails_user_id_fkey"
)
