// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type ActionRequirement struct {
	ID           uuid.UUID `gorm:"type:uuid;primaryKey"`
	ActionID     uuid.UUID `gorm:"type:uuid;uniqueIndex:action_requirements_action_id_permission_id_key,priority:1;index:idx_action_requirements_action_id;index:idx_action_requirements_action_permission,priority:1"`
	PermissionID uuid.UUID `gorm:"type:uuid;uniqueIndex:action_requirements_action_id_permission_id_key,priority:2;index:idx_action_requirements_action_permission,priority:2;index:idx_action_requirements_permission_id"`
	CreatedAt    time.Time `gorm:"autoCreateTime"`
}

func (ActionRequirement) TableName() string { return "access.action_requirements" }

func (m *ActionRequirement) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var ActionRequirementCols = struct {
	ID, ActionID, PermissionID, CreatedAt string
}{
	ID:           "id",
	ActionID:     "action_id",
	PermissionID: "permission_id",
	CreatedAt:    "created_at",
}

const (
	ActionRequirementPk                        = "action_requirements_pkey"
	ActionRequirementUkActionIdPermissionIdKey = "action_requirements_action_id_permission_id_key"
	ActionRequirementFkActionIdFkey            = "action_requirements_action_id_fkey"
	ActionRequirementFkPermissionIdFkey        = "action_requirements_permission_id_fkey"
)
