// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type ApplicationRoleAssignment struct {
	ID                uuid.UUID  `gorm:"type:uuid;primaryKey"`
	UserID            uuid.UUID  `gorm:"type:uuid;uniqueIndex:application_role_assignments_user_id_application_id_key,priority:1;index:idx_application_role_assignments_user_id"`
	ApplicationID     uuid.UUID  `gorm:"type:uuid;uniqueIndex:application_role_assignments_user_id_application_id_key,priority:2;index:idx_application_role_assignments_application_id"`
	ApplicationRoleID uuid.UUID  `gorm:"type:uuid;index:idx_application_role_assignments_application_role_id"`
	AssignedAt        time.Time  `gorm:"type:timestamp"`
	AssignedBy        *uuid.UUID `gorm:"type:uuid"`
}

func (ApplicationRoleAssignment) TableName() string { return "access.application_role_assignments" }

func (m *ApplicationRoleAssignment) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var ApplicationRoleAssignmentCols = struct {
	ID, UserID, ApplicationID, ApplicationRoleID, AssignedAt, AssignedBy string
}{
	ID:                "id",
	UserID:            "user_id",
	ApplicationID:     "application_id",
	ApplicationRoleID: "application_role_id",
	AssignedAt:        "assigned_at",
	AssignedBy:        "assigned_by",
}

const (
	ApplicationRoleAssignmentPk                       = "application_role_assignments_pkey"
	ApplicationRoleAssignmentUkUserIdApplicationIdKey = "application_role_assignments_user_id_application_id_key"
)
