// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type ApplicationRole struct {
	ID            uuid.UUID `gorm:"type:uuid;primaryKey"`
	ApplicationID uuid.UUID `gorm:"type:uuid;uniqueIndex:application_roles_application_id_role_key_key,priority:1;index:idx_application_roles_application_id"`
	RoleKey       string    `gorm:"type:varchar(32);uniqueIndex:application_roles_application_id_role_key_key,priority:2;index:idx_application_roles_role_key"`
	Name          *string   `gorm:"type:varchar(255)"`
	CreatedAt     time.Time `gorm:"autoCreateTime"`
}

func (ApplicationRole) TableName() string { return "access.application_roles" }

func (m *ApplicationRole) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var ApplicationRoleCols = struct {
	ID, ApplicationID, RoleKey, Name, CreatedAt string
}{
	ID:            "id",
	ApplicationID: "application_id",
	RoleKey:       "role_key",
	Name:          "name",
	CreatedAt:     "created_at",
}

const (
	ApplicationRolePk                        = "application_roles_pkey"
	ApplicationRoleUkApplicationIdRoleKeyKey = "application_roles_application_id_role_key_key"
)
