// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxid/enums"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type Grant struct {
	ID           uuid.UUID               `gorm:"type:uuid;primaryKey"`
	SubjectType  enums.AccessSubjectType `gorm:"type:subject_type;index:idx_grants_subject,priority:1;index:idx_grants_subject_tenant,priority:1"`
	SubjectID    uuid.UUID               `gorm:"type:uuid;index:idx_grants_subject,priority:2;index:idx_grants_subject_tenant,priority:2"`
	GrantType    enums.AccessGrantType   `gorm:"type:grant_type;index:idx_grants_grant_type,priority:1"`
	GrantRefID   uuid.UUID               `gorm:"type:uuid;index:idx_grants_grant_type,priority:2"`
	TenantID     *uuid.UUID              `gorm:"type:uuid;index:idx_grants_subject_tenant,priority:3;index:idx_grants_tenant_id"`
	AppID        *uuid.UUID              `gorm:"type:uuid;index:idx_grants_app_id"`
	ResourceType *string                 `gorm:"type:varchar(100);index:idx_grants_resource,priority:1"`
	ResourceID   *uuid.UUID              `gorm:"type:uuid;index:idx_grants_resource,priority:2"`
	Effect       enums.AccessGrantEffect `gorm:"type:grant_effect;index:idx_grants_effect"`
	ExpiresAt    *time.Time              `gorm:"type:timestamp;index:idx_grants_expires_at"`
	CreatedAt    time.Time               `gorm:"autoCreateTime"`
	CreatedBy    *uuid.UUID              `gorm:"type:uuid"`
	RevokedAt    *time.Time              `gorm:"type:timestamp;index:idx_grants_revoked_at"`
	RevokedBy    *uuid.UUID              `gorm:"type:uuid"`
	RevokeReason *string                 `gorm:"type:text"`
}

func (Grant) TableName() string { return "access.grants" }

func (m *Grant) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var GrantCols = struct {
	ID, SubjectType, SubjectID, GrantType, GrantRefID, TenantID, AppID,
	ResourceType, ResourceID, Effect, ExpiresAt, CreatedAt, CreatedBy, RevokedAt,
	RevokedBy, RevokeReason string
}{
	ID:           "id",
	SubjectType:  "subject_type",
	SubjectID:    "subject_id",
	GrantType:    "grant_type",
	GrantRefID:   "grant_ref_id",
	TenantID:     "tenant_id",
	AppID:        "app_id",
	ResourceType: "resource_type",
	ResourceID:   "resource_id",
	Effect:       "effect",
	ExpiresAt:    "expires_at",
	CreatedAt:    "created_at",
	CreatedBy:    "created_by",
	RevokedAt:    "revoked_at",
	RevokedBy:    "revoked_by",
	RevokeReason: "revoke_reason",
}

const (
	GrantPk = "grants_pkey"
)
