// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type Permission struct {
	ID          uuid.UUID      `gorm:"type:uuid;primaryKey"`
	Key         string         `gorm:"type:varchar(255);index:idx_permissions_key;uniqueIndex:permissions_key_key"`
	Name        string         `gorm:"type:varchar(255)"`
	Description *string        `gorm:"type:text"`
	IsSystem    bool           `gorm:"type:boolean;index:idx_permissions_is_system"`
	CreatedAt   time.Time      `gorm:"autoCreateTime"`
	UpdatedAt   time.Time      `gorm:"autoUpdateTime"`
	DeletedAt   gorm.DeletedAt `gorm:"index"`
}

func (Permission) TableName() string { return "access.permissions" }

func (m *Permission) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var PermissionCols = struct {
	ID, Key, Name, Description, IsSystem, CreatedAt, UpdatedAt,
	DeletedAt string
}{
	ID:          "id",
	Key:         "key",
	Name:        "name",
	Description: "description",
	IsSystem:    "is_system",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
	DeletedAt:   "deleted_at",
}

const (
	PermissionPk       = "permissions_pkey"
	PermissionUkKeyKey = "permissions_key_key"
)
