// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type RolePermission struct {
	ID           uuid.UUID  `gorm:"type:uuid;primaryKey"`
	RoleID       uuid.UUID  `gorm:"type:uuid;index:idx_role_permissions_role_id;index:idx_role_permissions_role_permission,priority:1;uniqueIndex:role_permissions_role_id_permission_id_key,priority:1"`
	PermissionID uuid.UUID  `gorm:"type:uuid;index:idx_role_permissions_permission_id;index:idx_role_permissions_role_permission,priority:2;uniqueIndex:role_permissions_role_id_permission_id_key,priority:2"`
	CreatedAt    time.Time  `gorm:"autoCreateTime"`
	CreatedBy    *uuid.UUID `gorm:"type:uuid"`
}

func (RolePermission) TableName() string { return "access.role_permissions" }

func (m *RolePermission) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var RolePermissionCols = struct {
	ID, RoleID, PermissionID, CreatedAt, CreatedBy string
}{
	ID:           "id",
	RoleID:       "role_id",
	PermissionID: "permission_id",
	CreatedAt:    "created_at",
	CreatedBy:    "created_by",
}

const (
	RolePermissionPk                      = "role_permissions_pkey"
	RolePermissionUkRoleIdPermissionIdKey = "role_permissions_role_id_permission_id_key"
	RolePermissionFkPermissionIdFkey      = "role_permissions_permission_id_fkey"
	RolePermissionFkRoleIdFkey            = "role_permissions_role_id_fkey"
)
