// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxid/enums"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type Role struct {
	ID          uuid.UUID             `gorm:"type:uuid;primaryKey"`
	Key         string                `gorm:"type:varchar(255);index:idx_roles_key;uniqueIndex:roles_key_key"`
	Name        string                `gorm:"type:varchar(255)"`
	Description *string               `gorm:"type:text"`
	ScopeType   enums.AccessScopeType `gorm:"type:scope_type;index:idx_roles_scope_type"`
	IsSystem    bool                  `gorm:"type:boolean;index:idx_roles_is_system"`
	CreatedAt   time.Time             `gorm:"autoCreateTime"`
	UpdatedAt   time.Time             `gorm:"autoUpdateTime"`
	DeletedAt   gorm.DeletedAt        `gorm:"index"`
}

func (Role) TableName() string { return "access.roles" }

func (m *Role) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var RoleCols = struct {
	ID, Key, Name, Description, ScopeType, IsSystem, CreatedAt,
	UpdatedAt, DeletedAt string
}{
	ID:          "id",
	Key:         "key",
	Name:        "name",
	Description: "description",
	ScopeType:   "scope_type",
	IsSystem:    "is_system",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
	DeletedAt:   "deleted_at",
}

const (
	RolePk       = "roles_pkey"
	RoleUkKeyKey = "roles_key_key"
)
