// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type ScopePermission struct {
	ID           uuid.UUID `gorm:"type:uuid;primaryKey"`
	Scope        string    `gorm:"type:varchar(255);index:idx_scope_permissions_scope;index:idx_scope_permissions_scope_permission,priority:1;uniqueIndex:scope_permissions_scope_permission_id_key,priority:1"`
	PermissionID uuid.UUID `gorm:"type:uuid;index:idx_scope_permissions_permission_id;index:idx_scope_permissions_scope_permission,priority:2;uniqueIndex:scope_permissions_scope_permission_id_key,priority:2"`
	CreatedAt    time.Time `gorm:"autoCreateTime"`
}

func (ScopePermission) TableName() string { return "access.scope_permissions" }

func (m *ScopePermission) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var ScopePermissionCols = struct {
	ID, Scope, PermissionID, CreatedAt string
}{
	ID:           "id",
	Scope:        "scope",
	PermissionID: "permission_id",
	CreatedAt:    "created_at",
}

const (
	ScopePermissionPk                     = "scope_permissions_pkey"
	ScopePermissionUkScopePermissionIdKey = "scope_permissions_scope_permission_id_key"
	ScopePermissionFkPermissionIdFkey     = "scope_permissions_permission_id_fkey"
	ScopePermissionFkScopeFkey            = "scope_permissions_scope_fkey"
)
