// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"gorm.io/gorm"
)

type Scope struct {
	Scope       string         `gorm:"type:varchar(255);primaryKey"`
	Description *string        `gorm:"type:text"`
	IsSystem    bool           `gorm:"type:boolean;index:idx_scopes_is_system"`
	CreatedAt   time.Time      `gorm:"autoCreateTime"`
	UpdatedAt   time.Time      `gorm:"autoUpdateTime"`
	DeletedAt   gorm.DeletedAt `gorm:"index"`
}

func (Scope) TableName() string { return "access.scopes" }

var ScopeCols = struct {
	Scope, Description, IsSystem, CreatedAt, UpdatedAt, DeletedAt string
}{
	Scope:       "scope",
	Description: "description",
	IsSystem:    "is_system",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
	DeletedAt:   "deleted_at",
}

const (
	ScopePk = "scopes_pkey"
)
