// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
)

type SuperAdmin struct {
	UserID    uuid.UUID `gorm:"type:uuid;primaryKey;index:idx_super_admins_user_id"`
	CreatedAt time.Time `gorm:"autoCreateTime"`
}

func (SuperAdmin) TableName() string { return "access.super_admins" }

var SuperAdminCols = struct {
	UserID, CreatedAt string
}{
	UserID:    "user_id",
	CreatedAt: "created_at",
}

const (
	SuperAdminPk = "super_admins_pkey"
)
