// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type TenantRole struct {
	ID        uuid.UUID `gorm:"type:uuid;primaryKey"`
	TenantID  uuid.UUID `gorm:"type:uuid;index:idx_tenant_roles_tenant_id;uniqueIndex:tenant_roles_tenant_id_role_key_key,priority:1"`
	RoleKey   string    `gorm:"type:varchar(32);index:idx_tenant_roles_role_key;uniqueIndex:tenant_roles_tenant_id_role_key_key,priority:2"`
	Name      *string   `gorm:"type:varchar(255)"`
	CreatedAt time.Time `gorm:"autoCreateTime"`
}

func (TenantRole) TableName() string { return "access.tenant_roles" }

func (m *TenantRole) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var TenantRoleCols = struct {
	ID, TenantID, RoleKey, Name, CreatedAt string
}{
	ID:        "id",
	TenantID:  "tenant_id",
	RoleKey:   "role_key",
	Name:      "name",
	CreatedAt: "created_at",
}

const (
	TenantRolePk                   = "tenant_roles_pkey"
	TenantRoleUkTenantIdRoleKeyKey = "tenant_roles_tenant_id_role_key_key"
)
