// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type TenantRoleAssignment struct {
	ID           uuid.UUID  `gorm:"type:uuid;primaryKey"`
	UserID       uuid.UUID  `gorm:"type:uuid;index:idx_tenant_role_assignments_user_id;uniqueIndex:tenant_role_assignments_user_id_tenant_id_key,priority:1"`
	TenantID     uuid.UUID  `gorm:"type:uuid;index:idx_tenant_role_assignments_tenant_id;uniqueIndex:tenant_role_assignments_user_id_tenant_id_key,priority:2"`
	TenantRoleID uuid.UUID  `gorm:"type:uuid;index:idx_tenant_role_assignments_tenant_role_id"`
	AssignedAt   time.Time  `gorm:"type:timestamp"`
	AssignedBy   *uuid.UUID `gorm:"type:uuid"`
}

func (TenantRoleAssignment) TableName() string { return "access.tenant_role_assignments" }

func (m *TenantRoleAssignment) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var TenantRoleAssignmentCols = struct {
	ID, UserID, TenantID, TenantRoleID, AssignedAt, AssignedBy string
}{
	ID:           "id",
	UserID:       "user_id",
	TenantID:     "tenant_id",
	TenantRoleID: "tenant_role_id",
	AssignedAt:   "assigned_at",
	AssignedBy:   "assigned_by",
}

const (
	TenantRoleAssignmentPk                  = "tenant_role_assignments_pkey"
	TenantRoleAssignmentUkUserIdTenantIdKey = "tenant_role_assignments_user_id_tenant_id_key"
)
