// Code generated by gen-enums. DO NOT EDIT.

package enums

type UserStatus string

const (
	UserStatusPending  UserStatus = "pending"
	UserStatusActive   UserStatus = "active"
	UserStatusDeactive UserStatus = "deactive"
)
