// Code generated by gen-views. DO NOT EDIT.
package views

import (
	"time"

	"github.com/google/uuid"
)

// ImageTypeStats represents the image.image_type_stats database view
// Purpose: Provides aggregated statistics for each image type (counts, public/private breakdown)
// Use Case: Admin dashboards, analytics, reports, monitoring image usage by type
type ImageTypeStats struct {
	ID             uuid.UUID  `gorm:"column:id;->"`
	TypeKey        string     `gorm:"column:type_key;->"`
	Description    *string    `gorm:"column:description;->"`
	MaxWidth       *int       `gorm:"column:max_width;->"`
	MaxHeight      *int       `gorm:"column:max_height;->"`
	AspectRatio    *string    `gorm:"column:aspect_ratio;->"`
	IsSystem       *bool      `gorm:"column:is_system;->"`
	TotalImages    int64      `gorm:"column:total_images;->"`
	PublicImages   int64      `gorm:"column:public_images;->"`
	PrivateImages  int64      `gorm:"column:private_images;->"`
	FirstCreatedAt *time.Time `gorm:"column:first_created_at;->"`
	LastCreatedAt  *time.Time `gorm:"column:last_created_at;->"`
}

func (ImageTypeStats) TableName() string {
	return "image.image_type_stats"
}

var ImageTypeStatsCols = struct {
	ID, TypeKey, Description, MaxWidth, MaxHeight, AspectRatio, IsSystem,
	TotalImages, PublicImages, PrivateImages, FirstCreatedAt, LastCreatedAt string
}{
	ID:             "id",
	TypeKey:        "type_key",
	Description:    "description",
	MaxWidth:       "max_width",
	MaxHeight:      "max_height",
	AspectRatio:    "aspect_ratio",
	IsSystem:       "is_system",
	TotalImages:    "total_images",
	PublicImages:   "public_images",
	PrivateImages:  "private_images",
	FirstCreatedAt: "first_created_at",
	LastCreatedAt:  "last_created_at",
}

