// Code generated by gen-views. DO NOT EDIT.
package views

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
)

// ImageListItem represents the image.image_list_item database view
// Purpose: Provides a flattened view of images with type information and primary thumbnail URL
// Use Case: API endpoints for listing images, admin dashboards, gallery views
type ImageListItem struct {
	ID               uuid.UUID       `gorm:"column:id;->"`
	TypeID           *uuid.UUID      `gorm:"column:type_id;->"`
	TypeKey          *string         `gorm:"column:type_key;->"`
	TypeDescription  *string         `gorm:"column:type_description;->"`
	UserID           *uuid.UUID      `gorm:"column:user_id;->"`
	SourceDomain     *string         `gorm:"column:source_domain;->"`
	Filename         string          `gorm:"column:filename;->"`
	OriginalFilename string          `gorm:"column:original_filename;->"`
	MimeType         string          `gorm:"column:mime_type;->"`
	OriginalSize     int64           `gorm:"column:original_size;->"`
	OriginalWidth    *int            `gorm:"column:original_width;->"`
	OriginalHeight   *int            `gorm:"column:original_height;->"`
	StoragePath      string          `gorm:"column:storage_path;->"`
	OriginalURL      *string         `gorm:"column:original_url;->"`
	IsPublic         bool            `gorm:"column:is_public;->"`
	ThumbnailURL     *string         `gorm:"column:thumbnail_url;->"`
	ThumbnailWidth   *int            `gorm:"column:thumbnail_width;->"`
	ThumbnailHeight  *int            `gorm:"column:thumbnail_height;->"`
	Metadata         *datatypes.JSON `gorm:"column:metadata;->"`
	CreatedAt        time.Time       `gorm:"column:created_at;->"`
	UpdatedAt        time.Time       `gorm:"column:updated_at;->"`
}

func (ImageListItem) TableName() string {
	return "image.image_list_item"
}

var ImageListItemCols = struct {
	ID, TypeID, TypeKey, TypeDescription, UserID, SourceDomain, Filename,
	OriginalFilename, MimeType, OriginalSize, OriginalWidth, OriginalHeight,
	StoragePath, OriginalURL, IsPublic, ThumbnailURL, ThumbnailWidth, ThumbnailHeight,
	Metadata, CreatedAt, UpdatedAt string
}{
	ID:               "id",
	TypeID:           "type_id",
	TypeKey:          "type_key",
	TypeDescription:  "type_description",
	UserID:           "user_id",
	SourceDomain:     "source_domain",
	Filename:         "filename",
	OriginalFilename: "original_filename",
	MimeType:         "mime_type",
	OriginalSize:     "original_size",
	OriginalWidth:    "original_width",
	OriginalHeight:   "original_height",
	StoragePath:      "storage_path",
	OriginalURL:      "original_url",
	IsPublic:         "is_public",
	ThumbnailURL:     "thumbnail_url",
	ThumbnailWidth:   "thumbnail_width",
	ThumbnailHeight:  "thumbnail_height",
	Metadata:         "metadata",
	CreatedAt:        "created_at",
	UpdatedAt:        "updated_at",
}

