// Code generated by gen-views. DO NOT EDIT.
package views

import (
	"time"

	"github.com/google/uuid"
)

type Fullaccountinformationforgerprofilesettingsview struct {
	ID                *uuid.UUID `gorm:"column:id;->"`
	LoginNotification *bool      `gorm:"column:login_notification;->"`
	CreatedAt         *time.Time `gorm:"column:created_at;->"`
	UpdatedAt         *time.Time `gorm:"column:updated_at;->"`
}

func (Fullaccountinformationforgerprofilesettingsview) TableName() string {
	return "auth.FullAccountInformationForgerProfileSettingsView"
}

var FullaccountinformationforgerprofilesettingsviewCols = struct {
	ID, LoginNotification, CreatedAt, UpdatedAt string
}{
	ID:                "id",
	LoginNotification: "login_notification",
	CreatedAt:         "created_at",
	UpdatedAt:         "updated_at",
}
