// Code generated by gen-views. DO NOT EDIT.
package views

import (
	"nfxidentity/enums"
	"time"

	"github.com/google/uuid"
)

type FullAccountInformationWithForgerProfileAccountView struct {
	AccountID      *uuid.UUID                `gorm:"column:account_id;->"`
	AccountStatus  *enums.AuthAccountStatus  `gorm:"column:account_status;->"`
	SignupPlatform *enums.AuthSignupPlatform `gorm:"column:signup_platform;->"`
	CreatedAt      *time.Time                `gorm:"column:created_at;->"`
	UpdatedAt      *time.Time                `gorm:"column:updated_at;->"`
}

func (FullAccountInformationWithForgerProfileAccountView) TableName() string {
	return "auth.FullAccountInformationWithForgerProfileAccountView"
}

var FullAccountInformationWithForgerProfileAccountViewCols = struct {
	AccountID, AccountStatus, SignupPlatform, CreatedAt, UpdatedAt string
}{
	AccountID:      "account_id",
	AccountStatus:  "account_status",
	SignupPlatform: "signup_platform",
	CreatedAt:      "created_at",
	UpdatedAt:      "updated_at",
}
