// Code generated by gen-views. DO NOT EDIT.
package views

import (
	"time"

	"github.com/google/uuid"
)

type FullAccountInformationWithForgerProfilePhoneView struct {
	ID         *uuid.UUID `gorm:"column:id;->"`
	AccountID  *uuid.UUID `gorm:"column:account_id;->"`
	Phone      *string    `gorm:"column:phone;->"`
	IsPrimary  *bool      `gorm:"column:is_primary;->"`
	VerifiedAt *time.Time `gorm:"column:verified_at;->"`
	CreatedAt  *time.Time `gorm:"column:created_at;->"`
	UpdatedAt  *time.Time `gorm:"column:updated_at;->"`
}

func (FullAccountInformationWithForgerProfilePhoneView) TableName() string {
	return "auth.FullAccountInformationWithForgerProfilePhoneView"
}

var FullAccountInformationWithForgerProfilePhoneViewCols = struct {
	ID, AccountID, Phone, IsPrimary, VerifiedAt, CreatedAt, UpdatedAt string
}{
	ID:         "id",
	AccountID:  "account_id",
	Phone:      "phone",
	IsPrimary:  "is_primary",
	VerifiedAt: "verified_at",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
}
