// Code generated by gen-views. DO NOT EDIT.
package views

import (
	"time"

	"github.com/google/uuid"
)

type FullAccountInformationWithForgerProfileBackgroundView struct {
	ID        *uuid.UUID `gorm:"column:id;->"`
	ProfileID *uuid.UUID `gorm:"column:profile_id;->"`
	ImageID   *uuid.UUID `gorm:"column:image_id;->"`
	SortOrder *int       `gorm:"column:sort_order;->"`
	CreatedAt *time.Time `gorm:"column:created_at;->"`
	UpdatedAt *time.Time `gorm:"column:updated_at;->"`
}

func (FullAccountInformationWithForgerProfileBackgroundView) TableName() string {
	return "auth.FullAccountInformationWithForgerProfileBackgroundView"
}

var FullAccountInformationWithForgerProfileBackgroundViewCols = struct {
	ID, ProfileID, ImageID, SortOrder, CreatedAt, UpdatedAt string
}{
	ID:        "id",
	ProfileID: "profile_id",
	ImageID:   "image_id",
	SortOrder: "sort_order",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}
