// Code generated by gen-views. DO NOT EDIT.
package views

import (
	"time"

	"github.com/google/uuid"
)

type FullAccountInformationWithAuthorityProfileAvatarView struct {
	ID        *uuid.UUID `gorm:"column:id;->"`
	ProfileID *uuid.UUID `gorm:"column:profile_id;->"`
	ImageID   *uuid.UUID `gorm:"column:image_id;->"`
	IsActive  *bool      `gorm:"column:is_active;->"`
	CreatedAt *time.Time `gorm:"column:created_at;->"`
	UpdatedAt *time.Time `gorm:"column:updated_at;->"`
}

func (FullAccountInformationWithAuthorityProfileAvatarView) TableName() string {
	return "auth.FullAccountInformationWithAuthorityProfileAvatarView"
}

var FullAccountInformationWithAuthorityProfileAvatarViewCols = struct {
	ID, ProfileID, ImageID, IsActive, CreatedAt, UpdatedAt string
}{
	ID:        "id",
	ProfileID: "profile_id",
	ImageID:   "image_id",
	IsActive:  "is_active",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}
