// Code generated by gen-views. DO NOT EDIT.
package views

import (
	"nfxidentity/enums"
	"time"

	"github.com/google/uuid"
)

type Listforgerprofileitem struct {
	ProfileID         *uuid.UUID                 `gorm:"column:profile_id;->"`
	AccountID         *uuid.UUID                 `gorm:"column:account_id;->"`
	ForgerRoles       *string                    `gorm:"column:forger_roles;->"`
	DisplayName       *string                    `gorm:"column:display_name;->"`
	ProfileLanguage   *enums.AuthProfileLanguage `gorm:"column:profile_language;->"`
	City              *string                    `gorm:"column:city;->"`
	Country           *string                    `gorm:"column:country;->"`
	Website           *string                    `gorm:"column:website;->"`
	Timezone          *string                    `gorm:"column:timezone;->"`
	Birthday          *time.Time                 `gorm:"column:birthday;->"`
	CreatedAt         *time.Time                 `gorm:"column:created_at;->"`
	AvatarImageID     *uuid.UUID                 `gorm:"column:avatar_image_id;->"`
	BackgroundImageID *uuid.UUID                 `gorm:"column:background_image_id;->"`
}

func (Listforgerprofileitem) TableName() string { return "auth.ListForgerProfileItems" }

var ListforgerprofileitemCols = struct {
	ProfileID, AccountID, ForgerRoles, DisplayName, ProfileLanguage, City, Country,
	Website, Timezone, Birthday, CreatedAt, AvatarImageID, BackgroundImageID string
}{
	ProfileID:         "profile_id",
	AccountID:         "account_id",
	ForgerRoles:       "forger_roles",
	DisplayName:       "display_name",
	ProfileLanguage:   "profile_language",
	City:              "city",
	Country:           "country",
	Website:           "website",
	Timezone:          "timezone",
	Birthday:          "birthday",
	CreatedAt:         "created_at",
	AvatarImageID:     "avatar_image_id",
	BackgroundImageID: "background_image_id",
}
