// Code generated by gen-views. DO NOT EDIT.
package views

import (
	"time"

	"github.com/google/uuid"
)

type Listemailitem struct {
	ID         *uuid.UUID `gorm:"column:id;->"`
	AccountID  *uuid.UUID `gorm:"column:account_id;->"`
	Email      *string    `gorm:"column:email;->"`
	IsPrimary  *bool      `gorm:"column:is_primary;->"`
	VerifiedAt *time.Time `gorm:"column:verified_at;->"`
	CreatedAt  *time.Time `gorm:"column:created_at;->"`
	UpdatedAt  *time.Time `gorm:"column:updated_at;->"`
}

func (Listemailitem) TableName() string { return "auth.ListEmailItems" }

var ListemailitemCols = struct {
	ID, AccountID, Email, IsPrimary, VerifiedAt, CreatedAt, UpdatedAt string
}{
	ID:         "id",
	AccountID:  "account_id",
	Email:      "email",
	IsPrimary:  "is_primary",
	VerifiedAt: "verified_at",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
}
