// Code generated by gen-views. DO NOT EDIT.
package views

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
)

// ProfileSimpleView represents the auth.profile_simple_view database view
// Purpose: Provides basic user and profile information without aggregations
// Use Case: Quick profile lookups, API endpoints that don't need full details
type ProfileSimpleView struct {
	// User fields
	UserID        uuid.UUID  `gorm:"column:user_id;->"`
	Username      string     `gorm:"column:username;->"`
	Email         string     `gorm:"column:email;->"`
	UserPhone     *string    `gorm:"column:user_phone;->"`
	UserStatus    string     `gorm:"column:user_status;->"`
	IsVerified    bool       `gorm:"column:is_verified;->"`
	LastLoginAt   *time.Time `gorm:"column:last_login_at;->"`
	UserCreatedAt time.Time  `gorm:"column:user_created_at;->"`
	UserUpdatedAt time.Time  `gorm:"column:user_updated_at;->"`

	// Profile fields
	ProfileID        *uuid.UUID      `gorm:"column:profile_id;->"`
	FirstName        *string         `gorm:"column:first_name;->"`
	LastName         *string         `gorm:"column:last_name;->"`
	Nickname         *string         `gorm:"column:nickname;->"`
	DisplayName      *string         `gorm:"column:display_name;->"`
	AvatarID         *uuid.UUID      `gorm:"column:avatar_id;->"`
	BackgroundID     *uuid.UUID      `gorm:"column:background_id;->"`
	BackgroundIds    *string         `gorm:"column:background_ids;->"` // UUID array as string
	Bio              *string         `gorm:"column:bio;->"`
	ProfilePhone     *string         `gorm:"column:profile_phone;->"`
	Birthday         *time.Time      `gorm:"column:birthday;->"`
	Age              *int            `gorm:"column:age;->"`
	Gender           *string         `gorm:"column:gender;->"`
	Location         *string         `gorm:"column:location;->"`
	Website          *string         `gorm:"column:website;->"`
	Github           *string         `gorm:"column:github;->"`
	SocialLinks      *datatypes.JSON `gorm:"column:social_links;->"`
	Preferences      *datatypes.JSON `gorm:"column:preferences;->"`
	Skills           *datatypes.JSON `gorm:"column:skills;->"`
	PrivacySettings  *datatypes.JSON `gorm:"column:privacy_settings;->"`
	ProfileCreatedAt *time.Time      `gorm:"column:profile_created_at;->"`
	ProfileUpdatedAt *time.Time      `gorm:"column:profile_updated_at;->"`
}

func (ProfileSimpleView) TableName() string {
	return "auth.profile_simple_view"
}

var ProfileSimpleViewCols = struct {
	UserID, Username, Email, UserPhone, UserStatus, IsVerified, LastLoginAt,
	UserCreatedAt, UserUpdatedAt, ProfileID, FirstName, LastName, Nickname, DisplayName,
	AvatarID, BackgroundID, BackgroundIds, Bio, ProfilePhone, Birthday, Age, Gender,
	Location, Website, Github, SocialLinks, Preferences, Skills, PrivacySettings,
	ProfileCreatedAt, ProfileUpdatedAt string
}{
	UserID:           "user_id",
	Username:         "username",
	Email:            "email",
	UserPhone:        "user_phone",
	UserStatus:       "user_status",
	IsVerified:       "is_verified",
	LastLoginAt:      "last_login_at",
	UserCreatedAt:    "user_created_at",
	UserUpdatedAt:    "user_updated_at",
	ProfileID:        "profile_id",
	FirstName:        "first_name",
	LastName:         "last_name",
	Nickname:         "nickname",
	DisplayName:      "display_name",
	AvatarID:         "avatar_id",
	BackgroundID:     "background_id",
	BackgroundIds:    "background_ids",
	Bio:              "bio",
	ProfilePhone:     "profile_phone",
	Birthday:         "birthday",
	Age:              "age",
	Gender:           "gender",
	Location:         "location",
	Website:          "website",
	Github:           "github",
	SocialLinks:      "social_links",
	Preferences:      "preferences",
	Skills:           "skills",
	PrivacySettings:  "privacy_settings",
	ProfileCreatedAt: "profile_created_at",
	ProfileUpdatedAt: "profile_updated_at",
}
