// Code generated by gen-views. DO NOT EDIT.
package views

import (
	"time"

	"github.com/google/uuid"
)

type AudiosActiveView struct {
	ID              *uuid.UUID `gorm:"column:id;->"`
	FilePath        *string    `gorm:"column:file_path;->"`
	FileName        *string    `gorm:"column:file_name;->"`
	FileSize        *int64     `gorm:"column:file_size;->"`
	MimeType        *string    `gorm:"column:mime_type;->"`
	DurationSeconds *float64   `gorm:"column:duration_seconds;->"`
	UploaderID      *uuid.UUID `gorm:"column:uploader_id;->"`
	CreatedAt       *time.Time `gorm:"column:created_at;->"`
	UpdatedAt       *time.Time `gorm:"column:updated_at;->"`
}

func (AudiosActiveView) TableName() string { return "asset.AudiosActiveView" }

var AudiosActiveViewCols = struct {
	ID, FilePath, FileName, FileSize, MimeType, DurationSeconds, UploaderID,
	CreatedAt, UpdatedAt string
}{
	ID:              "id",
	FilePath:        "file_path",
	FileName:        "file_name",
	FileSize:        "file_size",
	MimeType:        "mime_type",
	DurationSeconds: "duration_seconds",
	UploaderID:      "uploader_id",
	CreatedAt:       "created_at",
	UpdatedAt:       "updated_at",
}
