// Code generated by gen-views. DO NOT EDIT.
package views

import (
	"time"

	"github.com/google/uuid"
)

type Filesactiveview struct {
	ID         *uuid.UUID `gorm:"column:id;->"`
	FilePath   *string    `gorm:"column:file_path;->"`
	FileName   *string    `gorm:"column:file_name;->"`
	FileSize   *int64     `gorm:"column:file_size;->"`
	MimeType   *string    `gorm:"column:mime_type;->"`
	UploaderID *uuid.UUID `gorm:"column:uploader_id;->"`
	CreatedAt  *time.Time `gorm:"column:created_at;->"`
	UpdatedAt  *time.Time `gorm:"column:updated_at;->"`
}

func (Filesactiveview) TableName() string { return "asset.FilesActiveView" }

var FilesactiveviewCols = struct {
	ID, FilePath, FileName, FileSize, MimeType, UploaderID, CreatedAt,
	UpdatedAt string
}{
	ID:         "id",
	FilePath:   "file_path",
	FileName:   "file_name",
	FileSize:   "file_size",
	MimeType:   "mime_type",
	UploaderID: "uploader_id",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
}
