-- atlas:import schema.sql
-- atlas:import tables/user_credentials.sql
-- atlas:import tables/refresh_tokens.sql
-- atlas:import tables/login_attempts.sql
-- atlas:import tables/account_lockouts.sql
-- atlas:import tables/password_resets.sql
-- atlas:import tables/mfa_factors.sql
-- atlas:import tables/sessions.sql
-- atlas:import tables/credential_events.sql
-- atlas:import tables/password_history.sql
-- atlas:import tables/trusted_devices.sql

