// Code generated by gen-views. DO NOT EDIT.
package views

import (
	"github.com/google/uuid"
	"gorm.io/datatypes"
)

// UserBadgesView represents the auth.user_badges_view database view
// Purpose: Provides user information with aggregated badges array
// Use Case: User profile pages, achievement displays, badge-based filtering
type UserBadgesView struct {
	UserID      uuid.UUID       `gorm:"column:user_id;->"`
	Username    string          `gorm:"column:username;->"`
	Email       string          `gorm:"column:email;->"`
	ProfileID   *uuid.UUID      `gorm:"column:profile_id;->"`
	DisplayName *string         `gorm:"column:display_name;->"`
	Badges      *datatypes.JSON `gorm:"column:badges;->"` // Array of badge objects
}

func (UserBadgesView) TableName() string {
	return "auth.user_badges_view"
}

var UserBadgesViewCols = struct {
	UserID, Username, Email, ProfileID, DisplayName, Badges string
}{
	UserID:      "user_id",
	Username:    "username",
	Email:       "email",
	ProfileID:   "profile_id",
	DisplayName: "display_name",
	Badges:      "badges",
}
