// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type Audio struct {
	ID              uuid.UUID      `gorm:"type:uuid;primaryKey"`
	FilePath        string         `gorm:"type:varchar(500);index:idx_audios_file_path"`
	FileName        string         `gorm:"type:varchar(255)"`
	FileSize        int64          `gorm:"type:bigint"`
	MimeType        string         `gorm:"type:varchar(100);index:idx_audios_mime_type"`
	DurationSeconds *float64       `gorm:"type:double precision"`
	UploaderID      uuid.UUID      `gorm:"type:uuid;index:idx_audios_uploader_id"`
	CreatedAt       time.Time      `gorm:"autoCreateTime"`
	UpdatedAt       time.Time      `gorm:"autoUpdateTime"`
	DeletedAt       gorm.DeletedAt `gorm:"index"`
}

func (Audio) TableName() string { return "asset.Audios" }

func (m *Audio) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var AudioCols = struct {
	ID, FilePath, FileName, FileSize, MimeType, DurationSeconds, UploaderID,
	CreatedAt, UpdatedAt, DeletedAt string
}{
	ID:              "id",
	FilePath:        "file_path",
	FileName:        "file_name",
	FileSize:        "file_size",
	MimeType:        "mime_type",
	DurationSeconds: "duration_seconds",
	UploaderID:      "uploader_id",
	CreatedAt:       "created_at",
	UpdatedAt:       "updated_at",
	DeletedAt:       "deleted_at",
}

const (
	AudioPk = "Audios_pkey"
)
