// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type Image struct {
	ID         uuid.UUID      `gorm:"type:uuid;primaryKey"`
	FilePath   string         `gorm:"type:varchar(500);index:idx_images_file_path"`
	FileName   string         `gorm:"type:varchar(255)"`
	FileSize   int64          `gorm:"type:bigint"`
	MimeType   string         `gorm:"type:varchar(100);index:idx_images_mime_type"`
	Width      *int           `gorm:"type:integer"`
	Height     *int           `gorm:"type:integer"`
	AltText    *string        `gorm:"type:varchar(255)"`
	UploaderID uuid.UUID      `gorm:"type:uuid;index:idx_images_uploader_id"`
	CreatedAt  time.Time      `gorm:"autoCreateTime"`
	UpdatedAt  time.Time      `gorm:"autoUpdateTime"`
	DeletedAt  gorm.DeletedAt `gorm:"index"`
}

func (Image) TableName() string { return "asset.Images" }

func (m *Image) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var ImageCols = struct {
	ID, FilePath, FileName, FileSize, MimeType, Width, Height,
	AltText, UploaderID, CreatedAt, UpdatedAt, DeletedAt string
}{
	ID:         "id",
	FilePath:   "file_path",
	FileName:   "file_name",
	FileSize:   "file_size",
	MimeType:   "mime_type",
	Width:      "width",
	Height:     "height",
	AltText:    "alt_text",
	UploaderID: "uploader_id",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
	DeletedAt:  "deleted_at",
}

const (
	ImagePk = "Images_pkey"
)
