// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxid/enums"
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

type Application struct {
	ID            uuid.UUID                `gorm:"type:uuid;primaryKey"`
	ApplicationID string                   `gorm:"type:varchar(255);uniqueIndex:applications_application_id_key;index:idx_applications_application_id"`
	TenantID      uuid.UUID                `gorm:"type:uuid;index:idx_applications_tenant_environment,priority:1;index:idx_applications_tenant_id"`
	Name          string                   `gorm:"type:varchar(255)"`
	Description   *string                  `gorm:"type:text"`
	Type          enums.ClientsAppType     `gorm:"type:app_type"`
	Status        enums.ClientsAppStatus   `gorm:"type:app_status;index:idx_applications_status"`
	Environment   enums.ClientsEnvironment `gorm:"type:environment;index:idx_applications_environment;index:idx_applications_tenant_environment,priority:2"`
	CreatedAt     time.Time                `gorm:"autoCreateTime"`
	UpdatedAt     time.Time                `gorm:"autoUpdateTime"`
	CreatedBy     *uuid.UUID               `gorm:"type:uuid"`
	UpdatedBy     *uuid.UUID               `gorm:"type:uuid"`
	Metadata      *datatypes.JSON          `gorm:"type:jsonb"`
	DeletedAt     gorm.DeletedAt           `gorm:"index"`
}

func (Application) TableName() string { return "clients.applications" }

func (m *Application) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var ApplicationCols = struct {
	ID, ApplicationID, TenantID, Name, Description, Type, Status,
	Environment, CreatedAt, UpdatedAt, CreatedBy, UpdatedBy, Metadata, DeletedAt string
}{
	ID:            "id",
	ApplicationID: "application_id",
	TenantID:      "tenant_id",
	Name:          "name",
	Description:   "description",
	Type:          "type",
	Status:        "status",
	Environment:   "environment",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
	CreatedBy:     "created_by",
	UpdatedBy:     "updated_by",
	Metadata:      "metadata",
	DeletedAt:     "deleted_at",
}

const (
	ApplicationPk                 = "applications_pkey"
	ApplicationUkApplicationIdKey = "applications_application_id_key"
)
