// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type ClientScope struct {
	ID           uuid.UUID  `gorm:"type:uuid;primaryKey"`
	AppID        uuid.UUID  `gorm:"type:uuid;uniqueIndex:client_scopes_app_id_scope_key,priority:1;index:idx_client_scopes_app_id;index:idx_client_scopes_app_scope,priority:1"`
	Scope        string     `gorm:"type:varchar(255);uniqueIndex:client_scopes_app_id_scope_key,priority:2;index:idx_client_scopes_app_scope,priority:2;index:idx_client_scopes_scope"`
	GrantedBy    *uuid.UUID `gorm:"type:uuid"`
	GrantedAt    time.Time  `gorm:"type:timestamp"`
	ExpiresAt    *time.Time `gorm:"type:timestamp;index:idx_client_scopes_expires_at"`
	CreatedAt    time.Time  `gorm:"autoCreateTime"`
	RevokedAt    *time.Time `gorm:"type:timestamp;index:idx_client_scopes_revoked_at"`
	RevokedBy    *uuid.UUID `gorm:"type:uuid"`
	RevokeReason *string    `gorm:"type:text"`
}

func (ClientScope) TableName() string { return "clients.client_scopes" }

func (m *ClientScope) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var ClientScopeCols = struct {
	ID, AppID, Scope, GrantedBy, GrantedAt, ExpiresAt, CreatedAt,
	RevokedAt, RevokedBy, RevokeReason string
}{
	ID:           "id",
	AppID:        "app_id",
	Scope:        "scope",
	GrantedBy:    "granted_by",
	GrantedAt:    "granted_at",
	ExpiresAt:    "expires_at",
	CreatedAt:    "created_at",
	RevokedAt:    "revoked_at",
	RevokedBy:    "revoked_by",
	RevokeReason: "revoke_reason",
}

const (
	ClientScopePk              = "client_scopes_pkey"
	ClientScopeUkAppIdScopeKey = "client_scopes_app_id_scope_key"
	ClientScopeFkAppIdFkey     = "client_scopes_app_id_fkey"
)
