// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxid/enums"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type IpAllowlist struct {
	ID            uuid.UUID                    `gorm:"type:uuid;primaryKey"`
	RuleID        string                       `gorm:"type:varchar(255);index:idx_ip_allowlist_rule_id;uniqueIndex:ip_allowlist_rule_id_key"`
	ApplicationID uuid.UUID                    `gorm:"type:uuid;index:idx_ip_allowlist_app_status,priority:1;index:idx_ip_allowlist_application_id"`
	Cidr          string                       `gorm:"type:cidr"`
	Description   *string                      `gorm:"type:text"`
	Status        enums.ClientsAllowlistStatus `gorm:"type:allowlist_status;index:idx_ip_allowlist_app_status,priority:2;index:idx_ip_allowlist_status"`
	CreatedAt     time.Time                    `gorm:"autoCreateTime"`
	CreatedBy     *uuid.UUID                   `gorm:"type:uuid"`
	UpdatedAt     time.Time                    `gorm:"autoUpdateTime"`
	UpdatedBy     *uuid.UUID                   `gorm:"type:uuid"`
	RevokedAt     *time.Time                   `gorm:"type:timestamp"`
	RevokedBy     *uuid.UUID                   `gorm:"type:uuid"`
	RevokeReason  *string                      `gorm:"type:text"`
}

func (IpAllowlist) TableName() string { return "clients.ip_allowlist" }

func (m *IpAllowlist) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var IpAllowlistCols = struct {
	ID, RuleID, ApplicationID, Cidr, Description, Status, CreatedAt,
	CreatedBy, UpdatedAt, UpdatedBy, RevokedAt, RevokedBy, RevokeReason string
}{
	ID:            "id",
	RuleID:        "rule_id",
	ApplicationID: "application_id",
	Cidr:          "cidr",
	Description:   "description",
	Status:        "status",
	CreatedAt:     "created_at",
	CreatedBy:     "created_by",
	UpdatedAt:     "updated_at",
	UpdatedBy:     "updated_by",
	RevokedAt:     "revoked_at",
	RevokedBy:     "revoked_by",
	RevokeReason:  "revoke_reason",
}

const (
	IpAllowlistPk                  = "ip_allowlist_pkey"
	IpAllowlistUkRuleIdKey         = "ip_allowlist_rule_id_key"
	IpAllowlistFkApplicationIdFkey = "ip_allowlist_application_id_fkey"
)
