// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxid/enums"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type RateLimit struct {
	ID            uuid.UUID                  `gorm:"type:uuid;primaryKey"`
	ApplicationID uuid.UUID                  `gorm:"type:uuid;index:idx_rate_limits_application_id;uniqueIndex:rate_limits_application_id_limit_type_key,priority:1"`
	LimitType     enums.ClientsRateLimitType `gorm:"type:rate_limit_type;uniqueIndex:rate_limits_application_id_limit_type_key,priority:2"`
	LimitValue    int                        `gorm:"type:integer"`
	WindowSeconds int                        `gorm:"type:integer"`
	Description   *string                    `gorm:"type:text"`
	Status        string                     `gorm:"type:varchar(50);index:idx_rate_limits_status"`
	CreatedAt     time.Time                  `gorm:"autoCreateTime"`
	CreatedBy     *uuid.UUID                 `gorm:"type:uuid"`
	UpdatedAt     time.Time                  `gorm:"autoUpdateTime"`
	UpdatedBy     *uuid.UUID                 `gorm:"type:uuid"`
}

func (RateLimit) TableName() string { return "clients.rate_limits" }

func (m *RateLimit) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var RateLimitCols = struct {
	ID, ApplicationID, LimitType, LimitValue, WindowSeconds, Description, Status,
	CreatedAt, CreatedBy, UpdatedAt, UpdatedBy string
}{
	ID:            "id",
	ApplicationID: "application_id",
	LimitType:     "limit_type",
	LimitValue:    "limit_value",
	WindowSeconds: "window_seconds",
	Description:   "description",
	Status:        "status",
	CreatedAt:     "created_at",
	CreatedBy:     "created_by",
	UpdatedAt:     "updated_at",
	UpdatedBy:     "updated_by",
}

const (
	RateLimitPk                          = "rate_limits_pkey"
	RateLimitUkApplicationIdLimitTypeKey = "rate_limits_application_id_limit_type_key"
	RateLimitFkApplicationIdFkey         = "rate_limits_application_id_fkey"
)
