// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxid/enums"
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

type ActorSnapshot struct {
	ID           uuid.UUID            `gorm:"type:uuid;primaryKey"`
	ActorType    enums.AuditActorType `gorm:"type:actor_type;uniqueIndex:actor_snapshots_actor_type_actor_id_snapshot_at_key,priority:1;index:idx_actor_snapshots_actor,priority:1"`
	ActorID      uuid.UUID            `gorm:"type:uuid;uniqueIndex:actor_snapshots_actor_type_actor_id_snapshot_at_key,priority:2;index:idx_actor_snapshots_actor,priority:2"`
	DisplayName  *string              `gorm:"type:varchar(255)"`
	Email        *string              `gorm:"type:varchar(255)"`
	ClientName   *string              `gorm:"type:varchar(255)"`
	TenantID     *uuid.UUID           `gorm:"type:uuid;index:idx_actor_snapshots_tenant_id"`
	SnapshotAt   time.Time            `gorm:"type:timestamp;uniqueIndex:actor_snapshots_actor_type_actor_id_snapshot_at_key,priority:3;index:idx_actor_snapshots_actor,priority:3;index:idx_actor_snapshots_snapshot_at"`
	SnapshotData *datatypes.JSON      `gorm:"type:jsonb"`
	CreatedAt    time.Time            `gorm:"autoCreateTime"`
}

func (ActorSnapshot) TableName() string { return "audit.actor_snapshots" }

func (m *ActorSnapshot) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var ActorSnapshotCols = struct {
	ID, ActorType, ActorID, DisplayName, Email, ClientName, TenantID,
	SnapshotAt, SnapshotData, CreatedAt string
}{
	ID:           "id",
	ActorType:    "actor_type",
	ActorID:      "actor_id",
	DisplayName:  "display_name",
	Email:        "email",
	ClientName:   "client_name",
	TenantID:     "tenant_id",
	SnapshotAt:   "snapshot_at",
	SnapshotData: "snapshot_data",
	CreatedAt:    "created_at",
}

const (
	ActorSnapshotPk                              = "actor_snapshots_pkey"
	ActorSnapshotUkActorTypeActorIdSnapshotAtKey = "actor_snapshots_actor_type_actor_id_snapshot_at_key"
)
