// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxid/enums"
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

type Event struct {
	ID                  uuid.UUID                     `gorm:"type:uuid;primaryKey"`
	EventID             string                        `gorm:"type:varchar(255);uniqueIndex:events_event_id_key;index:idx_events_event_id"`
	OccurredAt          time.Time                     `gorm:"type:timestamp;index:idx_events_action_occurred,priority:2;index:idx_events_actor_occurred,priority:3;index:idx_events_occurred_at;index:idx_events_tenant_action,priority:3;index:idx_events_tenant_occurred,priority:2"`
	ReceivedAt          time.Time                     `gorm:"type:timestamp"`
	TenantID            *uuid.UUID                    `gorm:"type:uuid;index:idx_events_tenant_action,priority:1;index:idx_events_tenant_id;index:idx_events_tenant_occurred,priority:1"`
	ApplicationID       *uuid.UUID                    `gorm:"type:uuid;index:idx_events_application_id"`
	ActorType           enums.AuditActorType          `gorm:"type:actor_type;index:idx_events_actor,priority:1;index:idx_events_actor_occurred,priority:1"`
	ActorID             uuid.UUID                     `gorm:"type:uuid;index:idx_events_actor,priority:2;index:idx_events_actor_occurred,priority:2"`
	ActorTenantMemberID *uuid.UUID                    `gorm:"type:uuid"`
	Action              string                        `gorm:"type:varchar(255);index:idx_events_action;index:idx_events_action_occurred,priority:1;index:idx_events_tenant_action,priority:2"`
	TargetType          *string                       `gorm:"type:varchar(100);index:idx_events_target,priority:1"`
	TargetID            *uuid.UUID                    `gorm:"type:uuid;index:idx_events_target,priority:2"`
	Result              enums.AuditResultType         `gorm:"type:result_type;index:idx_events_result"`
	FailureReasonCode   *string                       `gorm:"type:varchar(100)"`
	HttpMethod          *string                       `gorm:"type:varchar(10)"`
	HttpPath            *string                       `gorm:"type:varchar(500)"`
	HttpStatus          *int                          `gorm:"type:integer"`
	RequestID           *string                       `gorm:"type:varchar(255);index:idx_events_request_id"`
	TraceID             *string                       `gorm:"type:varchar(255);index:idx_events_trace_id"`
	IP                  *string                       `gorm:"type:inet"`
	UserAgent           *string                       `gorm:"type:text"`
	GeoCountry          *string                       `gorm:"type:varchar(10)"`
	RiskLevel           enums.AuditRiskLevel          `gorm:"type:risk_level;index:idx_events_risk_level"`
	DataClassification  enums.AuditDataClassification `gorm:"type:data_classification;index:idx_events_data_classification"`
	PrevHash            *string                       `gorm:"type:varchar(64)"`
	EventHash           *string                       `gorm:"type:varchar(64)"`
	Metadata            *datatypes.JSON               `gorm:"type:jsonb"`
	CreatedAt           time.Time                     `gorm:"autoCreateTime"`
}

func (Event) TableName() string { return "audit.events" }

func (m *Event) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var EventCols = struct {
	ID, EventID, OccurredAt, ReceivedAt, TenantID, ApplicationID, ActorType,
	ActorID, ActorTenantMemberID, Action, TargetType, TargetID, Result, FailureReasonCode,
	HttpMethod, HttpPath, HttpStatus, RequestID, TraceID, IP, UserAgent,
	GeoCountry, RiskLevel, DataClassification, PrevHash, EventHash, Metadata, CreatedAt string
}{
	ID:                  "id",
	EventID:             "event_id",
	OccurredAt:          "occurred_at",
	ReceivedAt:          "received_at",
	TenantID:            "tenant_id",
	ApplicationID:       "application_id",
	ActorType:           "actor_type",
	ActorID:             "actor_id",
	ActorTenantMemberID: "actor_tenant_member_id",
	Action:              "action",
	TargetType:          "target_type",
	TargetID:            "target_id",
	Result:              "result",
	FailureReasonCode:   "failure_reason_code",
	HttpMethod:          "http_method",
	HttpPath:            "http_path",
	HttpStatus:          "http_status",
	RequestID:           "request_id",
	TraceID:             "trace_id",
	IP:                  "ip",
	UserAgent:           "user_agent",
	GeoCountry:          "geo_country",
	RiskLevel:           "risk_level",
	DataClassification:  "data_classification",
	PrevHash:            "prev_hash",
	EventHash:           "event_hash",
	Metadata:            "metadata",
	CreatedAt:           "created_at",
}

const (
	EventPk           = "events_pkey"
	EventUkEventIdKey = "events_event_id_key"
)
