// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxid/enums"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type EventSearchIndex struct {
	ID                 uuid.UUID                     `gorm:"type:uuid;primaryKey"`
	EventID            string                        `gorm:"type:varchar(255);uniqueIndex:event_search_index_event_id_key;index:idx_event_search_index_event_id"`
	TenantID           *uuid.UUID                    `gorm:"type:uuid;index:idx_event_search_index_tenant_occurred,priority:1"`
	ApplicationID      *uuid.UUID                    `gorm:"type:uuid"`
	ActorType          enums.AuditActorType          `gorm:"type:actor_type;index:idx_event_search_index_actor,priority:1"`
	ActorID            uuid.UUID                     `gorm:"type:uuid;index:idx_event_search_index_actor,priority:2"`
	Action             string                        `gorm:"type:varchar(255);index:idx_event_search_index_action,priority:1"`
	TargetType         *string                       `gorm:"type:varchar(100);index:idx_event_search_index_target,priority:1"`
	TargetID           *uuid.UUID                    `gorm:"type:uuid;index:idx_event_search_index_target,priority:2"`
	Result             enums.AuditResultType         `gorm:"type:result_type;index:idx_event_search_index_result,priority:1"`
	OccurredAt         time.Time                     `gorm:"type:timestamp;index:idx_event_search_index_action,priority:2;index:idx_event_search_index_actor,priority:3;index:idx_event_search_index_result,priority:2;index:idx_event_search_index_risk_level,priority:2;index:idx_event_search_index_tenant_occurred,priority:2"`
	IP                 *string                       `gorm:"type:inet"`
	RiskLevel          enums.AuditRiskLevel          `gorm:"type:risk_level;index:idx_event_search_index_risk_level,priority:1"`
	DataClassification enums.AuditDataClassification `gorm:"type:data_classification"`
	Tags               *string                       `gorm:"type:text[];index:idx_event_search_index_tags"`
	CreatedAt          time.Time                     `gorm:"autoCreateTime"`
}

func (EventSearchIndex) TableName() string { return "audit.event_search_index" }

func (m *EventSearchIndex) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var EventSearchIndexCols = struct {
	ID, EventID, TenantID, ApplicationID, ActorType, ActorID, Action,
	TargetType, TargetID, Result, OccurredAt, IP, RiskLevel, DataClassification,
	Tags, CreatedAt string
}{
	ID:                 "id",
	EventID:            "event_id",
	TenantID:           "tenant_id",
	ApplicationID:      "application_id",
	ActorType:          "actor_type",
	ActorID:            "actor_id",
	Action:             "action",
	TargetType:         "target_type",
	TargetID:           "target_id",
	Result:             "result",
	OccurredAt:         "occurred_at",
	IP:                 "ip",
	RiskLevel:          "risk_level",
	DataClassification: "data_classification",
	Tags:               "tags",
	CreatedAt:          "created_at",
}

const (
	EventSearchIndexPk           = "event_search_index_pkey"
	EventSearchIndexUkEventIdKey = "event_search_index_event_id_key"
)
