// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxid/enums"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type EventRetentionPolicy struct {
	ID                 uuid.UUID                      `gorm:"type:uuid;primaryKey"`
	PolicyName         string                         `gorm:"type:varchar(255);uniqueIndex:event_retention_policies_policy_name_key;index:idx_event_retention_policies_policy_name"`
	TenantID           *uuid.UUID                     `gorm:"type:uuid;index:idx_event_retention_policies_tenant_id"`
	ActionPattern      *string                        `gorm:"type:varchar(255)"`
	DataClassification *enums.AuditDataClassification `gorm:"type:data_classification"`
	RiskLevel          *enums.AuditRiskLevel          `gorm:"type:risk_level"`
	RetentionDays      int                            `gorm:"type:integer"`
	RetentionAction    enums.AuditRetentionAction     `gorm:"type:retention_action"`
	ArchiveLocation    *string                        `gorm:"type:text"`
	Status             string                         `gorm:"type:varchar(50);index:idx_event_retention_policies_status"`
	CreatedAt          time.Time                      `gorm:"autoCreateTime"`
	UpdatedAt          time.Time                      `gorm:"autoUpdateTime"`
	CreatedBy          *uuid.UUID                     `gorm:"type:uuid"`
}

func (EventRetentionPolicy) TableName() string { return "audit.event_retention_policies" }

func (m *EventRetentionPolicy) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var EventRetentionPolicyCols = struct {
	ID, PolicyName, TenantID, ActionPattern, DataClassification, RiskLevel, RetentionDays,
	RetentionAction, ArchiveLocation, Status, CreatedAt, UpdatedAt, CreatedBy string
}{
	ID:                 "id",
	PolicyName:         "policy_name",
	TenantID:           "tenant_id",
	ActionPattern:      "action_pattern",
	DataClassification: "data_classification",
	RiskLevel:          "risk_level",
	RetentionDays:      "retention_days",
	RetentionAction:    "retention_action",
	ArchiveLocation:    "archive_location",
	Status:             "status",
	CreatedAt:          "created_at",
	UpdatedAt:          "updated_at",
	CreatedBy:          "created_by",
}

const (
	EventRetentionPolicyPk              = "event_retention_policies_pkey"
	EventRetentionPolicyUkPolicyNameKey = "event_retention_policies_policy_name_key"
)
