// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type HashChainCheckpoint struct {
	ID                 uuid.UUID  `gorm:"type:uuid;primaryKey"`
	CheckpointID       string     `gorm:"type:varchar(255);uniqueIndex:hash_chain_checkpoints_checkpoint_id_key;index:idx_hash_chain_checkpoints_checkpoint_id"`
	TenantID           *uuid.UUID `gorm:"type:uuid;index:idx_hash_chain_checkpoints_tenant_id"`
	PartitionDate      time.Time  `gorm:"type:date;index:idx_hash_chain_checkpoints_partition_date"`
	CheckpointHash     string     `gorm:"type:varchar(64)"`
	PrevCheckpointHash *string    `gorm:"type:varchar(64);index:idx_hash_chain_checkpoints_prev_hash"`
	EventCount         int        `gorm:"type:integer"`
	FirstEventID       *string    `gorm:"type:varchar(255)"`
	LastEventID        *string    `gorm:"type:varchar(255)"`
	CreatedAt          time.Time  `gorm:"autoCreateTime"`
	CreatedBy          *string    `gorm:"type:varchar(255)"`
}

func (HashChainCheckpoint) TableName() string { return "audit.hash_chain_checkpoints" }

func (m *HashChainCheckpoint) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var HashChainCheckpointCols = struct {
	ID, CheckpointID, TenantID, PartitionDate, CheckpointHash, PrevCheckpointHash, EventCount,
	FirstEventID, LastEventID, CreatedAt, CreatedBy string
}{
	ID:                 "id",
	CheckpointID:       "checkpoint_id",
	TenantID:           "tenant_id",
	PartitionDate:      "partition_date",
	CheckpointHash:     "checkpoint_hash",
	PrevCheckpointHash: "prev_checkpoint_hash",
	EventCount:         "event_count",
	FirstEventID:       "first_event_id",
	LastEventID:        "last_event_id",
	CreatedAt:          "created_at",
	CreatedBy:          "created_by",
}

const (
	HashChainCheckpointPk                = "hash_chain_checkpoints_pkey"
	HashChainCheckpointUkCheckpointIdKey = "hash_chain_checkpoints_checkpoint_id_key"
)
