// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxid/enums"
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

type DomainVerification struct {
	ID                 uuid.UUID                       `gorm:"type:uuid;primaryKey"`
	TenantID           uuid.UUID                       `gorm:"type:uuid;uniqueIndex:domain_verifications_tenant_id_domain_key,priority:1;index:idx_domain_verifications_tenant_id"`
	Domain             string                          `gorm:"type:varchar(255);uniqueIndex:domain_verifications_tenant_id_domain_key,priority:2;index:idx_domain_verifications_domain"`
	VerificationMethod enums.TenantsVerificationMethod `gorm:"type:verification_method"`
	VerificationToken  *string                         `gorm:"type:varchar(255)"`
	Status             enums.TenantsVerificationStatus `gorm:"type:verification_status;index:idx_domain_verifications_status"`
	VerifiedAt         *time.Time                      `gorm:"type:timestamp"`
	ExpiresAt          *time.Time                      `gorm:"type:timestamp"`
	CreatedAt          time.Time                       `gorm:"autoCreateTime"`
	CreatedBy          *uuid.UUID                      `gorm:"type:uuid"`
	Metadata           *datatypes.JSON                 `gorm:"type:jsonb"`
}

func (DomainVerification) TableName() string { return "tenants.domain_verifications" }

func (m *DomainVerification) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var DomainVerificationCols = struct {
	ID, TenantID, Domain, VerificationMethod, VerificationToken, Status, VerifiedAt,
	ExpiresAt, CreatedAt, CreatedBy, Metadata string
}{
	ID:                 "id",
	TenantID:           "tenant_id",
	Domain:             "domain",
	VerificationMethod: "verification_method",
	VerificationToken:  "verification_token",
	Status:             "status",
	VerifiedAt:         "verified_at",
	ExpiresAt:          "expires_at",
	CreatedAt:          "created_at",
	CreatedBy:          "created_by",
	Metadata:           "metadata",
}

const (
	DomainVerificationPk                  = "domain_verifications_pkey"
	DomainVerificationUkTenantIdDomainKey = "domain_verifications_tenant_id_domain_key"
	DomainVerificationFkTenantIdFkey      = "domain_verifications_tenant_id_fkey"
)
