// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxid/enums"
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

type Group struct {
	ID            uuid.UUID              `gorm:"type:uuid;primaryKey"`
	GroupID       string                 `gorm:"type:varchar(255);uniqueIndex:groups_group_id_key;index:idx_groups_group_id"`
	TenantID      uuid.UUID              `gorm:"type:uuid;index:idx_groups_tenant_id"`
	Name          string                 `gorm:"type:varchar(255)"`
	Type          enums.TenantsGroupType `gorm:"type:group_type;index:idx_groups_type"`
	ParentGroupID *uuid.UUID             `gorm:"type:uuid;index:idx_groups_parent_group_id"`
	Description   *string                `gorm:"type:text"`
	CreatedAt     time.Time              `gorm:"autoCreateTime"`
	UpdatedAt     time.Time              `gorm:"autoUpdateTime"`
	CreatedBy     *uuid.UUID             `gorm:"type:uuid"`
	DeletedAt     gorm.DeletedAt         `gorm:"index"`
	Metadata      *datatypes.JSON        `gorm:"type:jsonb"`
}

func (Group) TableName() string { return "tenants.groups" }

func (m *Group) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var GroupCols = struct {
	ID, GroupID, TenantID, Name, Type, ParentGroupID, Description,
	CreatedAt, UpdatedAt, CreatedBy, DeletedAt, Metadata string
}{
	ID:            "id",
	GroupID:       "group_id",
	TenantID:      "tenant_id",
	Name:          "name",
	Type:          "type",
	ParentGroupID: "parent_group_id",
	Description:   "description",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
	CreatedBy:     "created_by",
	DeletedAt:     "deleted_at",
	Metadata:      "metadata",
}

const (
	GroupPk                  = "groups_pkey"
	GroupUkGroupIdKey        = "groups_group_id_key"
	GroupFkParentGroupIdFkey = "groups_parent_group_id_fkey"
	GroupFkTenantIdFkey      = "groups_tenant_id_fkey"
)
