// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxid/enums"
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

type Invitation struct {
	ID               uuid.UUID                     `gorm:"type:uuid;primaryKey"`
	InviteID         string                        `gorm:"type:varchar(255);index:idx_invitations_invite_id;uniqueIndex:invitations_invite_id_key"`
	TenantID         uuid.UUID                     `gorm:"type:uuid;index:idx_invitations_tenant_id;index:idx_invitations_tenant_status,priority:1"`
	Email            string                        `gorm:"type:varchar(255);index:idx_invitations_email"`
	TokenHash        string                        `gorm:"type:varchar(255)"`
	ExpiresAt        time.Time                     `gorm:"type:timestamp;index:idx_invitations_expires_at"`
	Status           enums.TenantsInvitationStatus `gorm:"type:invitation_status;index:idx_invitations_status;index:idx_invitations_tenant_status,priority:2"`
	InvitedBy        uuid.UUID                     `gorm:"type:uuid"`
	InvitedAt        time.Time                     `gorm:"type:timestamp"`
	AcceptedByUserID *uuid.UUID                    `gorm:"type:uuid"`
	AcceptedAt       *time.Time                    `gorm:"type:timestamp"`
	RevokedBy        *uuid.UUID                    `gorm:"type:uuid"`
	RevokedAt        *time.Time                    `gorm:"type:timestamp"`
	RevokeReason     *string                       `gorm:"type:text"`
	TenantRoleID     uuid.UUID                     `gorm:"type:uuid;index:idx_invitations_tenant_role_id"`
	Metadata         *datatypes.JSON               `gorm:"type:jsonb"`
}

func (Invitation) TableName() string { return "tenants.invitations" }

func (m *Invitation) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var InvitationCols = struct {
	ID, InviteID, TenantID, Email, TokenHash, ExpiresAt, Status,
	InvitedBy, InvitedAt, AcceptedByUserID, AcceptedAt, RevokedBy, RevokedAt, RevokeReason,
	TenantRoleID, Metadata string
}{
	ID:               "id",
	InviteID:         "invite_id",
	TenantID:         "tenant_id",
	Email:            "email",
	TokenHash:        "token_hash",
	ExpiresAt:        "expires_at",
	Status:           "status",
	InvitedBy:        "invited_by",
	InvitedAt:        "invited_at",
	AcceptedByUserID: "accepted_by_user_id",
	AcceptedAt:       "accepted_at",
	RevokedBy:        "revoked_by",
	RevokedAt:        "revoked_at",
	RevokeReason:     "revoke_reason",
	TenantRoleID:     "tenant_role_id",
	Metadata:         "metadata",
}

const (
	InvitationPk             = "invitations_pkey"
	InvitationUkInviteIdKey  = "invitations_invite_id_key"
	InvitationFkTenantIdFkey = "invitations_tenant_id_fkey"
)
