// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxid/enums"
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

type Member struct {
	ID          uuid.UUID                 `gorm:"type:uuid;primaryKey"`
	MemberID    uuid.UUID                 `gorm:"type:uuid;index:idx_members_member_id;uniqueIndex:members_member_id_key"`
	TenantID    uuid.UUID                 `gorm:"type:uuid;index:idx_members_tenant_id;index:idx_members_tenant_status,priority:1;uniqueIndex:members_tenant_id_user_id_key,priority:1"`
	UserID      uuid.UUID                 `gorm:"type:uuid;index:idx_members_user_id;uniqueIndex:members_tenant_id_user_id_key,priority:2"`
	Status      enums.TenantsMemberStatus `gorm:"type:member_status;index:idx_members_status;index:idx_members_tenant_status,priority:2"`
	Source      enums.TenantsMemberSource `gorm:"type:member_source;index:idx_members_source"`
	JoinedAt    *time.Time                `gorm:"type:timestamp"`
	LeftAt      *time.Time                `gorm:"type:timestamp"`
	CreatedAt   time.Time                 `gorm:"autoCreateTime"`
	CreatedBy   *uuid.UUID                `gorm:"type:uuid"`
	UpdatedAt   time.Time                 `gorm:"autoUpdateTime"`
	ExternalRef *string                   `gorm:"type:varchar(255)"`
	Metadata    *datatypes.JSON           `gorm:"type:jsonb"`
}

func (Member) TableName() string { return "tenants.members" }

func (m *Member) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var MemberCols = struct {
	ID, MemberID, TenantID, UserID, Status, Source, JoinedAt,
	LeftAt, CreatedAt, CreatedBy, UpdatedAt, ExternalRef, Metadata string
}{
	ID:          "id",
	MemberID:    "member_id",
	TenantID:    "tenant_id",
	UserID:      "user_id",
	Status:      "status",
	Source:      "source",
	JoinedAt:    "joined_at",
	LeftAt:      "left_at",
	CreatedAt:   "created_at",
	CreatedBy:   "created_by",
	UpdatedAt:   "updated_at",
	ExternalRef: "external_ref",
	Metadata:    "metadata",
}

const (
	MemberPk                  = "members_pkey"
	MemberUkMemberIdKey       = "members_member_id_key"
	MemberUkTenantIdUserIdKey = "members_tenant_id_user_id_key"
	MemberFkTenantIdFkey      = "members_tenant_id_fkey"
)
