// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type MemberGroup struct {
	ID         uuid.UUID  `gorm:"type:uuid;primaryKey"`
	MemberID   uuid.UUID  `gorm:"type:uuid;index:idx_member_groups_member_id;uniqueIndex:member_groups_member_id_group_id_key,priority:1"`
	GroupID    uuid.UUID  `gorm:"type:uuid;index:idx_member_groups_group_id;uniqueIndex:member_groups_member_id_group_id_key,priority:2"`
	AssignedAt time.Time  `gorm:"type:timestamp"`
	AssignedBy *uuid.UUID `gorm:"type:uuid"`
	RevokedAt  *time.Time `gorm:"type:timestamp"`
	RevokedBy  *uuid.UUID `gorm:"type:uuid"`
}

func (MemberGroup) TableName() string { return "tenants.member_groups" }

func (m *MemberGroup) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var MemberGroupCols = struct {
	ID, MemberID, GroupID, AssignedAt, AssignedBy, RevokedAt, RevokedBy string
}{
	ID:         "id",
	MemberID:   "member_id",
	GroupID:    "group_id",
	AssignedAt: "assigned_at",
	AssignedBy: "assigned_by",
	RevokedAt:  "revoked_at",
	RevokedBy:  "revoked_by",
}

const (
	MemberGroupPk                   = "member_groups_pkey"
	MemberGroupUkMemberIdGroupIdKey = "member_groups_member_id_group_id_key"
	MemberGroupFkGroupIdFkey        = "member_groups_group_id_fkey"
	MemberGroupFkMemberIdFkey       = "member_groups_member_id_fkey"
)
