// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type MemberAppRole struct {
	ID           uuid.UUID  `gorm:"type:uuid;primaryKey"`
	MemberID     uuid.UUID  `gorm:"type:uuid;index:idx_member_app_roles_member_id;uniqueIndex:member_app_roles_member_id_app_id_role_id_key,priority:1"`
	AppID        uuid.UUID  `gorm:"type:uuid;index:idx_member_app_roles_app_id;uniqueIndex:member_app_roles_member_id_app_id_role_id_key,priority:2"`
	RoleID       uuid.UUID  `gorm:"type:uuid;index:idx_member_app_roles_role_id;uniqueIndex:member_app_roles_member_id_app_id_role_id_key,priority:3"`
	AssignedAt   time.Time  `gorm:"type:timestamp"`
	AssignedBy   *uuid.UUID `gorm:"type:uuid"`
	ExpiresAt    *time.Time `gorm:"type:timestamp;index:idx_member_app_roles_expires_at"`
	RevokedAt    *time.Time `gorm:"type:timestamp"`
	RevokedBy    *uuid.UUID `gorm:"type:uuid"`
	RevokeReason *string    `gorm:"type:text"`
}

func (MemberAppRole) TableName() string { return "tenants.member_app_roles" }

func (m *MemberAppRole) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var MemberAppRoleCols = struct {
	ID, MemberID, AppID, RoleID, AssignedAt, AssignedBy, ExpiresAt,
	RevokedAt, RevokedBy, RevokeReason string
}{
	ID:           "id",
	MemberID:     "member_id",
	AppID:        "app_id",
	RoleID:       "role_id",
	AssignedAt:   "assigned_at",
	AssignedBy:   "assigned_by",
	ExpiresAt:    "expires_at",
	RevokedAt:    "revoked_at",
	RevokedBy:    "revoked_by",
	RevokeReason: "revoke_reason",
}

const (
	MemberAppRolePk                       = "member_app_roles_pkey"
	MemberAppRoleUkMemberIdAppIdRoleIdKey = "member_app_roles_member_id_app_id_role_id_key"
	MemberAppRoleFkMemberIdFkey           = "member_app_roles_member_id_fkey"
)
