// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type MemberRole struct {
	ID           uuid.UUID  `gorm:"type:uuid;primaryKey"`
	TenantID     uuid.UUID  `gorm:"type:uuid;index:idx_member_roles_tenant_id;uniqueIndex:member_roles_tenant_id_member_id_role_id_key,priority:1"`
	MemberID     uuid.UUID  `gorm:"type:uuid;index:idx_member_roles_member_id;uniqueIndex:member_roles_tenant_id_member_id_role_id_key,priority:2"`
	RoleID       uuid.UUID  `gorm:"type:uuid;index:idx_member_roles_role_id;uniqueIndex:member_roles_tenant_id_member_id_role_id_key,priority:3"`
	AssignedAt   time.Time  `gorm:"type:timestamp"`
	AssignedBy   *uuid.UUID `gorm:"type:uuid"`
	ExpiresAt    *time.Time `gorm:"type:timestamp;index:idx_member_roles_expires_at"`
	Scope        *string    `gorm:"type:varchar(100)"`
	RevokedAt    *time.Time `gorm:"type:timestamp;index:idx_member_roles_revoked_at"`
	RevokedBy    *uuid.UUID `gorm:"type:uuid"`
	RevokeReason *string    `gorm:"type:text"`
}

func (MemberRole) TableName() string { return "tenants.member_roles" }

func (m *MemberRole) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var MemberRoleCols = struct {
	ID, TenantID, MemberID, RoleID, AssignedAt, AssignedBy, ExpiresAt,
	Scope, RevokedAt, RevokedBy, RevokeReason string
}{
	ID:           "id",
	TenantID:     "tenant_id",
	MemberID:     "member_id",
	RoleID:       "role_id",
	AssignedAt:   "assigned_at",
	AssignedBy:   "assigned_by",
	ExpiresAt:    "expires_at",
	Scope:        "scope",
	RevokedAt:    "revoked_at",
	RevokedBy:    "revoked_by",
	RevokeReason: "revoke_reason",
}

const (
	MemberRolePk                          = "member_roles_pkey"
	MemberRoleUkTenantIdMemberIdRoleIdKey = "member_roles_tenant_id_member_id_role_id_key"
	MemberRoleFkMemberIdFkey              = "member_roles_member_id_fkey"
	MemberRoleFkTenantIdFkey              = "member_roles_tenant_id_fkey"
)
