// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxid/enums"
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

type Tenant struct {
	ID            uuid.UUID                 `gorm:"type:uuid;primaryKey"`
	TenantID      string                    `gorm:"type:varchar(255);index:idx_tenants_tenant_id;uniqueIndex:tenants_tenant_id_key"`
	Name          string                    `gorm:"type:varchar(255);index:idx_tenants_name"`
	DisplayName   *string                   `gorm:"type:varchar(255)"`
	Status        enums.TenantsTenantStatus `gorm:"type:tenant_status;index:idx_tenants_status"`
	PrimaryDomain *string                   `gorm:"type:varchar(255);index:idx_tenants_primary_domain"`
	CreatedAt     time.Time                 `gorm:"autoCreateTime"`
	UpdatedAt     time.Time                 `gorm:"autoUpdateTime"`
	DeletedAt     gorm.DeletedAt            `gorm:"index"`
	Metadata      *datatypes.JSON           `gorm:"type:jsonb"`
}

func (Tenant) TableName() string { return "tenants.tenants" }

func (m *Tenant) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var TenantCols = struct {
	ID, TenantID, Name, DisplayName, Status, PrimaryDomain, CreatedAt,
	UpdatedAt, DeletedAt, Metadata string
}{
	ID:            "id",
	TenantID:      "tenant_id",
	Name:          "name",
	DisplayName:   "display_name",
	Status:        "status",
	PrimaryDomain: "primary_domain",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
	DeletedAt:     "deleted_at",
	Metadata:      "metadata",
}

const (
	TenantPk            = "tenants_pkey"
	TenantUkTenantIdKey = "tenants_tenant_id_key"
)
