// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxid/enums"
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

type TenantApplication struct {
	ID            uuid.UUID                            `gorm:"type:uuid;primaryKey"`
	TenantID      uuid.UUID                            `gorm:"type:uuid;index:idx_tenant_applications_tenant_id;uniqueIndex:tenant_applications_tenant_id_application_id_key,priority:1"`
	ApplicationID uuid.UUID                            `gorm:"type:uuid;index:idx_tenant_applications_application_id;uniqueIndex:tenant_applications_tenant_id_application_id_key,priority:2"`
	Status        enums.TenantsTenantApplicationStatus `gorm:"type:tenant_application_status;index:idx_tenant_applications_status"`
	CreatedAt     time.Time                            `gorm:"autoCreateTime"`
	CreatedBy     *uuid.UUID                           `gorm:"type:uuid"`
	UpdatedAt     time.Time                            `gorm:"autoUpdateTime"`
	Settings      *datatypes.JSON                      `gorm:"type:jsonb"`
}

func (TenantApplication) TableName() string { return "tenants.tenant_applications" }

func (m *TenantApplication) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var TenantApplicationCols = struct {
	ID, TenantID, ApplicationID, Status, CreatedAt, CreatedBy, UpdatedAt,
	Settings string
}{
	ID:            "id",
	TenantID:      "tenant_id",
	ApplicationID: "application_id",
	Status:        "status",
	CreatedAt:     "created_at",
	CreatedBy:     "created_by",
	UpdatedAt:     "updated_at",
	Settings:      "settings",
}

const (
	TenantApplicationPk                         = "tenant_applications_pkey"
	TenantApplicationUkTenantIdApplicationIdKey = "tenant_applications_tenant_id_application_id_key"
	TenantApplicationFkTenantIdFkey             = "tenant_applications_tenant_id_fkey"
)
