// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxid/enums"
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

type TenantApp struct {
	ID        uuid.UUID                    `gorm:"type:uuid;primaryKey"`
	TenantID  uuid.UUID                    `gorm:"type:uuid;index:idx_tenant_apps_tenant_id;uniqueIndex:tenant_apps_tenant_id_app_id_key,priority:1"`
	AppID     uuid.UUID                    `gorm:"type:uuid;index:idx_tenant_apps_app_id;uniqueIndex:tenant_apps_tenant_id_app_id_key,priority:2"`
	Status    enums.TenantsTenantAppStatus `gorm:"type:tenant_app_status;index:idx_tenant_apps_status"`
	CreatedAt time.Time                    `gorm:"autoCreateTime"`
	CreatedBy *uuid.UUID                   `gorm:"type:uuid"`
	UpdatedAt time.Time                    `gorm:"autoUpdateTime"`
	Settings  *datatypes.JSON              `gorm:"type:jsonb"`
}

func (TenantApp) TableName() string { return "tenants.tenant_apps" }

func (m *TenantApp) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var TenantAppCols = struct {
	ID, TenantID, AppID, Status, CreatedAt, CreatedBy, UpdatedAt,
	Settings string
}{
	ID:        "id",
	TenantID:  "tenant_id",
	AppID:     "app_id",
	Status:    "status",
	CreatedAt: "created_at",
	CreatedBy: "created_by",
	UpdatedAt: "updated_at",
	Settings:  "settings",
}

const (
	TenantAppPk                 = "tenant_apps_pkey"
	TenantAppUkTenantIdAppIdKey = "tenant_apps_tenant_id_app_id_key"
	TenantAppFkTenantIdFkey     = "tenant_apps_tenant_id_fkey"
)
