// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

type TenantSetting struct {
	ID                  uuid.UUID       `gorm:"type:uuid;primaryKey"`
	TenantID            uuid.UUID       `gorm:"type:uuid;index:idx_tenant_settings_tenant_id;uniqueIndex:tenant_settings_tenant_id_key"`
	EnforceMfa          bool            `gorm:"type:boolean"`
	AllowedEmailDomains *string         `gorm:"type:text[]"`
	SessionTtlMinutes   *int            `gorm:"type:integer"`
	PasswordPolicy      *datatypes.JSON `gorm:"type:jsonb"`
	LoginPolicy         *datatypes.JSON `gorm:"type:jsonb"`
	MfaPolicy           *datatypes.JSON `gorm:"type:jsonb"`
	CreatedAt           time.Time       `gorm:"autoCreateTime"`
	UpdatedAt           time.Time       `gorm:"autoUpdateTime"`
	UpdatedBy           *uuid.UUID      `gorm:"type:uuid"`
}

func (TenantSetting) TableName() string { return "tenants.tenant_settings" }

func (m *TenantSetting) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var TenantSettingCols = struct {
	ID, TenantID, EnforceMfa, AllowedEmailDomains, SessionTtlMinutes, PasswordPolicy, LoginPolicy,
	MfaPolicy, CreatedAt, UpdatedAt, UpdatedBy string
}{
	ID:                  "id",
	TenantID:            "tenant_id",
	EnforceMfa:          "enforce_mfa",
	AllowedEmailDomains: "allowed_email_domains",
	SessionTtlMinutes:   "session_ttl_minutes",
	PasswordPolicy:      "password_policy",
	LoginPolicy:         "login_policy",
	MfaPolicy:           "mfa_policy",
	CreatedAt:           "created_at",
	UpdatedAt:           "updated_at",
	UpdatedBy:           "updated_by",
}

const (
	TenantSettingPk             = "tenant_settings_pkey"
	TenantSettingUkTenantIdKey  = "tenant_settings_tenant_id_key"
	TenantSettingFkTenantIdFkey = "tenant_settings_tenant_id_fkey"
)
