// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxidentity/enums"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type Account struct {
	ID             uuid.UUID                `gorm:"type:uuid;primaryKey"`
	AccountStatus  enums.AuthAccountStatus  `gorm:"type:account_status;index:idx_accounts_account_status"`
	SignupPlatform enums.AuthSignupPlatform `gorm:"type:signup_platform;index:idx_accounts_signup_platform"`
	CreatedAt      time.Time                `gorm:"autoCreateTime"`
	UpdatedAt      time.Time                `gorm:"autoUpdateTime"`
	DeletedAt      gorm.DeletedAt           `gorm:"index"`
}

func (Account) TableName() string { return "auth.Accounts" }

func (m *Account) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var AccountCols = struct {
	ID, AccountStatus, SignupPlatform, CreatedAt, UpdatedAt, DeletedAt string
}{
	ID:             "id",
	AccountStatus:  "account_status",
	SignupPlatform: "signup_platform",
	CreatedAt:      "created_at",
	UpdatedAt:      "updated_at",
	DeletedAt:      "deleted_at",
}

const (
	AccountPk = "Accounts_pkey"
)
