// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxid/enums"
	"time"

	"github.com/google/uuid"
)

type AccountLockout struct {
	UserID        uuid.UUID            `gorm:"type:uuid;primaryKey"`
	TenantID      uuid.UUID            `gorm:"type:uuid;index:idx_account_lockouts_tenant_id"`
	LockedUntil   *time.Time           `gorm:"type:timestamp;index:idx_account_lockouts_locked_until"`
	LockReason    enums.AuthLockReason `gorm:"type:lock_reason"`
	LockedAt      time.Time            `gorm:"type:timestamp;index:idx_account_lockouts_locked_at"`
	LockedBy      *string              `gorm:"type:varchar(255)"`
	ActorID       *uuid.UUID           `gorm:"type:uuid"`
	UnlockedAt    *time.Time           `gorm:"type:timestamp"`
	UnlockedBy    *string              `gorm:"type:varchar(255)"`
	UnlockActorID *uuid.UUID           `gorm:"type:uuid"`
	CreatedAt     time.Time            `gorm:"autoCreateTime"`
	UpdatedAt     time.Time            `gorm:"autoUpdateTime"`
}

func (AccountLockout) TableName() string { return "auth.account_lockouts" }

var AccountLockoutCols = struct {
	UserID, TenantID, LockedUntil, LockReason, LockedAt, LockedBy, ActorID,
	UnlockedAt, UnlockedBy, UnlockActorID, CreatedAt, UpdatedAt string
}{
	UserID:        "user_id",
	TenantID:      "tenant_id",
	LockedUntil:   "locked_until",
	LockReason:    "lock_reason",
	LockedAt:      "locked_at",
	LockedBy:      "locked_by",
	ActorID:       "actor_id",
	UnlockedAt:    "unlocked_at",
	UnlockedBy:    "unlocked_by",
	UnlockActorID: "unlock_actor_id",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
}

const (
	AccountLockoutPk = "account_lockouts_pkey"
)
