// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type AuthorityProfileSetting struct {
	ID                uuid.UUID      `gorm:"type:uuid;primaryKey"`
	LoginNotification bool           `gorm:"type:boolean"`
	CreatedAt         time.Time      `gorm:"autoCreateTime"`
	UpdatedAt         time.Time      `gorm:"autoUpdateTime"`
	DeletedAt         gorm.DeletedAt `gorm:"index"`
}

func (AuthorityProfileSetting) TableName() string { return "auth.AuthorityProfileSettings" }

func (m *AuthorityProfileSetting) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var AuthorityProfileSettingCols = struct {
	ID, LoginNotification, CreatedAt, UpdatedAt, DeletedAt string
}{
	ID:                "id",
	LoginNotification: "login_notification",
	CreatedAt:         "created_at",
	UpdatedAt:         "updated_at",
	DeletedAt:         "deleted_at",
}

const (
	AuthorityProfileSettingPk                           = "AuthorityProfileSettings_pkey"
	AuthorityProfileSettingFkAuthorityProfileSettingsId = "fk_authority_profile_settings_id"
)
