// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type AuthorityProfileAvatar struct {
	ID        uuid.UUID      `gorm:"type:uuid;primaryKey"`
	ProfileID uuid.UUID      `gorm:"type:uuid;index:idx_authority_profile_avatars_profile_id;uniqueIndex:uq_authority_profile_avatars_one_active_per_profile"`
	ImageID   uuid.UUID      `gorm:"type:uuid;index:idx_authority_profile_avatars_image_id"`
	IsActive  bool           `gorm:"type:boolean"`
	CreatedAt time.Time      `gorm:"autoCreateTime"`
	UpdatedAt time.Time      `gorm:"autoUpdateTime"`
	DeletedAt gorm.DeletedAt `gorm:"index"`
}

func (AuthorityProfileAvatar) TableName() string { return "auth.AuthorityProfileAvatars" }

func (m *AuthorityProfileAvatar) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var AuthorityProfileAvatarCols = struct {
	ID, ProfileID, ImageID, IsActive, CreatedAt, UpdatedAt, DeletedAt string
}{
	ID:        "id",
	ProfileID: "profile_id",
	ImageID:   "image_id",
	IsActive:  "is_active",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
}

const (
	AuthorityProfileAvatarPk                                           = "AuthorityProfileAvatars_pkey"
	AuthorityProfileAvatarUkAuthorityProfileAvatarsOneActivePerProfile = "uq_authority_profile_avatars_one_active_per_profile"
	AuthorityProfileAvatarFkAuthorityProfileAvatarsProfileId           = "fk_authority_profile_avatars_profile_id"
)
