// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type Email struct {
	ID         uuid.UUID      `gorm:"type:uuid;primaryKey"`
	AccountID  uuid.UUID      `gorm:"type:uuid;index:idx_emails_account_id;uniqueIndex:uq_emails_one_primary_per_account"`
	Email      string         `gorm:"type:varchar(255)"`
	IsPrimary  bool           `gorm:"type:boolean"`
	VerifiedAt *time.Time     `gorm:"type:timestamp"`
	CreatedAt  time.Time      `gorm:"autoCreateTime"`
	UpdatedAt  time.Time      `gorm:"autoUpdateTime"`
	DeletedAt  gorm.DeletedAt `gorm:"index"`
}

func (Email) TableName() string { return "auth.Emails" }

func (m *Email) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var EmailCols = struct {
	ID, AccountID, Email, IsPrimary, VerifiedAt, CreatedAt, UpdatedAt,
	DeletedAt string
}{
	ID:         "id",
	AccountID:  "account_id",
	Email:      "email",
	IsPrimary:  "is_primary",
	VerifiedAt: "verified_at",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
	DeletedAt:  "deleted_at",
}

const (
	EmailPk                     = "Emails_pkey"
	EmailUkEmailCi              = "uq_emails_email_ci"
	EmailUkOnePrimaryPerAccount = "uq_emails_one_primary_per_account"
	EmailFkAccountId            = "fk_emails_account_id"
)
