// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxidentity/enums"
	"nfxidentity/pkgs/enumx"
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

type ForgerProfile struct {
	ID              uuid.UUID                         `gorm:"type:uuid;primaryKey"`
	AccountID       uuid.UUID                         `gorm:"type:uuid;index:idx_forger_profiles_account_id"`
	ForgerRoles     enumx.Array[enums.AuthForgerRole] `gorm:"type:auth.forger_role[];index:idx_forger_profiles_forger_roles"`
	ProfileLanguage enums.AuthProfileLanguage         `gorm:"type:profile_language;index:idx_forger_profiles_profile_language"`
	Preference      *datatypes.JSON                   `gorm:"type:jsonb"`
	DisplayName     *string                           `gorm:"type:varchar(150)"`
	FirstName       *string                           `gorm:"type:varchar(100)"`
	LastName        *string                           `gorm:"type:varchar(100)"`
	Country         *string                           `gorm:"type:varchar(100)"`
	City            *string                           `gorm:"type:varchar(100)"`
	Gender          *string                           `gorm:"type:varchar(100)"`
	Birthday        *time.Time                        `gorm:"type:date"`
	Website         *string                           `gorm:"type:varchar(100)"`
	Timezone        *string                           `gorm:"type:varchar(100)"`
	Bio             *string                           `gorm:"type:text"`
	CreatedAt       time.Time                         `gorm:"autoCreateTime"`
	UpdatedAt       time.Time                         `gorm:"autoUpdateTime"`
	DeletedAt       gorm.DeletedAt                    `gorm:"index"`
}

func (ForgerProfile) TableName() string { return "auth.ForgerProfiles" }

func (m *ForgerProfile) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var ForgerProfileCols = struct {
	ID, AccountID, ForgerRoles, ProfileLanguage, Preference, DisplayName, FirstName,
	LastName, Country, City, Gender, Birthday, Website, Timezone,
	Bio, CreatedAt, UpdatedAt, DeletedAt string
}{
	ID:              "id",
	AccountID:       "account_id",
	ForgerRoles:     "forger_roles",
	ProfileLanguage: "profile_language",
	Preference:      "preference",
	DisplayName:     "display_name",
	FirstName:       "first_name",
	LastName:        "last_name",
	Country:         "country",
	City:            "city",
	Gender:          "gender",
	Birthday:        "birthday",
	Website:         "website",
	Timezone:        "timezone",
	Bio:             "bio",
	CreatedAt:       "created_at",
	UpdatedAt:       "updated_at",
	DeletedAt:       "deleted_at",
}

const (
	ForgerProfilePk                        = "ForgerProfiles_pkey"
	ForgerProfileFkForgerProfilesAccountId = "fk_forger_profiles_account_id"
)
