// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type Forgerprofilebackground struct {
	ID        uuid.UUID      `gorm:"type:uuid;primaryKey"`
	ProfileID uuid.UUID      `gorm:"type:uuid;index:idx_forger_profile_backgrounds_profile_id;index:idx_forger_profile_backgrounds_profile_sort,priority:1"`
	ImageID   uuid.UUID      `gorm:"type:uuid;index:idx_forger_profile_backgrounds_image_id"`
	SortOrder int            `gorm:"type:integer;index:idx_forger_profile_backgrounds_profile_sort,priority:2"`
	CreatedAt time.Time      `gorm:"autoCreateTime"`
	UpdatedAt time.Time      `gorm:"autoUpdateTime"`
	DeletedAt gorm.DeletedAt `gorm:"index"`
}

func (Forgerprofilebackground) TableName() string { return "auth.ForgerProfileBackgrounds" }

func (m *Forgerprofilebackground) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var ForgerprofilebackgroundCols = struct {
	ID, ProfileID, ImageID, SortOrder, CreatedAt, UpdatedAt, DeletedAt string
}{
	ID:        "id",
	ProfileID: "profile_id",
	ImageID:   "image_id",
	SortOrder: "sort_order",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
}

const (
	ForgerprofilebackgroundPk                                  = "ForgerProfileBackgrounds_pkey"
	ForgerprofilebackgroundFkForgerProfileBackgroundsProfileId = "fk_forger_profile_backgrounds_profile_id"
)
