// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type ForgerProfileSetting struct {
	ID                uuid.UUID      `gorm:"type:uuid;primaryKey"`
	LoginNotification bool           `gorm:"type:boolean"`
	CreatedAt         time.Time      `gorm:"autoCreateTime"`
	UpdatedAt         time.Time      `gorm:"autoUpdateTime"`
	DeletedAt         gorm.DeletedAt `gorm:"index"`
}

func (ForgerProfileSetting) TableName() string { return "auth.ForgerProfileSettings" }

func (m *ForgerProfileSetting) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var ForgerProfileSettingCols = struct {
	ID, LoginNotification, CreatedAt, UpdatedAt, DeletedAt string
}{
	ID:                "id",
	LoginNotification: "login_notification",
	CreatedAt:         "created_at",
	UpdatedAt:         "updated_at",
	DeletedAt:         "deleted_at",
}

const (
	ForgerProfileSettingPk                        = "ForgerProfileSettings_pkey"
	ForgerProfileSettingFkForgerProfileSettingsId = "fk_forger_profile_settings_id"
)
