// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxidentity/enums"
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

type Identity struct {
	ID               uuid.UUID                  `gorm:"type:uuid;primaryKey"`
	AccountID        uuid.UUID                  `gorm:"type:uuid;index:idx_identities_account_id"`
	IdentityProvider enums.AuthIdentityProvider `gorm:"type:identity_provider;uniqueIndex:uq_identities_identity_provider_subject_active,priority:1"`
	ProviderSubject  string                     `gorm:"type:text;uniqueIndex:uq_identities_identity_provider_subject_active,priority:2"`
	PasswordHash     *string                    `gorm:"type:text"`
	Metadata         *datatypes.JSON            `gorm:"type:jsonb"`
	LastLoginAt      *time.Time                 `gorm:"type:timestamp"`
	CreatedAt        time.Time                  `gorm:"autoCreateTime"`
	UpdatedAt        time.Time                  `gorm:"autoUpdateTime"`
	DeletedAt        gorm.DeletedAt             `gorm:"index"`
}

func (Identity) TableName() string { return "auth.Identities" }

func (m *Identity) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var IdentityCols = struct {
	ID, AccountID, IdentityProvider, ProviderSubject, PasswordHash, Metadata, LastLoginAt,
	CreatedAt, UpdatedAt, DeletedAt string
}{
	ID:               "id",
	AccountID:        "account_id",
	IdentityProvider: "identity_provider",
	ProviderSubject:  "provider_subject",
	PasswordHash:     "password_hash",
	Metadata:         "metadata",
	LastLoginAt:      "last_login_at",
	CreatedAt:        "created_at",
	UpdatedAt:        "updated_at",
	DeletedAt:        "deleted_at",
}

const (
	IdentityPk                              = "Identities_pkey"
	IdentityUkIdentityProviderSubjectActive = "uq_identities_identity_provider_subject_active"
	IdentityFkAccountId                     = "fk_identities_account_id"
)
