// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxid/enums"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type LoginAttempt struct {
	ID                uuid.UUID              `gorm:"type:uuid;primaryKey"`
	Identifier        string                 `gorm:"type:varchar(255);index:idx_login_attempts_identifier,priority:1"`
	UserID            *uuid.UUID             `gorm:"type:uuid;index:idx_login_attempts_user_id,priority:1"`
	IP                *string                `gorm:"type:inet;index:idx_login_attempts_ip,priority:1"`
	UaHash            *string                `gorm:"type:varchar(64)"`
	DeviceFingerprint *string                `gorm:"type:varchar(255)"`
	Success           bool                   `gorm:"type:boolean;index:idx_login_attempts_success,priority:1"`
	FailureCode       *enums.AuthFailureCode `gorm:"type:failure_code"`
	MfaRequired       bool                   `gorm:"type:boolean"`
	MfaVerified       bool                   `gorm:"type:boolean"`
	CreatedAt         time.Time              `gorm:"autoCreateTime"`
}

func (LoginAttempt) TableName() string { return "auth.login_attempts" }

func (m *LoginAttempt) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var LoginAttemptCols = struct {
	ID, Identifier, UserID, IP, UaHash, DeviceFingerprint, Success,
	FailureCode, MfaRequired, MfaVerified, CreatedAt string
}{
	ID:                "id",
	Identifier:        "identifier",
	UserID:            "user_id",
	IP:                "ip",
	UaHash:            "ua_hash",
	DeviceFingerprint: "device_fingerprint",
	Success:           "success",
	FailureCode:       "failure_code",
	MfaRequired:       "mfa_required",
	MfaVerified:       "mfa_verified",
	CreatedAt:         "created_at",
}

const (
	LoginAttemptPk = "login_attempts_pkey"
)
