// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxid/enums"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type MfaFactor struct {
	ID                uuid.UUID         `gorm:"type:uuid;primaryKey"`
	FactorID          string            `gorm:"type:varchar(255);index:idx_mfa_factors_factor_id;uniqueIndex:mfa_factors_factor_id_key"`
	UserID            uuid.UUID         `gorm:"type:uuid;index:idx_mfa_factors_enabled,priority:1;index:idx_mfa_factors_user_id"`
	Type              enums.AuthMfaType `gorm:"type:mfa_type;index:idx_mfa_factors_type"`
	SecretEncrypted   *string           `gorm:"type:text"`
	Phone             *string           `gorm:"type:varchar(20)"`
	Email             *string           `gorm:"type:varchar(255)"`
	Name              *string           `gorm:"type:varchar(255)"`
	Enabled           bool              `gorm:"type:boolean;index:idx_mfa_factors_enabled,priority:2"`
	CreatedAt         time.Time         `gorm:"autoCreateTime"`
	LastUsedAt        *time.Time        `gorm:"type:timestamp"`
	RecoveryCodesHash *string           `gorm:"type:text"`
	UpdatedAt         time.Time         `gorm:"autoUpdateTime"`
	DeletedAt         gorm.DeletedAt    `gorm:"index"`
}

func (MfaFactor) TableName() string { return "auth.mfa_factors" }

func (m *MfaFactor) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var MfaFactorCols = struct {
	ID, FactorID, UserID, Type, SecretEncrypted, Phone, Email,
	Name, Enabled, CreatedAt, LastUsedAt, RecoveryCodesHash, UpdatedAt, DeletedAt string
}{
	ID:                "id",
	FactorID:          "factor_id",
	UserID:            "user_id",
	Type:              "type",
	SecretEncrypted:   "secret_encrypted",
	Phone:             "phone",
	Email:             "email",
	Name:              "name",
	Enabled:           "enabled",
	CreatedAt:         "created_at",
	LastUsedAt:        "last_used_at",
	RecoveryCodesHash: "recovery_codes_hash",
	UpdatedAt:         "updated_at",
	DeletedAt:         "deleted_at",
}

const (
	MfaFactorPk            = "mfa_factors_pkey"
	MfaFactorUkFactorIdKey = "mfa_factors_factor_id_key"
)
