// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type Occupation struct {
	ID               uuid.UUID      `gorm:"type:uuid;primaryKey"`
	ProfileID        uuid.UUID      `gorm:"type:uuid;index:idx_occupations_profile_id"`
	Company          string         `gorm:"type:varchar(255);index:idx_occupations_company"`
	Position         string         `gorm:"type:varchar(255);index:idx_occupations_position"`
	Department       *string        `gorm:"type:varchar(255)"`
	Industry         *string        `gorm:"type:varchar(100);index:idx_occupations_industry"`
	Location         *string        `gorm:"type:varchar(255)"`
	EmploymentType   *string        `gorm:"type:varchar(50)"`
	StartDate        *time.Time     `gorm:"type:date"`
	EndDate          *time.Time     `gorm:"type:date"`
	IsCurrent        bool           `gorm:"type:boolean;index:idx_occupations_is_current"`
	Description      *string        `gorm:"type:text"`
	Responsibilities *string        `gorm:"type:text"`
	Achievements     *string        `gorm:"type:text"`
	SkillsUsed       *string        `gorm:"type:text[]"`
	CreatedAt        time.Time      `gorm:"autoCreateTime"`
	UpdatedAt        time.Time      `gorm:"autoUpdateTime"`
	DeletedAt        gorm.DeletedAt `gorm:"index"`
}

func (Occupation) TableName() string { return "auth.occupations" }

func (m *Occupation) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var OccupationCols = struct {
	ID, ProfileID, Company, Position, Department, Industry, Location,
	EmploymentType, StartDate, EndDate, IsCurrent, Description, Responsibilities, Achievements,
	SkillsUsed, CreatedAt, UpdatedAt, DeletedAt string
}{
	ID:               "id",
	ProfileID:        "profile_id",
	Company:          "company",
	Position:         "position",
	Department:       "department",
	Industry:         "industry",
	Location:         "location",
	EmploymentType:   "employment_type",
	StartDate:        "start_date",
	EndDate:          "end_date",
	IsCurrent:        "is_current",
	Description:      "description",
	Responsibilities: "responsibilities",
	Achievements:     "achievements",
	SkillsUsed:       "skills_used",
	CreatedAt:        "created_at",
	UpdatedAt:        "updated_at",
	DeletedAt:        "deleted_at",
}

const (
	OccupationPk              = "occupations_pkey"
	OccupationFkProfileIdFkey = "occupations_profile_id_fkey"
)
