// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type PasswordHistory struct {
	ID           uuid.UUID `gorm:"type:uuid;primaryKey"`
	UserID       uuid.UUID `gorm:"type:uuid;index:idx_password_history_user_id,priority:1"`
	TenantID     uuid.UUID `gorm:"type:uuid;index:idx_password_history_tenant_id"`
	PasswordHash string    `gorm:"type:varchar(255)"`
	HashAlg      *string   `gorm:"type:varchar(50)"`
	CreatedAt    time.Time `gorm:"autoCreateTime"`
}

func (PasswordHistory) TableName() string { return "auth.password_history" }

func (m *PasswordHistory) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var PasswordHistoryCols = struct {
	ID, UserID, TenantID, PasswordHash, HashAlg, CreatedAt string
}{
	ID:           "id",
	UserID:       "user_id",
	TenantID:     "tenant_id",
	PasswordHash: "password_hash",
	HashAlg:      "hash_alg",
	CreatedAt:    "created_at",
}

const (
	PasswordHistoryPk = "password_history_pkey"
)
