// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxid/enums"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type PasswordReset struct {
	ID           uuid.UUID               `gorm:"type:uuid;primaryKey"`
	ResetID      string                  `gorm:"type:varchar(255);index:idx_password_resets_reset_id;uniqueIndex:password_resets_reset_id_key"`
	UserID       uuid.UUID               `gorm:"type:uuid;index:idx_password_resets_user_id"`
	Delivery     enums.AuthResetDelivery `gorm:"type:reset_delivery"`
	CodeHash     string                  `gorm:"type:varchar(255)"`
	ExpiresAt    time.Time               `gorm:"type:timestamp;index:idx_password_resets_expires_at"`
	UsedAt       *time.Time              `gorm:"type:timestamp"`
	RequestedIP  *string                 `gorm:"type:inet"`
	UaHash       *string                 `gorm:"type:varchar(64)"`
	AttemptCount int                     `gorm:"type:integer"`
	Status       enums.AuthResetStatus   `gorm:"type:reset_status;index:idx_password_resets_status"`
	CreatedAt    time.Time               `gorm:"autoCreateTime"`
	UpdatedAt    time.Time               `gorm:"autoUpdateTime"`
}

func (PasswordReset) TableName() string { return "auth.password_resets" }

func (m *PasswordReset) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var PasswordResetCols = struct {
	ID, ResetID, UserID, Delivery, CodeHash, ExpiresAt, UsedAt,
	RequestedIP, UaHash, AttemptCount, Status, CreatedAt, UpdatedAt string
}{
	ID:           "id",
	ResetID:      "reset_id",
	UserID:       "user_id",
	Delivery:     "delivery",
	CodeHash:     "code_hash",
	ExpiresAt:    "expires_at",
	UsedAt:       "used_at",
	RequestedIP:  "requested_ip",
	UaHash:       "ua_hash",
	AttemptCount: "attempt_count",
	Status:       "status",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
}

const (
	PasswordResetPk           = "password_resets_pkey"
	PasswordResetUkResetIdKey = "password_resets_reset_id_key"
)
