// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type Phone struct {
	ID         uuid.UUID      `gorm:"type:uuid;primaryKey"`
	AccountID  uuid.UUID      `gorm:"type:uuid;index:idx_phones_account_id;uniqueIndex:uq_phones_one_primary_per_account"`
	Phone      string         `gorm:"type:varchar(32);uniqueIndex:uq_phones_phone_active"`
	IsPrimary  bool           `gorm:"type:boolean"`
	VerifiedAt *time.Time     `gorm:"type:timestamp"`
	CreatedAt  time.Time      `gorm:"autoCreateTime"`
	UpdatedAt  time.Time      `gorm:"autoUpdateTime"`
	DeletedAt  gorm.DeletedAt `gorm:"index"`
}

func (Phone) TableName() string { return "auth.Phones" }

func (m *Phone) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var PhoneCols = struct {
	ID, AccountID, Phone, IsPrimary, VerifiedAt, CreatedAt, UpdatedAt,
	DeletedAt string
}{
	ID:         "id",
	AccountID:  "account_id",
	Phone:      "phone",
	IsPrimary:  "is_primary",
	VerifiedAt: "verified_at",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
	DeletedAt:  "deleted_at",
}

const (
	PhonePk                     = "Phones_pkey"
	PhoneUkOnePrimaryPerAccount = "uq_phones_one_primary_per_account"
	PhoneUkPhoneActive          = "uq_phones_phone_active"
	PhoneFkAccountId            = "fk_phones_account_id"
)
