// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type ProfileEducation struct {
	ID           uuid.UUID      `gorm:"type:uuid;primaryKey"`
	ProfileID    uuid.UUID      `gorm:"type:uuid;index:idx_profile_educations_profile_id"`
	School       string         `gorm:"type:varchar(255);index:idx_profile_educations_school"`
	Degree       *string        `gorm:"type:varchar(100);index:idx_profile_educations_degree"`
	Major        *string        `gorm:"type:varchar(255)"`
	FieldOfStudy *string        `gorm:"type:varchar(255)"`
	StartDate    *time.Time     `gorm:"type:date"`
	EndDate      *time.Time     `gorm:"type:date"`
	IsCurrent    bool           `gorm:"type:boolean"`
	Description  *string        `gorm:"type:text"`
	Grade        *string        `gorm:"type:varchar(50)"`
	Activities   *string        `gorm:"type:text"`
	Achievements *string        `gorm:"type:text"`
	CreatedAt    time.Time      `gorm:"autoCreateTime"`
	UpdatedAt    time.Time      `gorm:"autoUpdateTime"`
	DeletedAt    gorm.DeletedAt `gorm:"index"`
}

func (ProfileEducation) TableName() string { return "auth.profile_educations" }

func (m *ProfileEducation) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var ProfileEducationCols = struct {
	ID, ProfileID, School, Degree, Major, FieldOfStudy, StartDate,
	EndDate, IsCurrent, Description, Grade, Activities, Achievements, CreatedAt,
	UpdatedAt, DeletedAt string
}{
	ID:           "id",
	ProfileID:    "profile_id",
	School:       "school",
	Degree:       "degree",
	Major:        "major",
	FieldOfStudy: "field_of_study",
	StartDate:    "start_date",
	EndDate:      "end_date",
	IsCurrent:    "is_current",
	Description:  "description",
	Grade:        "grade",
	Activities:   "activities",
	Achievements: "achievements",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
	DeletedAt:    "deleted_at",
}

const (
	ProfileEducationPk              = "profile_educations_pkey"
	ProfileEducationFkProfileIdFkey = "profile_educations_profile_id_fkey"
)
