// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxidentity/enums"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type Refreshtoken struct {
	ID           uuid.UUID               `gorm:"type:uuid;primaryKey"`
	AccountID    uuid.UUID               `gorm:"type:uuid;index:idx_refresh_tokens_account_device_active,priority:1;index:idx_refresh_tokens_account_id"`
	IdentityID   *uuid.UUID              `gorm:"type:uuid;index:idx_refresh_tokens_identity_id"`
	ProfileID    *uuid.UUID              `gorm:"type:uuid"`
	ProfileScope *enums.AuthProfileScope `gorm:"type:profile_scope"`
	DeviceID     *string                 `gorm:"type:text;index:idx_refresh_tokens_account_device_active,priority:2;index:idx_refresh_tokens_device_id"`
	TokenHash    string                  `gorm:"type:text"`
	ExpiresAt    time.Time               `gorm:"type:timestamp;index:idx_refresh_tokens_expires_at"`
	RevokedAt    *time.Time              `gorm:"type:timestamp;index:idx_refresh_tokens_revoked_at"`
	CreatedAt    time.Time               `gorm:"autoCreateTime"`
	DeletedAt    gorm.DeletedAt          `gorm:"index"`
}

func (Refreshtoken) TableName() string { return "auth.RefreshTokens" }

func (m *Refreshtoken) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var RefreshtokenCols = struct {
	ID, AccountID, IdentityID, ProfileID, ProfileScope, DeviceID, TokenHash,
	ExpiresAt, RevokedAt, CreatedAt, DeletedAt string
}{
	ID:           "id",
	AccountID:    "account_id",
	IdentityID:   "identity_id",
	ProfileID:    "profile_id",
	ProfileScope: "profile_scope",
	DeviceID:     "device_id",
	TokenHash:    "token_hash",
	ExpiresAt:    "expires_at",
	RevokedAt:    "revoked_at",
	CreatedAt:    "created_at",
	DeletedAt:    "deleted_at",
}

const (
	RefreshtokenPk                        = "RefreshTokens_pkey"
	RefreshtokenFkRefreshTokensAccountId  = "fk_refresh_tokens_account_id"
	RefreshtokenFkRefreshTokensIdentityId = "fk_refresh_tokens_identity_id"
)
