// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxid/enums"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type Session struct {
	ID                uuid.UUID                      `gorm:"type:uuid;primaryKey"`
	SessionID         string                         `gorm:"type:varchar(255);index:idx_sessions_session_id;uniqueIndex:sessions_session_id_key"`
	UserID            uuid.UUID                      `gorm:"type:uuid;index:idx_sessions_user_active,priority:1;index:idx_sessions_user_id"`
	AppID             *uuid.UUID                     `gorm:"type:uuid;index:idx_sessions_app_id"`
	ClientID          *string                        `gorm:"type:varchar(255)"`
	CreatedAt         time.Time                      `gorm:"autoCreateTime"`
	LastSeenAt        time.Time                      `gorm:"type:timestamp;index:idx_sessions_last_seen_at"`
	ExpiresAt         time.Time                      `gorm:"type:timestamp;index:idx_sessions_expires_at"`
	IP                *string                        `gorm:"type:inet"`
	UaHash            *string                        `gorm:"type:varchar(64)"`
	DeviceID          *string                        `gorm:"type:varchar(255)"`
	DeviceFingerprint *string                        `gorm:"type:varchar(255)"`
	DeviceName        *string                        `gorm:"type:varchar(255)"`
	RevokedAt         *time.Time                     `gorm:"type:timestamp;index:idx_sessions_revoked_at;index:idx_sessions_user_active,priority:2"`
	RevokeReason      *enums.AuthSessionRevokeReason `gorm:"type:session_revoke_reason"`
	RevokedBy         *string                        `gorm:"type:varchar(255)"`
	UpdatedAt         time.Time                      `gorm:"autoUpdateTime"`
}

func (Session) TableName() string { return "auth.sessions" }

func (m *Session) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var SessionCols = struct {
	ID, SessionID, UserID, AppID, ClientID, CreatedAt, LastSeenAt,
	ExpiresAt, IP, UaHash, DeviceID, DeviceFingerprint, DeviceName, RevokedAt,
	RevokeReason, RevokedBy, UpdatedAt string
}{
	ID:                "id",
	SessionID:         "session_id",
	UserID:            "user_id",
	AppID:             "app_id",
	ClientID:          "client_id",
	CreatedAt:         "created_at",
	LastSeenAt:        "last_seen_at",
	ExpiresAt:         "expires_at",
	IP:                "ip",
	UaHash:            "ua_hash",
	DeviceID:          "device_id",
	DeviceFingerprint: "device_fingerprint",
	DeviceName:        "device_name",
	RevokedAt:         "revoked_at",
	RevokeReason:      "revoke_reason",
	RevokedBy:         "revoked_by",
	UpdatedAt:         "updated_at",
}

const (
	SessionPk             = "sessions_pkey"
	SessionUkSessionIdKey = "sessions_session_id_key"
)
