// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type TrustedDevice struct {
	ID                    uuid.UUID `gorm:"type:uuid;primaryKey"`
	DeviceID              string    `gorm:"type:varchar(255);index:idx_trusted_devices_device_id;uniqueIndex:trusted_devices_user_id_device_id_key,priority:2"`
	UserID                uuid.UUID `gorm:"type:uuid;index:idx_trusted_devices_user_id;uniqueIndex:trusted_devices_user_id_device_id_key,priority:1"`
	DeviceFingerprintHash string    `gorm:"type:varchar(255)"`
	DeviceName            *string   `gorm:"type:varchar(255)"`
	TrustedUntil          time.Time `gorm:"type:timestamp;index:idx_trusted_devices_trusted_until"`
	LastUsedAt            time.Time `gorm:"type:timestamp"`
	IP                    *string   `gorm:"type:inet"`
	UaHash                *string   `gorm:"type:varchar(64)"`
	CreatedAt             time.Time `gorm:"autoCreateTime"`
	UpdatedAt             time.Time `gorm:"autoUpdateTime"`
}

func (TrustedDevice) TableName() string { return "auth.trusted_devices" }

func (m *TrustedDevice) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var TrustedDeviceCols = struct {
	ID, DeviceID, UserID, DeviceFingerprintHash, DeviceName, TrustedUntil, LastUsedAt,
	IP, UaHash, CreatedAt, UpdatedAt string
}{
	ID:                    "id",
	DeviceID:              "device_id",
	UserID:                "user_id",
	DeviceFingerprintHash: "device_fingerprint_hash",
	DeviceName:            "device_name",
	TrustedUntil:          "trusted_until",
	LastUsedAt:            "last_used_at",
	IP:                    "ip",
	UaHash:                "ua_hash",
	CreatedAt:             "created_at",
	UpdatedAt:             "updated_at",
}

const (
	TrustedDevicePk                  = "trusted_devices_pkey"
	TrustedDeviceUkUserIdDeviceIdKey = "trusted_devices_user_id_device_id_key"
)
