// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type UserRole struct {
	ID        uuid.UUID `gorm:"type:uuid;primaryKey"`
	UserID    uuid.UUID `gorm:"type:uuid;index:idx_user_roles_user_id;uniqueIndex:user_roles_user_id_role_id_key,priority:1"`
	RoleID    uuid.UUID `gorm:"type:uuid;index:idx_user_roles_role_id;uniqueIndex:user_roles_user_id_role_id_key,priority:2"`
	CreatedAt time.Time `gorm:"autoCreateTime"`
}

func (UserRole) TableName() string { return "auth.user_roles" }

func (m *UserRole) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var UserRoleCols = struct {
	ID, UserID, RoleID, CreatedAt string
}{
	ID:        "id",
	UserID:    "user_id",
	RoleID:    "role_id",
	CreatedAt: "created_at",
}

const (
	UserRolePk                = "user_roles_pkey"
	UserRoleUkUserIdRoleIdKey = "user_roles_user_id_role_id_key"
	UserRoleFkRoleIdFkey      = "user_roles_role_id_fkey"
	UserRoleFkUserIdFkey      = "user_roles_user_id_fkey"
)
