// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxid/enums"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type User struct {
	ID           uuid.UUID        `gorm:"type:uuid;primaryKey"`
	Username     string           `gorm:"type:varchar(50);index:idx_users_username;uniqueIndex:users_username_key"`
	Email        string           `gorm:"type:varchar(255);index:idx_users_email;uniqueIndex:users_email_key"`
	Phone        string           `gorm:"type:varchar(20);index:idx_users_phone;uniqueIndex:users_phone_key"`
	PasswordHash string           `gorm:"type:varchar(255)"`
	Status       enums.UserStatus `gorm:"type:user_status;index:idx_users_status"`
	IsVerified   bool             `gorm:"type:boolean"`
	LastLoginAt  *time.Time       `gorm:"type:timestamp"`
	CreatedAt    time.Time        `gorm:"autoCreateTime"`
	UpdatedAt    time.Time        `gorm:"autoUpdateTime"`
	DeletedAt    gorm.DeletedAt   `gorm:"index"`
}

func (User) TableName() string { return "auth.users" }

func (m *User) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var UserCols = struct {
	ID, Username, Email, Phone, PasswordHash, Status, IsVerified,
	LastLoginAt, CreatedAt, UpdatedAt, DeletedAt string
}{
	ID:           "id",
	Username:     "username",
	Email:        "email",
	Phone:        "phone",
	PasswordHash: "password_hash",
	Status:       "status",
	IsVerified:   "is_verified",
	LastLoginAt:  "last_login_at",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
	DeletedAt:    "deleted_at",
}

const (
	UserPk            = "users_pkey"
	UserUkEmailKey    = "users_email_key"
	UserUkPhoneKey    = "users_phone_key"
	UserUkUsernameKey = "users_username_key"
)
