// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"nfxid/enums"
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

type UserCredential struct {
	ID                 uuid.UUID                  `gorm:"type:uuid;primaryKey"`
	UserID             uuid.UUID                  `gorm:"type:uuid;index:idx_user_credentials_user_id;uniqueIndex:user_credentials_user_id_key"`
	TenantID           uuid.UUID                  `gorm:"type:uuid;index:idx_user_credentials_tenant_id"`
	CredentialType     enums.AuthCredentialType   `gorm:"type:credential_type;index:idx_user_credentials_type"`
	PasswordHash       *string                    `gorm:"type:varchar(255)"`
	HashAlg            *string                    `gorm:"type:varchar(50)"`
	HashParams         *datatypes.JSON            `gorm:"type:jsonb"`
	PasswordUpdatedAt  *time.Time                 `gorm:"type:timestamp"`
	LastSuccessLoginAt *time.Time                 `gorm:"type:timestamp"`
	Status             enums.AuthCredentialStatus `gorm:"type:credential_status;index:idx_user_credentials_status"`
	MustChangePassword bool                       `gorm:"type:boolean"`
	Version            int                        `gorm:"type:integer"`
	CreatedAt          time.Time                  `gorm:"autoCreateTime"`
	UpdatedAt          time.Time                  `gorm:"autoUpdateTime"`
	DeletedAt          gorm.DeletedAt             `gorm:"index"`
}

func (UserCredential) TableName() string { return "auth.user_credentials" }

func (m *UserCredential) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var UserCredentialCols = struct {
	ID, UserID, TenantID, CredentialType, PasswordHash, HashAlg, HashParams,
	PasswordUpdatedAt, LastSuccessLoginAt, Status, MustChangePassword, Version, CreatedAt, UpdatedAt,
	DeletedAt string
}{
	ID:                 "id",
	UserID:             "user_id",
	TenantID:           "tenant_id",
	CredentialType:     "credential_type",
	PasswordHash:       "password_hash",
	HashAlg:            "hash_alg",
	HashParams:         "hash_params",
	PasswordUpdatedAt:  "password_updated_at",
	LastSuccessLoginAt: "last_success_login_at",
	Status:             "status",
	MustChangePassword: "must_change_password",
	Version:            "version",
	CreatedAt:          "created_at",
	UpdatedAt:          "updated_at",
	DeletedAt:          "deleted_at",
}

const (
	UserCredentialPk          = "user_credentials_pkey"
	UserCredentialUkUserIdKey = "user_credentials_user_id_key"
)
